document.write("<table width=\"760\" border=\"0\" cellspacing=\"0\" cellpadding=\"0\" bgcolor=\"EBCE78\" align=\"center\">");
document.write("  <tr> ");
document.write("    <td align=\"center\" rowspan=\"7\" width=\"6\"><img src=\"http://www.chinadaily.com.cn/image/Dot.gif\" width=\"1\" height=\"1\"></td>");
document.write("    <td align=\"center\" height=\"24\" class=\"v7\" valign=\"bottom\"> ");
document.write("      <p><font face=\"Verdana, Arial, Helvetica, sans-serif\" size=\"1\"><b><font color=\"#FFFFFF\">|</font> ");
document.write("        <a href=\"http://www.chinadaily.com.cn/english/home/index.html\">Home</a><font color=\"#FFFFFF\"> ");
document.write("        |</font> <a href=\"http://www.chinadaily.com.cn/english/home/news.html\">News</a> ");
document.write("        <font color=\"#FFFFFF\">|</font> <a href=\"http://bizchina.chinadaily.com.cn\">Business</a> ");
document.write("        <font color=\"#FFFFFF\">| </font><a href=\"http://www.chinadaily.com.cn/english/livechina/livingchina.html\">Living ");
document.write("        in China</a> <font color=\"#FFFFFF\">|</font> <a href=\"http://bbs.chinadaily.com.cn/\">Forum</a><font color=\"#FFFFFF\"> ");
document.write("        |</font> <a href=\"http://www.chinadaily.com.cn/english/cndy/cdtop.html\">E-Papers</a> ");
document.write("        <font color=#ffffff>|</font><font ");
document.write("      face=\"Verdana, Arial, Helvetica, sans-serif\" size=1><b><a ");
document.write("      href=\"http://www.chinadaily.com.cn/weather/en\"> Weather</a> <font ");
document.write("      color=#ffffff>|</font></b></font></b></font></p>");
document.write("    </td>");
document.write("  </tr>");
document.write("  <tr> ");
document.write("    <td align=\"center\" height=\"1\"><img src=\"/image/dot.gif\" width=\"1\" height=\"1\"></td>");
document.write("  </tr>");
document.write("  <tr> ");
document.write("    <td align=\"center\" height=\"24\" valign=\"middle\"><img src=\"http://www.chinadaily.com.cn/image/toplistwh_4.gif\" width=\"330\" height=\"13\" usemap=\"#toplistwh_3\" border=\"0\" name=\"toplistwh_3\"> ");
document.write("      <map name=\"toplistwh_3\"> ");
document.write("        <area shape=\"rect\" coords=\"0,1,50,14\" href=\"http://www.chinadaily.com.cn/gb/worldrep/index.html\">");
document.write("        <area shape=\"rect\" coords=\"53,0,103,13\" href=\"http://www.chinadaily.com.cn/english/lt/lt_index.html\">");
document.write("        <area shape=\"rect\" coords=\"106,2,169,14\" href=\"http://www.21kc.cn/\">");
document.write("        <area shape=\"rect\" coords=\"171,1,204,12\" href=\"http://mms.chinadaily.com.cn/\">");
document.write("        <area shape=\"rect\" coords=\"205,-1,240,15\" href=\"http://sms.chinadaily.com.cn/\">");
document.write("        <area shape=\"rect\" coords=\"242,0,267,11\" href=\"http://www.newsphoto.com.cn/\">");
document.write("        <area shape=\"rect\" coords=\"271,1,299,14\" href=\"http://newscartoon.chinadaily.com.cn/app/index.asp\">");
document.write("        <area shape=\"rect\" coords=\"302,2,334,13\" href=\"http://www.chinadaily.com.cn/weather/gb/\">");
document.write("      </map>");
document.write("    </td>");
document.write("  </tr>");
document.write("  <tr> ");
document.write("    <td align=\"center\" bgcolor=\"#FFFFFF\" height=\"2\"><font face=\"Verdana, Arial, Helvetica, sans-serif\" size=\"1\"><img src=\"http://www.chinadaily.com.cn/image/Dot.gif\" width=\"1\" height=\"1\"></font></td>");
document.write("  </tr>");
document.write("  <tr> ");
document.write("    <td align=\"center\" class=\"v7\" height=\"20\"><font face=\"Verdana, Arial, Helvetica, sans-serif\" size=\"1\"><font color=\"#FFFFFF\">|<a href=\"http://www.chinadaily.com.cn/english/static/aboutchinadaily.html\" target=\"_blank\"> ");
document.write("      About China Daily</a> <font color=\"#FFFFFF\">| </font></font></font><a href=\"http://www.chinadaily.com.cn/english/static/aboutus.html\" target=\"_blank\"><font color=\"#000000\"> ");
document.write("      About China Daily.com.cn</font></a> <font color=\"#FFFFFF\">| </font><a href=\"http://www.chinadaily.com.cn/english/static/contactus.html\" target=\"_blank\"><font color=\"#000000\">Contact ");
document.write("      Us</font></a><font color=\"#FFFFFF\"> |</font> <a href=\"http://www.chinadaily.com.cn/english/static/sitemap.html\" target=\"_blank\">Site ");
document.write("      Map</a><font color=\"#FFFFFF\"> |</font><a href=\"http://www.chinadaily.com.cn/english/static/job.html\" target=\"_blank\"> ");
document.write("      <font color=\"#FF0000\"><b>Jobs</b></font></a> <font color=\"#FFFFFF\">| </font></td>");
document.write("  </tr>");
document.write("  <tr> ");
document.write("    <td align=\"center\" class=\"v7\" height=\"1\" bgcolor=\"#FFFFFF\"><img src=\"http://www.chinadaily.com.cn/image/dot.gif\" width=\"1\" height=\"1\"></td>");
document.write("  </tr>");
document.write("  <tr> ");
document.write("    <td align=\"center\" class=\"v7\" height=\"38\"><font color=\"#996600\">&nbsp;Copyright ");
document.write("      2005 Chinadaily.com.cn All rights reserved. Registered Number: <a href=\"http://www.chinadaily.com.cn/ad/licence/licence.html\"><font color=\"#996600\">20100000002731</font></a> ");
document.write("      <a href=\"http://www.hd315.gov.cn/beian/view.asp?bianhao=010202001052200008\"><img src=\"http://www.chinadaily.com.cn/image/biaoshi1.gif\" align=\"absmiddle\" border=\"0\"></a></font></td>");
document.write("  </tr>");
document.write("</table>");




document.write("<map name=\"toplistwh_3\">");
  document.write("<area shape=\"rect\" coords=\"0,2,49,15\" href=\"http://www.chinadaily.com.cn/gb/worldrep/index.html\">");
  document.write("<area shape=\"rect\" coords=\"50,1,104,14\" href=\"http://language.chinadaily.com.cn/\">");
  document.write("<area shape=\"rect\" coords=\"104,0,156,16\" href=\"http://www.chinaculture.org/gb/cn_index/node_843.htm\">");
  document.write("<area shape=\"rect\" coords=\"155,1,222,13\" href=\"http://www.21kc.cn/\">");
  document.write("<area shape=\"rect\" coords=\"221,1,258,16\" href=\"http://mms.chinadaily.com.cn\">");
  document.write("<area shape=\"rect\" coords=\"258,1,293,15\" href=\"http://sms.chinadaily.com.cn/\">");
  document.write("<area shape=\"rect\" coords=\"292,3,320,14\" href=\"http://www.newsphoto.com.cn/\">");
  document.write("<area shape=\"rect\" coords=\"321,1,350,13\" href=\"http://www.newscartoon.com.cn/\">");
  document.write("<area shape=\"rect\" coords=\"349,2,380,13\" href=\"http://www.chinadaily.com.cn/weather/gb\">");
document.write("</map>");

