Menu.CLASS_BGCOLOR = '#EFF3FF';
Menu.TOP_COORD = top_coord + 1;
Menu.SM_TOP_COORD = Menu.TOP_COORD + 22;
Menu.CSM_TOP_COORD = Menu.TOP_COORD + 22;
Menu.CL_BGCOLOR = '#FC0208';
Menu.SM_LEFT_COORD = Menu.LEFT_COORD;
Menu.SM_HEADER_TOP_COORD = (228 + Menu.TOP_COORD - 302 - 15);
Menu.MI_BGCOLOR = ['#001B6A','#000033','#336699','#3399CC'];
Menu.MI_ROVR_BGCOLOR = '#5F87FF';
Menu.SM_BGCOLOR = '#4F4F68';
Menu.SM_HEADER = '#003366';
Menu.SI_EVEN_BGCOLOR = '#F9F8FA';
Menu.SI_ODD_BGCOLOR = '#E5E5E5';
Menu.CSI_EVEN_BGCOLOR = '#FFFAED';
Menu.CSI_ODD_BGCOLOR = '#F9E7DB';
Menu.SI_ROVR_BGCOLOR = '#C1D5FF';
var hNAVBAR = new Menu();
hNAVBAR.m_i[0] = new MenuI('a', 'Home', 'asub','/', 51, 10, 'mi');
hNAVBAR.m_i[0].s_m.s_i = [
new SubI('sub0link0', '<b>Home Page</b>', 'http://www.cleveland.com'),
new SubI('sub0link1', 'Media Affiliates', '/affiliates/'),
new SubI('sub0link2', 'About Us', '/aboutus'),
new SubI('sub0link3', 'The Plain Dealer ', '/plaindealer'),
new SubI('sub0link4', 'Advertise With Us', '/mediakit'),
new SubI('sub0link5', 'Privacy Policy', '/privacypolicy/'),
new SubI('sub0link6', 'Awards', '/mediakit/content.ssf?/mediakit/awards.html'),
new SubI('sub0link7', 'Site Index', '/sitemap'),
new SubI('sub0link8', 'cleveland.com\'s 10th Anniversary!', '/ten'),
new SubI('sub0link9', 'User Agreement', '/useragreement'),
new SubI('sub0link10', 'Contact Us', '/contactus'),
new SubI('sub0link11', '<b>Visit Cleveland</b>', '/visit'),
new SubI('sub0link12', 'Free Newsletters', 'http://update.cleveland.com/adv_cleveland/newsletters/cleve/subscribe.htm'),
new SubI('sub0link13', 'What\'s New', '/whatsnew'),
new SubI('sub0link14', 'Help/Feedback', '/contactus/'),
new SubI('sub0link15', 'Yellow Pages', 'http://cleveland.switchboard.com/bin/cgidir.dll?MEM=225'),
new SubI('sub0link16', 'Job Opportunities', 'http://jobs.cleveland.com/js.php?view=2&qcompid=44197b3843e20&qlookidu=&qComp=Cleveland.com')
]
hNAVBAR.m_i[1] = new MenuI('b', 'News', 'bsub','/news', 49, 61, 'mi');
hNAVBAR.m_i[1].s_m.s_i = [
new SubI('sub1link0', '<b>News Home</b>', '/news'),
new SubI('sub1link1', '<b>Plain Dealer News</b>', '/plaindealer'),
new SubI('sub1link2', 'cleveland.com\'s 10th Anniversary!', '/ten'),
new SubI('sub1link3', 'Archived PD News', '/news/plaindealer/index.ssf?/plaindealer/index/news_archive.html'),
new SubI('sub1link4', 'Crime News', '/crime'),
new SubI('sub1link5', 'Columns/Editorials', '/columns'),
new SubI('sub1link6', 'NewsFlash', '/newsflash'),
new SubI('sub1link7', 'Corrections', '/corrections/plaindealer/index.ssf'),
new SubI('sub1link8', 'News Photos', '/news/photos/'),
new SubI('sub1link9', 'Daily Life', '/dailylife'),
new SubI('sub1link10', 'Paid Death Notices', 'http://www.legacy.com/Cleveland'),
new SubI('sub1link11', 'Editorial Cartoons', '/darcy'),
new SubI('sub1link12', 'Politics - National', '/politics'),
new SubI('sub1link13', 'Front Page', '/frontpage'),
new SubI('sub1link14', 'Strange News', '/strange'),
new SubI('sub1link15', 'Medical & Science', '/medical'),
new SubI('sub1link16', 'Traffic', '/traffic'),
new SubI('sub1link17', 'Obituaries', '/obituary/plaindealer'),
new SubI('sub1link18', 'Weather', '/weather'),
new SubI('sub1link19', 'OPEN: Ohio Politics', '/open'),
new SubI('sub1link20', 'Wireless', '/wireless'),
new SubI('sub1link21', 'PD Graphics', '/pdgraphics'),
new SubI('sub1link22', 'Young Professionals', '/youngprofessionals'),
new SubI('sub1link23', 'PD Photos', '/plaindealer/photos/'),
new SubI('sub1link24', '<b>Weblogs</b>', '/weblogs'),
new SubI('sub1link25', 'Reader Network', '/readernetwork'),
new SubI('sub1link26', 'Breaking News Blog', '/newslogs/plaindealer'),
new SubI('sub1link27', '<b>Special Reports</b>', '/indepth'),
new SubI('sub1link28', 'Medical Blog', '/weblogs/medical'),
new SubI('sub1link29', 'AIDS', '/aids'),
new SubI('sub1link30', 'Ted Diadiun: Reader Rep', '/weblogs/readers'),
new SubI('sub1link31', 'Brownfields', '/deal'),
new SubI('sub1link32', '<b>Media Alliances</b>', '/affiliates'),
new SubI('sub1link33', 'C Diff', '/cdiff'),
new SubI('sub1link34', 'The Plain Dealer ', '/plaindealer'),
new SubI('sub1link35', 'Cleveland Police', '/clevelandpolice'),
new SubI('sub1link36', 'Sun News', '/sun'),
new SubI('sub1link37', 'Concealed Weapons', '/concealed'),
new SubI('sub1link38', 'WKYC-TV 3', '/wkyc'),
new SubI('sub1link39', 'Death Row Doubts', '/doubts'),
new SubI('sub1link40', '<b>Multimedia</b> ', '/multimedia'),
new SubI('sub1link41', 'Economic Development', '/economy'),
new SubI('sub1link42', '  ', '/p'),
new SubI('sub1link43', 'Floods', '/flood'),
new SubI('sub1link44', ' ', '/p'),
new SubI('sub1link45', 'Gerald Levert', '/levert'),
new SubI('sub1link46', ' ', '/p '),
new SubI('sub1link47', 'Holiday Spirit', 'http://www.cleveland.com/holidays/spirit/plaindealer/'),
new SubI('sub1link48', ' ', '/p'),
new SubI('sub1link49', 'Lorain Cops', '/loraincops'),
new SubI('sub1link50', ' ', '/p'),
new SubI('sub1link51', 'Mismanaged Millions', '/millions'),
new SubI('sub1link52', ' ', '/p '),
new SubI('sub1link53', 'Plagued By Fear', '/plague'),
new SubI('sub1link54', ' ', '/p '),
new SubI('sub1link55', 'Public Records', '/publicrecords'),
new SubI('sub1link56', ' ', '/p '),
new SubI('sub1link57', 'Quiet Crisis', '/quietcrisis'),
new SubI('sub1link58', ' ', '/p '),
new SubI('sub1link59', 'Reader Network', '/readernetwork'),
new SubI('sub1link60', ' ', '/p '),
new SubI('sub1link61', 'Regionalism', '/region'),
new SubI('sub1link62', ' ', '/p '),
new SubI('sub1link63', 'Right To Know', '/righttoknow'),
new SubI('sub1link64', ' ', '/p'),
new SubI('sub1link65', 'Tay-Sachs', '/taysachs'),
new SubI('sub1link66', ' ', '/p '),
new SubI('sub1link67', 'Teen Trouble', '/teentrouble'),
new SubI('sub1link68', ' ', '/p'),
new SubI('sub1link69', 'Welfare', '/welfare')
]
hNAVBAR.m_i[2] = new MenuI('c', 'Local', 'csub','/community', 49, 111, 'mi');
hNAVBAR.m_i[2].s_m.s_i = [
new SubI('sub2link0', '<b>Community</b>', '/community'),
new SubI('sub2link1', '<b>Education</b>', '/education'),
new SubI('sub2link2', 'Sun News', '/sun'),
new SubI('sub2link3', 'School Crime', '/education'),
new SubI('sub2link4', 'Calendar', '/events'),
new SubI('sub2link5', 'School Closings', '/schoolclosings'),
new SubI('sub2link6', 'Cleve City Council', '/profiles'),
new SubI('sub2link7', '<b>Other Features</b>', '/community'),
new SubI('sub2link8', 'City Club', '/cityclub'),
new SubI('sub2link9', 'Daily Life', '/dailylife'),
new SubI('sub2link10', 'Crime', '/crime'),
new SubI('sub2link11', 'Mosaic', '/mosaic'),
new SubI('sub2link12', 'Gas Prices', '/gasprices'),
new SubI('sub2link13', 'Multimedia', '/multimedia'),
new SubI('sub2link14', 'OPEN: Ohio Politics', '/open'),
new SubI('sub2link15', 'Maps', '/maps'),
new SubI('sub2link16', 'PD\'s Livelines', '/livelines'),
new SubI('sub2link17', 'Resources', '/community/index.ssf?/community/more/resources.html'),
new SubI('sub2link18', 'Property Taxes', '/community/wide/index.ssf?/community/wide/propertytax.html'),
new SubI('sub2link19', 'Volunteer', '/volunteer'),
new SubI('sub2link20', 'Yellow Pages ', 'http://cleveland.switchboard.com/bin/cgidir.dll?MEM=225'),
new SubI('sub2link21', 'Voices and Choices', '/voices'),
new SubI('sub2link22', 'Weather', '/weather'),
new SubI('sub2link23', '<b>Media Alliances</b>', '/affiliates'),
new SubI('sub2link24', 'Weblogs', '/weblogs'),
new SubI('sub2link25', 'The Plain Dealer', '/plaindealer'),
new SubI('sub2link26', 'White Pages', 'http://cleveland.switchboard.com/bin/cgiqa.dll?MEM=225'),
new SubI('sub2link27', 'WKYC TV-3', '/wkyc')
]
hNAVBAR.m_i[3] = new MenuI('d', 'Sports', 'dsub','/sports', 58, 161, 'mi');
hNAVBAR.m_i[3].s_m.s_i = [
new SubI('sub3link0', '<b>Sports Home</b>', '/sports'),
new SubI('sub3link1', 'Breaking Sports News', '/weblogs/pdsports'),
new SubI('sub3link2', 'SportsFlash', '/sportsflash/index.ssf'),
new SubI('sub3link3', '<b>HS Sports</b>', '/hssports'),
new SubI('sub3link4', 'Indians', '/tribe'),
new SubI('sub3link5', 'HS Big Game', '/biggame'),
new SubI('sub3link6', 'MLB', '/mlb'),
new SubI('sub3link7', 'HS Football', '/hssports/football'),
new SubI('sub3link8', 'Captains', '/captains'),
new SubI('sub3link9', 'HS Forums', '/forums/index.ssf?/forums/hssports.ssf'),
new SubI('sub3link10', 'Aeros', '/aeros'),
new SubI('sub3link11', 'HS Basketball ', '/hssports/basketball'),
new SubI('sub3link12', 'Browns', '/browns'),
new SubI('sub3link13', 'HS Volleyball', '/hssports/volleyball'),
new SubI('sub3link14', 'NFL', '/nfl'),
new SubI('sub3link15', 'The Locker Room', '/tlr'),
new SubI('sub3link16', 'Cavaliers', '/cavs'),
new SubI('sub3link17', 'TLR Insider Blog', '/tlr/weblog'),
new SubI('sub3link18', 'NBA', '/nba'),
new SubI('sub3link19', '<b>Local Colleges</b>', '/sports/college'),
new SubI('sub3link20', 'NHL ', '/nhl'),
new SubI('sub3link21', 'Ohio State', '/osu'),
new SubI('sub3link22', '<b>Media/Interact</b>', '/affiliates'),
new SubI('sub3link23', 'Cleveland State', '/sports/csu'),
new SubI('sub3link24', 'The Plain Dealer', '/sports/plaindealer/index/'),
new SubI('sub3link25', 'College Football', '/ncaafootball'),
new SubI('sub3link26', 'PD-TV', '/pdtv'),
new SubI('sub3link27', 'College Basketball', '/ncaabasketball'),
new SubI('sub3link28', 'PD Columnists', '/sports/columns'),
new SubI('sub3link29', 'Recruiting', '/recruiting'),
new SubI('sub3link30', 'PD Fanlines', '/sports/fanlines'),
new SubI('sub3link31', '<b>Other Features</b>', '/sports'),
new SubI('sub3link32', 'PD Rec Room', '/recroom'),
new SubI('sub3link33', 'Auto Racing', '/autoracing'),
new SubI('sub3link34', 'Sun Newspapers', '/hssports/sun/'),
new SubI('sub3link35', 'Golf', '/golf'),
new SubI('sub3link36', 'WKYC-TV 3', '/wkyc'),
new SubI('sub3link37', 'Horse Racing', '/horseracing'),
new SubI('sub3link38', 'Multimedia', '/multimedia'),
new SubI('sub3link39', 'Outdoors', '/outdoors'),
new SubI('sub3link40', 'Desktop Updates', '/desktop'),
new SubI('sub3link41', 'Pro Hockey - Cleveland', '/prohockey'),
new SubI('sub3link42', 'Photo Galleries', '/sports/photos'),
new SubI('sub3link43', 'Recreation', '/recreation'),
new SubI('sub3link44', 'Sports Forums', '/forums/index.ssf#sports'),
new SubI('sub3link45', 'Women\'s Final Four ', '/womensfinalfour'),
new SubI('sub3link46', 'Weblogs', '/weblogs')
]
hNAVBAR.m_i[4] = new MenuI('e', 'Business', 'esub','/business', 72, 221, 'mi');
hNAVBAR.m_i[4].s_m.s_i = [
new SubI('sub4link0', '<b>Business Home</b>', '/business'),
new SubI('sub4link1', '<b>Plain Dealer Business</b>', '/business/plaindealer/index.ssf'),
new SubI('sub4link2', 'American Business Daily', '/business/ambizdaily/'),
new SubI('sub4link3', 'Breaking Business News', '/weblogs/business'),
new SubI('sub4link4', 'Appointments', '/appointments/'),
new SubI('sub4link5', 'Auto News/Reviews', '/autonews'),
new SubI('sub4link6', 'Bankrate', '/bankrate'),
new SubI('sub4link7', 'BusinessMonday', '/businessmonday/'),
new SubI('sub4link8', 'Entrepreneurs', '/entrepreneur'),
new SubI('sub4link9', 'Consumer News', '/business/plaindealer/sheryl_harris/'),
new SubI('sub4link10', 'Personal Finance', '/personalfinance'),
new SubI('sub4link11', '<b>PD Business Reports</b>', '/indepth'),
new SubI('sub4link12', 'Job Search ', '/jobs/'),
new SubI('sub4link13', 'Crude Awakening ', '/energy'),
new SubI('sub4link14', 'Technology', '/tech/'),
new SubI('sub4link15', 'Ford', '/ford'),
new SubI('sub4link16', 'Tax Center', '/tax'),
new SubI('sub4link17', 'Health Care Guide', '/healthcare'),
new SubI('sub4link18', 'Wireless', '/wireless'),
new SubI('sub4link19', 'On The Record', '/ontherecord'),
new SubI('sub4link20', '<b>Young Professionals</b>', '/youngprofessionals/'),
new SubI('sub4link21', 'PD Tax Guide ', '/taxguide'),
new SubI('sub4link22', 'cleveland.com\'s 10th Anniversary!', '/ten'),
new SubI('sub4link23', 'Retire At Your Own Risk', '/retirement')
]
hNAVBAR.m_i[5] = new MenuI('f', 'Forums', 'fsub','/forums', 64, 293, 'mi');
hNAVBAR.m_i[5].s_m.s_i = [
new SubI('sub5link0', '<b>Forums Home</b>', '/forums'),
new SubI('sub5link1', 'ChatRadio', '/chatradio'),
new SubI('sub5link2', 'Forums Help', '/forums/index.ssf?help.html'),
new SubI('sub5link3', 'Cams', '/multimedia'),
new SubI('sub5link4', 'Forums Rules', '/useragreement'),
new SubI('sub5link5', 'Online Radio', '/multimedia'),
new SubI('sub5link6', 'Forums Search ', '/forums/search/index.ssf'),
new SubI('sub5link7', 'Weblogs', '/weblogs'),
new SubI('sub5link8', 'Register Now!', 'http://register.cleveland.com/regdb/servlet/Reg?affiliate=cleveland.com&source=forums&_returnurl=http://www.cleveland.com/forums/'),
new SubI('sub5link9', 'Podcasts', '/podcasting')
]
hNAVBAR.m_i[6] = new MenuI('g', 'Living & Travel', 'gsub','/living', 108, 240, 'mi');
hNAVBAR.m_i[6].s_m.s_i = [
new SubI('sub6link0', '<b>Living Home</b>', '/living'),
new SubI('sub6link1', '<b>Travel</b>', '/travel'),
new SubI('sub6link2', 'PD Life News ', '/living/plaindealer/index.ssf'),
new SubI('sub6link3', 'Maps', '/maps'),
new SubI('sub6link4', 'PD Sunday Mag', '/sundaymag'),
new SubI('sub6link5', 'New to Cleveland', '/movers'),
new SubI('sub6link6', 'PDQ', '/pdq'),
new SubI('sub6link7', 'Visit Cleveland', '/visit'),
new SubI('sub6link8', '<b>Other Sections</b>', '/'),
new SubI('sub6link9', '<b>More Cool Stuff</b>', '/'),
new SubI('sub6link10', 'Education', '/education'),
new SubI('sub6link11', 'Ask the Psychic', '/psychic'),
new SubI('sub6link12', 'Family & Pets', '/family'),
new SubI('sub6link13', 'Caught on Camera', '/caught'),
new SubI('sub6link14', 'Garden Center', '/insideout'),
new SubI('sub6link15', 'Holiday Guide', '/holidays'),
new SubI('sub6link16', 'Health & Fitness', '/healthfit'),
new SubI('sub6link17', 'Holiday Spirit ', '/holidays/spirit/plaindealer/'),
new SubI('sub6link18', 'Homes', '/insideout'),
new SubI('sub6link19', 'Podcasts', '/podcasting'),
new SubI('sub6link20', 'Inside & Out', '/insideout'),
new SubI('sub6link21', 'Sophisticated Homes', '/sophisticated'),
new SubI('sub6link22', 'Medical & Science', '/medical'),
new SubI('sub6link23', 'Weblogs', '/weblogs'),
new SubI('sub6link24', 'Religion', '/religion'),
new SubI('sub6link25', ' ', '/p '),
new SubI('sub6link26', 'Style', '/style'),
new SubI('sub6link27', ' ', '/p '),
new SubI('sub6link28', 'Taste', '/taste'),
new SubI('sub6link29', ' ', '/p'),
new SubI('sub6link30', 'Weddings', '/weddings')
]
hNAVBAR.m_i[7] = new MenuI('h', 'Entertainment', 'hsub','/entertainment', 109, 352, 'mi');
hNAVBAR.m_i[7].s_m.s_i = [
new SubI('sub7link0', '<b>Entertainment</b>', '/entertainment'),
new SubI('sub7link1', 'Breaking Arts News', '/weblogs/entertainment'),
new SubI('sub7link2', 'Arts', '/arts'),
new SubI('sub7link3', '<b>New Sections!</b>', '/'),
new SubI('sub7link4', 'Books', '/books'),
new SubI('sub7link5', 'Arts & Economy', '/artseconomy'),
new SubI('sub7link6', 'Dining & Bars', '/dining'),
new SubI('sub7link7', 'Caught on Camera', '/caught'),
new SubI('sub7link8', 'Events', '/events'),
new SubI('sub7link9', 'Fall Guide', '/fallguide'),
new SubI('sub7link10', 'Friday! Magazine', '/friday'),
new SubI('sub7link11', 'Gerald Levert', '/levert'),
new SubI('sub7link12', 'Fun & Games', '/fun'),
new SubI('sub7link13', 'Holiday Guide', '/holidays'),
new SubI('sub7link14', 'Going Out Guides', '/goingout'),
new SubI('sub7link15', 'Local Bands', '/localbands'),
new SubI('sub7link16', 'Movies', '/movies'),
new SubI('sub7link17', 'Podcasts', '/podcasting'),
new SubI('sub7link18', 'Music', '/music'),
new SubI('sub7link19', 'Theater', '/theater'),
new SubI('sub7link20', 'Television', '/tv'),
new SubI('sub7link21', '<b>Multimedia</b> ', '/multimedia'),
new SubI('sub7link22', '<b>Other Cool Stuff</b>', '/'),
new SubI('sub7link23', 'Cedar Point Cam', '/cedarpointcam'),
new SubI('sub7link24', 'Contests!', '/contests'),
new SubI('sub7link25', 'Concert Cam', '/concertcam'),
new SubI('sub7link26', 'IPIX Cleveland', '/ipix'),
new SubI('sub7link27', 'Lakefront East', '/lakefront/east/'),
new SubI('sub7link28', 'Local Heroes', '/homegrown'),
new SubI('sub7link29', 'Lakefront West', '/lakefront/west/'),
new SubI('sub7link30', 'Maps', '/maps'),
new SubI('sub7link31', 'Zoo Cam', '/zoocam/index.ssf/video'),
new SubI('sub7link32', 'Photo Galleries', '/entertainment/photos'),
new SubI('sub7link33', 'PD TV', '/pdtv'),
new SubI('sub7link34', 'Visit Cleveland!', '/visit'),
new SubI('sub7link35', 'PD\'s Loudmouth Soup', '/pdtv'),
new SubI('sub7link36', 'Weblogs', '/weblogs'),
new SubI('sub7link37', 'PD\'s Laugh Track', '/pdtv'),
new SubI('sub7link38', 'What\'s New?', '/whatsnew'),
new SubI('sub7link39', 'WKYC', '/wkyc'),
new SubI('sub7link40', 'Slideshows', '/dailylife'),
new SubI('sub7link41', 'ChatRadio', '/chatradio')
]
hNAVBAR.m_i[8] = new MenuI('i', '<img src="/dhtml/hnavbar_class/images/classtitle.gif" border=0>', 'isub','/classifieds', 193, 244, 'miclass');
hNAVBAR.m_i[8].s_m.s_i = [
new SubI('sub8link0', 'Use Our Quick & Simple Job Search', 'http://www.cleveland.com/jobs/', 'Jobs:', 'Find The Right Job For You!', '/dhtml/hnavbar_class/images/icons/spacer.gif'),
new SubI('sub8link1', 'Get A Quick Quote OR Do More Research', 'http://www.cleveland.com/autos/', 'Autos:', 'Is That Hot New Car Perfect For You?', '/dhtml/hnavbar_class/images/icons/spacer.gif'),
new SubI('sub8link2', 'Search Our Listings ', 'http://www.cleveland.com/realestate', 'Real Estate:', 'Looking For A Bigger Home?', '/dhtml/hnavbar_class/images/icons/spacer.gif'),
new SubI('sub8link3', 'Find A Pet, A Lawn Mower Or Painter!', 'http://www.cleveland.com/classifieds/', '', 'Browse All Our Classifieds Listings', '/dhtml/hnavbar_class/images/icons/spacer.gif'),
new SubI('sub8link4', 'Place A Classifieds Ad Now!', 'http://www.cleveland.com/placead/index.ssf', '', 'Advertise Jobs, Autos, Homes & More', '/dhtml/hnavbar_class/images/icons/spacer.gif')
]
