<!--myTop=197if(splash==true){myTop=197}function LayerSpecs(Left,Top,Width) { if(No3) {        this.top = Top;        this.left = Left;        this.info  = "";        T=0;        for(i=3; i<arguments.length; i++) {                if(document.all || document.getElementById) { this.info += "<TR><TD WIDTH="+Width+">"+arguments[i]+"</TD></TR>"; }                else { this.info += "<LAYER WIDTH="+Width+" POSITION=RELATIVE TOP="+T+">"+arguments[i]+"</LAYER>"; }				if(i==3){				T+=2				}				else{                T+=16;				}        }} }Layer = new Array();///////////////////////////////////////////////*      Specific Layers per rollover.*/Layer[1] =      new LayerSpecs(0,0,0,"");Layer[2] =      new LayerSpecs(95,myTop,164,                        '<IMG src="images/dd_blank_01.gif" width="172" height="1">',                        '<A HREF="searchmls.asp" onMouseOver="Show(2);setImage(\'dd01\',dd01on)" onMouseOut="setImage(\'dd01\',dd01off)" target="_parent"><IMG name="dd01" src="images/searchmlsoff.gif" width="172" height="16" border="0"></A>',                        '<A HREF="featuredhomes.asp" onMouseOver="Show(2);setImage(\'dd02\',dd02on)" onMouseOut="setImage(\'dd02\',dd02off)" target="_parent"><IMG name="dd02" src="images/featuredhomesoff.gif" width="172" height="16" border="0"></A>',                        '<A HREF="foreclosures.asp" onMouseOver="Show(2);setImage(\'dd03\',dd03on)" onMouseOut="setImage(\'dd03\',dd03off)" target="_parent"><IMG name="dd03" src="images/foreclosuresoff.gif" width="172" height="16" border="0"></A>',                        '<A HREF="10step.asp" onMouseOver="Show(2);setImage(\'dd04\',dd04on)" onMouseOut="setImage(\'dd04\',dd04off)" target="_parent"><IMG name="dd04" src="images/10stepoff.gif" width="172" height="16" border="0"></A>',                        '<A HREF="propertylookout.asp" onMouseOver="Show(2);setImage(\'dd05\',dd05on)" onMouseOut="setImage(\'dd05\',dd05off)" target="_parent"><IMG name="dd05" src="images/propertylookoutoff.gif" width="172" height="16" border="0"></A>',                        '<A HREF="requestshowing.asp" onMouseOver="Show(2);setImage(\'dd06\',dd06on)" onMouseOut="setImage(\'dd06\',dd06off)" target="_parent"><IMG name="dd06" src="images/requestashowingoff.gif" width="172" height="16" border="0"></A>'                        
);

Layer[3] =      new LayerSpecs(189,myTop,164,                        '<IMG src="images/dd_blank_01.gif" width="172" height="1">',                        '<A HREF="sellingtips.asp" onMouseOver="Show(3);setImage(\'dd07\',dd07on)" onMouseOut="setImage(\'dd07\',dd07off)" target="_parent"><IMG name="dd07" src="images/tipsandinfooff.gif" width="172" height="16" border="0"></A>',                        '<A HREF="listwithus.asp" onMouseOver="Show(3);setImage(\'dd08\',dd08on)" onMouseOut="setImage(\'dd08\',dd08off)" target="_parent"><IMG name="dd08" src="images/listwithusoff.gif" width="172" height="16" border="0"></A>',                        '<A HREF="marketanalysis.asp" onMouseOver="Show(3);setImage(\'dd09\',dd09on)" onMouseOut="setImage(\'dd09\',dd09off)" target="_parent"><IMG name="dd09" src="images/freemarketoff.gif" width="172" height="16" border="0"></A>',                        '<A HREF="buyersfrom.asp" onMouseOver="Show(3);setImage(\'dd10\',dd10on)" onMouseOut="setImage(\'dd10\',dd10off)" target="_parent"><IMG name="dd10" src="images/wherebuyersoff.gif" width="172" height="16" border="0"></A>'                                               
);
Layer[4] =      new LayerSpecs(0,0,0,"");Layer[5] =      new LayerSpecs(380,myTop,164,                        '<IMG src="images/dd_blank_01.gif" width="172" height="1">',                        '<A HREF="mortgageservices.asp" onMouseOver="Show(5);setImage(\'dd12\',dd12on)" onMouseOut="setImage(\'dd12\',dd12off)" target="_parent"><IMG name="dd12" src="images/mortgageserviceoff.gif" width="172" height="16" border="0"></A>',                        '<A HREF="estateservices.asp" onMouseOver="Show(5);setImage(\'dd13\',dd13on)" onMouseOut="setImage(\'dd13\',dd13off)" target="_parent"><IMG name="dd13" src="images/estateservicesoff.gif" width="172" height="16" border="0"></A>',
                        '<A HREF="relocationservices.asp" onMouseOver="Show(5);setImage(\'dd14\',dd14on)" onMouseOut="setImage(\'dd14\',dd14off)" target="_parent"><IMG name="dd14" src="images/relocationservicesoff.gif" width="172" height="16" border="0"></A>',
                        '<A HREF="renovationservices.asp" onMouseOver="Show(5);setImage(\'dd28\',dd28on)" onMouseOut="setImage(\'dd28\',dd28off)" target="_parent"><IMG name="dd28" src="images/renovationservicesoff.gif" width="172" height="16" border="0"></A>',                        '<A HREF="builderservices.asp" onMouseOver="Show(5);setImage(\'dd15\',dd15on)" onMouseOut="setImage(\'dd15\',dd15off)" target="_parent"><IMG name="dd15" src="images/builderservicesoff.gif" width="172" height="16" border="0"></A>',                        '<A HREF="commercialservices.asp" onMouseOver="Show(5);setImage(\'dd16\',dd16on)" onMouseOut="setImage(\'dd16\',dd16off)" target="_parent"><IMG name="dd16" src="images/commercialservicesoff.gif" width="172" height="16" border="0"></A>',                        '<A HREF="monthlyspecial.asp" onMouseOver="Show(5);setImage(\'dd17\',dd17on)" onMouseOut="setImage(\'dd17\',dd17off)" target="_parent"><IMG name="dd17" src="images/internetspecialoff.gif" width="172" height="16" border="0"></A>'                                               
);

Layer[6] =      new LayerSpecs(475,myTop,164,
				'<IMG src="images/dd_blank_01.gif" width="172" height="1">',
						'<A HREF="ourcompany.asp" onMouseOver="Show(6);setImage(\'dd23\',dd23on)" onMouseOut="setImage(\'dd23\',dd23off)" target="_parent"><IMG name="dd23" src="images/ourcompanyoff.gif" width="172" height="16" border="0"></A>',                        '<A HREF="officelocation.asp" onMouseOver="Show(6);setImage(\'dd24\',dd24on)" onMouseOut="setImage(\'dd24\',dd24off)" target="_parent"><IMG name="dd24" src="images/officelocationoff.gif" width="172" height="16" border="0"></A>',                        '<A HREF="recareer.asp" onMouseOver="Show(6);setImage(\'dd25\',dd25on)" onMouseOut="setImage(\'dd25\',dd25off)" target="_parent"><IMG name="dd25" src="images/recareeroff.gif" width="172" height="16" border="0"></A>',                        '<A HREF="contactus.asp" onMouseOver="Show(6);setImage(\'dd27\',dd27on)" onMouseOut="setImage(\'dd27\',dd27off)" target="_parent"><IMG name="dd27" src="images/contactusoff.gif" width="172" height="16" border="0"></A>'                        );
Layer[7] =      new LayerSpecs(570,myTop,164,                        '<IMG src="images/dd_blank_01.gif" width="172" height="1">',                        '<A HREF="communityprofile.asp" onMouseOver="Show(7);setImage(\'dd18\',dd18on)" onMouseOut="setImage(\'dd18\',dd18off)" target="_parent"><IMG name="dd18" src="images/macombinfooff.gif" width="172" height="16" border="0"></A>',
                        '<A HREF="schoolinformation.asp" onMouseOver="Show(7);setImage(\'dd26\',dd26on)" onMouseOut="setImage(\'dd26\',dd26off)" target="_parent"><IMG name="dd26" src="images/schoolinfooff.gif" width="172" height="16" border="0"></A>',                        '<A HREF="glossary.asp" onMouseOver="Show(7);setImage(\'dd20\',dd20on)" onMouseOut="setImage(\'dd20\',dd20off)" target="_parent"><IMG name="dd20" src="images/reglossaryoff.gif" width="172" height="16" border="0"></A>',
                        '<A HREF="mortgagecalculator.asp" onMouseOver="Show(7);setImage(\'dd21\',dd21on)" onMouseOut="setImage(\'dd21\',dd21off)" target="_parent"><IMG name="dd21" src="images/calculatoroff.gif" width="172" height="16" border="0"></A>',                        '<A HREF="contactus.asp" onMouseOver="Show(7);setImage(\'dd22\',dd22on)" onMouseOut="setImage(\'dd22\',dd22off)" target="_parent"><IMG name="dd22" src="images/askaquestionoff.gif" width="172" height="16" border="0"></A>'                                                                       
);
////////////////////////////////////////////////////////////////j = (Layer[0]) ? 0:1;for(i=j; i<Layer.length; i++) {        if((document.all && No3) || document.getElementById) { document.write("<DIV onMouseOver='clearTimeout(timer)' onMouseOut='Hide("+i+")' ID='L"+i+"' STYLE='position:absolute; visibility:hidden; top:"+Layer[i].top+"; left:"+Layer[i].left+";'><TABLE border=0 cellspacing=0 cellpadding=0>"+Layer[i].info+"</TABLE></DIV>"); }        else if(document.layers && No3) { document.write("<LAYER onMouseOver='clearTimeout(timer)' onMouseOut='Hide("+i+")' ID='L"+i+"' POSITION=ABSOLUTE VISIBILITY=HIDDEN TOP="+Layer[i].top+" LEFT="+Layer[i].left+">"+Layer[i].info+"</LAYER>"); }}// -->