restrict_access = true
sequence = "9x445"
dqm__menu_title = "OpenCube Template"
dqm__icon_image = vqm__database+"services/web%25252525252525252525252525252525252525252525252525252525252525252525252525252525252525252525252525252525252525252525252520effects%25252525252525252525252525252525252525252525252525252525252525252525252525252525252525252525252525252525252525252525252520java"
dqm__instance_id = "Visual GoBar"
dqm__instance_code = 1234
dqm__hide_from_bar = false
dqm__hide_from_document = false
dqm__default_document = "http://"
dqm__default_title = "[Your Menu Title Here]"
dqm__icon_image0 = vqm__database+"services/yellowtriangle.gif"
dqm__icon_rollover0 = vqm__database+"services/yellowtriangle.gif"
dqm__icon_image_wh0 = "9,8"
dqm__icon_image1 = vqm__database+"services/gray_bullet.gif"
dqm__icon_rollover1 = vqm__database+"services/gray_bullet_hl.gif"
dqm__icon_image_wh1 = "13,8"
dqm__second_icon_image0 = vqm__database+"services/arrow_gray.gif"
dqm__second_icon_rollover0 = vqm__database+"services/arrow_gray_hl.gif"
dqm__second_icon_image_wh0 = "13,10"
dqm__second_icon_image_xy0 = "0,0"
dqm__main_width = 143
dqm__main_height = 22
dqm__main_width4 = 86
dqm__main_horizontal = true
dqm__main_border_width = 1
dqm__main_use_dividers = true
dqm__main_item_gap = 5
dqm__align_items_bottom_and_right = false
dqm__main_bgcolor = "#f9e457"
dqm__main_hl_bgcolor = "#f9e457"
dqm__main_textcolor = "#000000"
dqm__main_hl_textcolor = "#ffffff"
dqm__main_border_color = "#000000"
dqm__main_fontfamily = "Verdana"
dqm__main_fontsize = 9
dqm__main_textdecoration = "none"
dqm__main_fontweight = "normal"
dqm__main_fontstyle = "normal"
dqm__main_hl_textdecoration = "none"
dqm__main_text_alignment = "left"
dqm__main_margin_top = 2
dqm__main_margin_bottom = 2
dqm__main_margin_left = 1
dqm__main_margin_right = 1
dqm__maindesc0 = "Home"
dqm__maindesc1 = "Faculty"
dqm__maindesc2 = "Staff"
dqm__maindesc3 = "Graduate"
dqm__maindesc4 = "Undergraduate"
dqm__sub_menu_width = 127
dqm__sub_xy = "0,0"
dqm__urltarget = "_self"
dqm__border_width = 1
dqm__divider_height = 0
dqm__border_color = "#000000"
dqm__menu_bgcolor = "#f9e457"
dqm__hl_bgcolor = "#f9e457"
dqm__mouse_off_delay = 136
dqm__nn4_mouse_off_delay = 500
dqm__textcolor = "#000000"
dqm__fontfamily = "Verdana"
dqm__fontsize = 10
dqm__fontsize_ie4 = 9
dqm__textdecoration = "none"
dqm__fontweight = "normal"
dqm__fontstyle = "normal"
dqm__hl_textcolor = "#000000"
dqm__hl_textdecoration = "underline"
dqm__text_alignment = "left"
dqm__margin_top = 2
dqm__margin_bottom = 3
dqm__margin_left = 5
dqm__margin_right = 5
dqm__sub_menu_effect = "gradientwipe"
dqm__sub_item_effect = "gradientwipe"
dqm__sub_menu_effect_duration = 0.4
dqm__sub_item_effect_duration = 0.4
dqm__effect_pixelate_maxsqare = 25
dqm__effect_iris_irisstyle = "CIRCLE"
dqm__effect_checkerboard_squaresx = 14
dqm__effect_checkerboard_squaresY = 14
dqm__effect_checkerboard_direction = "RIGHT"
dqm__sub_menu_opacity = "90"
dqm__dropshadow_color = "#afafaf"
dqm__dropshadow_offx = "3"
dqm__dropshadow_offy = "2"
dqm__ie4mac_offset_x = -10
dqm__ie4mac_offset_Y = -45
dqm__nn4_reaload_after_resize = true
dqm__nn4_resize_prompt_user = false
dqm__nn4_resize_prompt_message = "NN4 - Custom Alert Message"
dqm__use_opera_div_detect_fix = true
dqm__escape_item_height = 20
dqm__onload_code = ""
dqm__showmenu_codeX = "status = 'custom show menu function call - menu0'"
dqm__hidemenu_codeX = "status = 'custom hide menu function call - menu0'"
dqm__clickitem_codeXX = "alert('custom Function - Menu Item 0_0')"
dqm__sub_xy4 = "-88,14"
dqm__subdesc4_0 = "Undergraduate Application"
dqm__main_width0 = 41
dqm__main_height0 = 18
dqm__main_width1 = 49
dqm__main_height1 = 18
dqm__main_width2 = 38
dqm__main_height2 = 18
dqm__main_width3 = 59
dqm__main_height3 = 18
dqm__maindesc5 = "Seminar"
dqm__main_width5 = 54
dqm__main_height5 = 18
dqm__main_textcolor5 = "#ffffff"
dqm__main_bgcolor5 = "#0f0f0f"
dqm__main_bgcolor0 = "#0f0f0f"
dqm__main_bgcolor1 = "#0f0f0f"
dqm__main_bgcolor2 = "#0f0f0f"
dqm__main_textcolor0 = "#ffffff"
dqm__main_textcolor1 = "#ffffff"
dqm__main_textcolor2 = "#ffffff"
dqm__main_bgcolor3 = "#0f0f0f"
dqm__main_textcolor3 = "#ffffff"
dqm__main_bgcolor4 = "#0f0f0f"
dqm__main_textcolor4 = "#ffffff"
dqm__subdesc5_0 = "Seminar Schedule"
dqm__sub_xy5 = "-56,14"
dqm__sub_menu_width5 = 142
dqm__main_height4 = 18
dqm__url4 = vqm__database+"../undergrad.html"
dqm__maindesc6 = "Alumni "
dqm__main_bgcolor6 = "#0f0f0f"
dqm__main_textcolor6 = "#ffffff"
dqm__main_width6 = 48
dqm__main_height6 = 18
dqm__main_border_color1 = "#f9e457"
dqm__clickitem_code0 = "Please check out all of our titles"
dqm__status_text0 = "Welcome to the School of Polymers and High Performance Materials"
dqm__show_urls_statusbar = true
dqm__status_text1 = "Welcome to the School of Polymers and High Performance Material"
dqm__status_text5 = "Undergraduate Studies"
dqm__status_text2 = "Faculty"
dqm__status_text5_0 = "Seminar Schedule"
dqm__status_text6 = "Seminar"
dqm__maindesc7 = "Institutes"
dqm__main_width7 = 63
dqm__main_height7 = 18
dqm__main_textcolor7 = "#ffffff"
dqm__main_bgcolor7 = "#0f0f0f"
dqm__sub_xy6 = "-49,14"
dqm__sub_menu_width6 = 164
dqm__subdesc6_1 = "Alumni Pictures"
dqm__url6_1 = vqm__database+"../alum_picts.html"
dqm__status_text6_1 = "Alumni Pictures"
dqm__subdesc6_0 = "Alumni Message Board"
dqm__status_text6_0 = "Alumni Message Board"
dqm__icon_index5_0 = 1
dqm__url4_0 = "https://www.usm.edu/ugapp/"
dqm__icon_index4_0 = 1
dqm__sub_menu_width4 = 179
dqm__maindesc8 = "Newsletter"
dqm__main_width8 = 66
dqm__main_height8 = 18
dqm__main_textcolor8 = "#ffffff"
dqm__main_bgcolor8 = "#0f0f0f"
dqm__main_border_color7 = "#f9e457"
dqm__main_border_color6 = "#f9e457"
dqm__main_border_color5 = "#f9e457"
dqm__main_border_color4 = "#f9e457"
dqm__main_border_color3 = "#f9e457"
dqm__main_border_color2 = "#f9e457"
dqm__icon_index6_1 = 1
dqm__icon_index6_0 = 1
dqm__url5_0 = vqm__database+"../calendar.html"
dqm__micon_index8 = 0
dqm__main_hl_bgcolor0 = "#f9e457"
dqm__main_border_color0 = "#f9e457"
dqm__main_border_color8 = "#f9e457"
dqm__second_icon_image1 = vqm__database+"services/arrowr_double_black.gif"
dqm__second_icon_rollover1 = vqm__database+"services/arrowr_double_black.gif"
dqm__second_icon_image_wh1 = "10,8"
dqm__second_icon_image_xy1 = "0,0"
dqm__second_icon_image2 = vqm__database+"services/arrow_solid_red.gif"
dqm__second_icon_rollover2 = vqm__database+"services/arrow_solid_red_hl.gif"
dqm__second_icon_image_wh2 = "10,8"
dqm__second_icon_image_xy2 = "0,0"
dqm__second_icon_image3 = vqm__database+"services/arrow_double_red.gif"
dqm__second_icon_rollover3 = vqm__database+"services/arrow_double_red_hl.gif"
dqm__second_icon_image_wh3 = "9,9"
dqm__second_icon_image_xy3 = "0,0"
dqm__status_text3 = "Staff"
dqm__status_text4 = "Graduates Studies"
dqm__status_text7 = "2006 President's Invitational Polymer Science Alumni Celebration"
dqm__status_text8 = "Institutes"
dqm__micon_index1 = 0
dqm__micon_index2 = 0
dqm__micon_index3 = 0
dqm__micon_index4 = 0
dqm__micon_index5 = 0
dqm__micon_index6 = 0
dqm__micon_index7 = 0
dqm__second_icon_image4 = vqm__database+"services/yellowtriangle.gif"
dqm__second_icon_rollover4 = vqm__database+"services/yellowtriangle.gif"
dqm__second_icon_image_wh4 = "9,8"
dqm__second_icon_image_xy4 = "0,0"
dqm__second_icon_image5 = vqm__database+"services/arrow_gray.gif"
dqm__second_icon_rollover5 = vqm__database+"services/arrow_gray_hl.gif"
dqm__second_icon_image_wh5 = "13,10"
dqm__second_icon_image_xy5 = "0,0"
dqm__second_icon_image6 = vqm__database+"services/arrow_double_red.gif"
dqm__second_icon_rollover6 = vqm__database+"services/arrow_double_red_hl.gif"
dqm__second_icon_image_wh6 = "9,9"
dqm__second_icon_image_xy6 = "0,0"
dqm__url2 = vqm__database+"../staffpage1.html"
dqm__url0 = vqm__database+"../index.html"
dqm__url1 = vqm__database+"../faculty1.html"
dqm__status_text4_0 = "Undergraduate Application"
dqm__url6_0 = vqm__database+"../newsletter/message.html"
dqm__subdesc8_0 = "Message from the Director"
dqm__sub_xy8 = "-68,14"
dqm__status_text8_0 = "Message from the Director"
dqm__url8_0 = vqm__database+"../newsletter/director.html"
dqm__sub_menu_width8 = 175
dqm__icon_index8_0 = 1
dqm__subdesc8_1 = "Faculty Spotlight"
dqm__subdesc8_2 = "Faculty Highlights"
dqm__subdesc8_3 = "New Faculty"
dqm__subdesc8_4 = "Student Events"
dqm__subdesc8_5 = "Institutes"
dqm__subdesc8_6 = "Equipment"
dqm__subdesc8_7 = "Alumni Message Board"
dqm__icon_index8_1 = 1
dqm__icon_index8_2 = 1
dqm__icon_index8_3 = 1
dqm__icon_index8_4 = 1
dqm__icon_index8_5 = 1
dqm__icon_index8_6 = 1
dqm__icon_index8_7 = 1
dqm__url3 = vqm__database+"../graduatenew1.html"
dqm__url8_1 = vqm__database+"../newsletter/newsletter.html"
dqm__url8_2 = vqm__database+"../newsletter/highlights.html"
dqm__url8_3 = vqm__database+"../newsletter/new_fac.html"
dqm__url8_4 = vqm__database+"../newsletter/events.html"
dqm__url8_5 = vqm__database+"../newsletter/Institutes.html"
dqm__url8_6 = vqm__database+"../newsletter/equipment.html"
dqm__url8_7 = vqm__database+"../newsletter/message.html"
dqm__subdesc7_0 = "Material Research Science & Engineering Ctr"
dqm__sub_xy7 = "-66,14"
dqm__url7_0 = "http://www.usm.edu/mrsec/"
dqm__status_text7_0 = "MRSEC"
dqm__sub_menu_width7 = 211
dqm__icon_index7_0 = 1
dqm__subdesc7_1 = "National Science Foundation Industry/University Cooperative Research Ctr"
dqm__icon_index7_1 = 1
dqm__maindesc9 = "Instrumentation"
dqm__main_width9 = 93
dqm__main_height9 = 18
dqm__main_textcolor9 = "#ffffff"
dqm__main_bgcolor9 = "#0f0f0f"
dqm__main_border_color9 = "#f9e457"
dqm__url9 = vqm__database+"../equipment.html"
dqm__micon_index9 = 0
dqm__second_icon_image7 = vqm__database+"services/yellowtriangle.gif"
dqm__second_icon_rollover7 = "http://"
dqm__second_icon_image_wh7 = "9,8"
dqm__second_icon_image_xy7 = "0,0"
dqm__url7_1 = "http://www.usm.edu/nsfiucrc/"
dqm__main_hl_bgcolor1 = "#f9e457"
dqm__status_text7_1 = "National Science Foundation Industry/University Cooperative Research Ctr"
dqm__main_hl_textcolor1 = "#0f0f0f"
dqm__main_hl_bgcolor5 = "#f9e457"
dqm__main_hl_bgcolor4 = "#f9e457"
dqm__main_hl_bgcolor3 = "#f9e457"
dqm__main_hl_bgcolor2 = "#f9e457"
dqm__main_hl_bgcolor6 = "#f9e457"
dqm__main_hl_bgcolor7 = "#f9e457"
dqm__main_hl_bgcolor8 = "#f9e457"
dqm__main_hl_bgcolor9 = "#f9e457"
dqm__main_hl_textcolor2 = "#0f0f0f"
dqm__main_hl_textcolor3 = "#0f0f0f"
dqm__main_hl_textcolor4 = "#0f0f0f"
dqm__main_hl_textcolor5 = "#0f0f0f"
dqm__main_hl_textcolor6 = "#0f0f0f"
dqm__main_hl_textcolor7 = "#0f0f0f"
dqm__main_hl_textcolor8 = "#0f0f0f"
dqm__main_hl_textcolor9 = "#0f0f0f"
dqm__status_text9 = "2006 Newsletter"
dqm__status_text10 = "Equipment"
dqm__status_text8_1 = "Faculty Spotlight-Dr. McCormick"
dqm__status_text8_2 = "Faculty Highlights"
dqm__status_text8_3 = "New Faculty"
dqm__status_text8_4 = "Student Events"
dqm__status_text8_5 = "Institutes"
dqm__status_text8_6 = "Equipment"
dqm__status_text8_7 = "Alumni Message Board"
dqm__subdesc7_2 = "Integrative Graduate Education and Research Traineeship IGERT"
dqm__url7_2 = "http://www.pslc.ws/igert/"
dqm__icon_index7_2 = 1
dqm__status_text7_2 = "Integrative Graduate Education and Research Traineeship IGERT"
dqm__micon_index0 = 0
dqm__main_hl_textcolor0 = "#0f0f0f"
dqm__url8 = vqm__database+"../index.html"
dqm__sub_xy1 = "-50,14"
dqm__sub_menu_width1 = 169
dqm__subdesc1_0 = "Dr. Roger D. Hester"
dqm__icon_index1_0 = 1
dqm__url1_0 = vqm__database+"../hester1.html"
dqm__status_text1_0 = "Dr. Roger D. Hester "
dqm__subdesc1_1 = "Dr. Charles E. Hoyle"
dqm__icon_index1_1 = 1
dqm__url1_1 = vqm__database+"../hoyle1.html"
dqm__status_text1_1 = "Dr. Charles E. Hoyle"
dqm__subdesc1_2 = "Dr. Robert Y. Lochhead "
dqm__icon_index1_2 = 1
dqm__url1_2 = vqm__database+"../lochhead1.html"
dqm__status_text1_2 = "Dr. Robert Y. Lochhead "
dqm__subdesc1_3 = "Dr. Lon J. Mathias "
dqm__icon_index1_3 = 1
dqm__url1_3 = vqm__database+"../mathias1.html"
dqm__status_text1_3 = "Dr. Lon J. Mathias "
dqm__subdesc1_4 = "Dr. Kenneth A. Mauritz"
dqm__icon_index1_4 = 1
dqm__url1_4 = vqm__database+"../mauritz1.html"
dqm__status_text1_4 = "Dr. Kenneth A. Mauritz"
dqm__subdesc1_5 = "Dr. Charles L. McCormick "
dqm__icon_index1_5 = 1
dqm__url1_5 = vqm__database+"../Mccormic.html"
dqm__status_text1_5 = "Dr. Charles L. McCormick "
dqm__subdesc1_6 = "Dr. Robert B. Moore "
dqm__icon_index1_6 = 1
dqm__url1_6 = vqm__database+"../moore1.html"
dqm__status_text1_6 = "Dr. Robert B. Moore "
dqm__subdesc1_7 = "Dr. Sarah E. Morgan "
dqm__icon_index1_7 = 1
dqm__url1_7 = vqm__database+"../morgan1.html"
dqm__status_text1_7 = "Dr. Sarah E. Morgan "
dqm__subdesc1_8 = "Dr. Sergei Nazarenko "
dqm__icon_index1_8 = 1
dqm__url1_8 = vqm__database+"../nazarenko1.html"
dqm__status_text1_8 = "Dr. Sergei Nazarenko "
dqm__subdesc1_9 = "Dr. Joshua U. Otaigbe"
dqm__icon_index1_9 = 1
dqm__url1_9 = vqm__database+"../otaigbe1.html"
dqm__status_text1_9 = "Dr. Joshua U. Otaigbe"
dqm__subdesc1_10 = "Dr. James W. Rawlins "
dqm__icon_index1_10 = 1
dqm__url1_10 = vqm__database+"../james1.html"
dqm__status_text1_10 = "Dr. James W. Rawlins "
dqm__subdesc1_11 = "Dr. Robson F. Storey "
dqm__icon_index1_11 = 1
dqm__url1_11 = vqm__database+"../storey1.html"
dqm__status_text1_11 = "Dr. Robson F. Storey "
dqm__subdesc1_12 = "Dr. Shelby F. Thames"
dqm__icon_index1_12 = 1
dqm__url1_12 = vqm__database+"../thames1.html"
dqm__status_text1_12 = "Dr. Shelby F. Thames"
dqm__subdesc1_13 = "Dr. Marek W. Urban "
dqm__icon_index1_13 = 1
dqm__url1_13 = vqm__database+"../marek1.html"
dqm__status_text1_13 = "Dr. Marek W. Urban "
dqm__subdesc1_14 = "Dr. Douglas A. Wicks"
dqm__icon_index1_14 = 1
dqm__url1_14 = vqm__database+"../wicksnew.html"
dqm__status_text1_14 = "Dr. Douglas A. Wicks"
dqm__subdesc1_15 = "Dr. Jeffrey S. Wiggins "
dqm__icon_index1_15 = 1
dqm__url1_15 = vqm__database+"../wiggins.html"
dqm__status_text1_15 = "Dr. Jeffrey S. Wiggins "
dqm__sub_xy3 = "-60,14"
dqm__sub_menu_width3 = 180
dqm__subdesc3_0 = "Graduate School Application"
dqm__icon_index3_0 = 1
dqm__url3_0 = "https://www.usm.edu/gradapp/"
dqm__status_text3_0 = "Graduate School Application"
dqm__subdesc5_1 = "Bayer Lecture Series"
dqm__icon_index5_1 = 1
dqm__url5_1 = vqm__database+"../bayer.html"
dqm__status_text5_1 = "Bayer Lecture Series"
dqm__subdesc7_3 = "Mississippi Polymer Institute"
dqm__icon_index7_3 = 1
dqm__url7_3 = "http://www.psrc.usm.edu/mpi/frontpg.htm"
dqm__status_text7_3 = "Mississippi Polymer Institute"
dqm__subdesc7_4 = "Macrogalleria"
dqm__icon_index7_4 = 1
dqm__url7_4 = "http://www.pslc.ws/macrog.htm"
dqm__status_text7_4 = "Macrogalleria"
dqm__subdesc7_5 = "Symposium Undergraduate Research in Polymer Science"
dqm__icon_index7_5 = 1
dqm__url7_5 = "http://www.psrc.usm.edu/ACS%20Atlanta%20(flyer).doc"
dqm__status_text7_5 = "Symposium Undergraduate Research in Polymer Science"
dqm__subdesc7_6 = "34th Annual International Waterborne, High-Solids, & Powder Coatings Symposium "
dqm__icon_index7_6 = 1
dqm__url7_6 = "http://www.psrc.usm.edu/waterborne/"
dqm__status_text7_6 = "34th Annual International Waterborne, High-Solids, & Powder Coatings Symposium "
dqm__subdesc7_7 = "College of Science & Technology"
dqm__icon_index7_7 = 1
dqm__url7_7 = "http://www.usm.edu/colleges/cost/"
dqm__status_text7_7 = "College of Science & Technology"
dqm__subdesc3_1 = "Graduate Handbook"
dqm__url3_1 = vqm__database+"../photos/Grad_Handbook.pdf"
dqm__icon_index3_1 = 1
dqm__status_text3_1 = "Graduate Handbook"
