/* Generated by Visual Menu Maker */


_VM_DATA=[
[{
"type":"horz",
"iconImageWidth":16,
"iconImageHeight":16,
"imagePath":"http://www.growthtrac.com/visualmenu/vm-images",
"delay":500,
"hArrowImage":"arrow_white.gif",
"hArrowImageWidth":4,
"hArrowImageHeight":8
}],
[
  [{"labelText":"home", "toolTip":"home", "status":"home", "url":"http://www.growthtrac.com"}],
  [{"type":"sep"}],
  [{"labelText":"love & marriage", "toolTip":"love & marriage", "status":"love & marriage", "url":"http://marriage.growthtrac.com/"}],
  [
    [{"labelText":"marriage", "toolTip":"marriage", "status":"marriage", "url":"http://marriage.growthtrac.com/"}],
    [{"labelText":"romance", "toolTip":"romance", "status":"romance", "url":"http://www.growthtrac.com/marriage/romantic.php"}],
    [{"labelText":"articles", "toolTip":"articles", "status":"articles", "url":"http://www.growthtrac.com/artman/publish/index2.php"}],
    [
      [{"labelText":"marriage", "toolTip":"marriage", "status":"marriage", "url":"http://www.growthtrac.com/artman/publish/cat_index_11.php"}],
      [{"labelText":"pre-marriage", "toolTip":"pre-marriage", "status":"pre-marriage", "url":"http://www.growthtrac.com/artman/publish/cat_index_12.php"}],
      [{"labelText":"interviews", "toolTip":"interviews", "status":"interviews", "url":"http://www.growthtrac.com/artman/publish/cat_index_14.php"}],
      [{"labelText":"growth", "toolTip":"growth", "status":"growth", "url":"http://www.growthtrac.com/artman/publish/cat_index_10.php"}],
      [{"labelText":"music", "toolTip":"music", "status":"music", "url":"http://www.growthtrac.com/artman/publish/cat_index_22.php"}],
      [{"labelImage":"bullets_sub.gif", "labelImageWidth":45, "labelImageHeight":3}],
      [{"labelText":"most popular", "toolTip":"most popular", "status":"most popular", "url":"http://www.growthtrac.com/popular.php"}],
      [{"labelText":"topics", "toolTip":"topics", "status":"topics", "url":"http://www.growthtrac.com/artman/topics/"}],
      [{"labelText":"authors", "toolTip":"authors", "status":"authors", "url":"http://www.growthtrac.com/artman/publish/authors.php"}],
      [{"labelText":"artists", "toolTip":"artists", "status":"artists", "url":"http://www.growthtrac.com/artman/publish/artists.php"}],
      [{"labelText":"audio clips", "toolTip":"audio clips", "status":"audio clips", "url":"http://www.growthtrac.com/cgi-bin/db/db.cgi?db=player&view=browse&uid=default&category=&ID=*&sb=2&so=ascend&view_records=View+Records"}]
    ],
    [{"labelText":"books,  music,  resources", "toolTip":"books,  music,  resources", "status":"books,  music,  resources", "url":"http://www.growthtrac.com/store/"}],
    [{"labelText":"events", "toolTip":"events", "status":"events", "url":"http://www.growthtrac.com/events/"}],
    [{"labelText":"marriage minute", "toolTip":"marriage minute", "status":"marriage minute", "url":"http://www.growthtrac.com/marriageminute/"}],
    [{"labelText":"spiritual discovery", "toolTip":"spiritual discovery", "status":"spiritual discovery", "url":"http://www.growthtrac.com/spiritual/"}],
    [
      [{"labelText":"basics", "toolTip":"spiritual basics", "status":"spiritual basics", "url":"http://www.growthtrac.com/spiritual/"}],
      [{"labelText":"questions", "toolTip":"questions", "status":"questions", "url":"http://www.growthtrac.com/spiritual/seekers.php"}],
      [{"labelText":"resources", "toolTip":"resources", "status":"resources", "url":"http://www.growthtrac.com/store/spiritual/"}],
      [{"labelText":"new christian", "toolTip":"new christian", "status":"new christian", "url":"http://www.growthtrac.com/spiritual/newchris.php"}]
    ],
    [{"labelText":"assessments", "toolTip":"assessments", "status":"assessments"}],
    [
      [{"labelText":"couple checkup", "toolTip":"couple checkup", "status":"couple checkup", "url":"http://www.growthtrac.com/checkup/"}],
      [{"labelText":"love talk", "toolTip":"love talk", "status":"love talk", "url":"http://www.growthtrac.com/lovetalk/"}]
    ],
    [{"labelText":"men's resources", "toolTip":"men's resources", "status":"men's resources", "url":"http://www.growthtrac.com/men/"}],
    [{"labelText":"ministry", "toolTip":"ministry", "status":"ministry", "url":"http://www.growthtrac.com/church/"}],
    [
      [{"labelText":"church e-news", "toolTip":"church e-news", "status":"church e-news", "url":"http://www.growthtrac.com/subscribe/church.php"}],
      [{"labelText":"free content!", "toolTip":"free content!", "status":"free content!", "url":"http://www.growthtrac.com/syndicate/"}],
      [{"labelText":"groupware & training", "toolTip":"groupware & training", "status":"groupware & training", "url":"http://www.growthtrac.com/store/ministry/"}],
      [{"labelText":"small groups", "toolTip":"small groups", "status":"small groups", "url":"http://www.growthtrac.com/store/group/"}],
      [{"labelText":"consulting", "toolTip":"consulting", "status":"consulting", "url":"http://www.growthtrac.com/church/consult.php"}],
      [{"labelText":"events", "toolTip":"events", "status":"events", "url":"http://www.growthtrac.com/events/gtevents.php"}]
    ]
  ],
  [{"type":"sep"}],
  [{"labelText":"help & healing", "toolTip":"help & healing", "status":"help & healing", "url":"http://www.growthtrac.com/special/"}],
  [
    [{"labelText":"discussion forums", "toolTip":"discussion forums", "status":"discussion forums", "url":"http://www.growthtrac.com/boards/"}],
    [{"labelText":"help topics", "toolTip":"help topics", "status":"help topics", "url":"http://www.growthtrac.com/special/"}],
    [
      [{"labelText":"counseling", "toolTip":"counseling", "status":"counseling", "url":"http://www.growthtrac.com/special/counseling/"}],
      [{"labelText":"affairs", "toolTip":"affairs", "status":"affairs", "url":"http://www.growthtrac.com/special/affair/"}],
      [{"labelText":"pornography", "toolTip":"pornography", "status":"pornography", "url":"http://www.growthtrac.com/special/pornography/"}],
      [{"labelText":"abuse", "toolTip":"abuse", "status":"abuse", "url":"http://www.growthtrac.com/special/abuse/"}],
      [{"labelText":"divorce", "toolTip":"divorce", "status":"divorce", "url":"http://www.growthtrac.com/special/divorce/"}],
      [{"labelText":"remarriage", "toolTip":"remarriage", "status":"remarriage", "url":"http://www.growthtrac.com/special/remarriage/"}],
      [{"labelText":"religion", "toolTip":"religion", "status":"religion", "url":"http://www.growthtrac.com/special/religion/"}],
      [{"labelText":"finances", "toolTip":"finances", "status":"finances", "url":"http://www.growthtrac.com/special/finances/"}],
      [{"labelText":"grieving", "toolTip":"grieving", "status":"grieving", "url":"http://www.growthtrac.com/special/grieve/"}]
    ],
    [{"labelText":"assessments", "toolTip":"assessments", "status":"assessments"}],
    [
      [{"labelText":"couple checkup", "toolTip":"couple checkup", "status":"couple checkup", "url":"http://www.growthtrac.com/checkup/"}],
      [{"labelText":"love talk", "toolTip":"love talk", "status":"love talk", "url":"http://www.growthtrac.com//lovetalk/"}]
    ],
    [{"labelText":"books,  music,  resources", "toolTip":"books,  music,  resources", "status":"books,  music,  resources", "url":"http://www.growthtrac.com/store/"}],
    [{"labelText":"articles", "toolTip":"articles", "status":"articles", "url":"http://www.growthtrac.com/artman/publish/index2.php"}],
    [{"labelText":"spiritual help", "toolTip":"spiritual help", "status":"spiritual help", "url":"http://www.growthtrac.com/spiritual/"}],
    [{"labelText":"marriage enrichment", "toolTip":"marriage enrichment", "status":"marriage enrichment", "url":"http://www.growthtrac.com/events/"}],
    [{"labelText":"the discover series", "toolTip":"the discover series", "status":"the discover series", "url":"http://www.growthtrac.com/discover/"}],
    [{"labelText":"email devotions", "toolTip":"email devotions", "status":"email devotions", "url":"http://www.growthtrac.com/devotional/"}],
    [{"labelText":"church locator", "toolTip":"church locator", "status":"church locator", "url":"http://www.growthtrac.com/church/looking.php"}],
    [{"labelText":"links", "toolTip":"links", "status":"links", "url":"http://www.growthtrac.com/links/"}]
  ],
  [{"type":"sep"}],
  [{"labelText":"singles & dating", "toolTip":"singles & dating", "status":"singles & dating"}],
  [
    [{"labelText":"compatibility test", "toolTip":"compatibility test", "status":"compatibility test", "url":"http://www.growthtrac.com/checkup"}],
    [{"labelText":"dating", "toolTip":"dating", "status":"dating", "url":"http://www.growthtrac.com/dating/"}],
    [{"labelText":"engaged", "toolTip":"engaged", "status":"engaged", "url":"http://www.growthtrac.com/premarried/"}],
    [{"labelText":"your wedding", "toolTip":"your wedding", "status":"your wedding", "url":"http://www.growthtrac.com/wedding"}],
    [{"labelText":"articles", "toolTip":"articles", "status":"articles", "url":"http://www.growthtrac.com/artman/publish/index2.php"}]
  ],
  [{"type":"sep"}],
  [{"labelText":"community", "toolTip":"community", "status":"community"}],
  [
    [{"labelText":"discussion forums", "toolTip":"discussion forums", "status":"discussion forums", "url":"http://www.growthtrac.com/boards/"}],
    [{"labelText":"chat", "toolTip":"chat", "status":"chat", "url":"http://www.growthtrac.com/chat/"}],
    [{"labelText":"podcasts", "toolTip":"podcasts", "status":"podcasts", "url":"http://www.growthtrac.com/podcast/"}],
    [{"labelText":"insidetrac blog", "toolTip":"insidetrac blog", "status":"insidetrac blog", "url":"http://inside.growthtrac.com/"}],
    [{"labelText":"small groups", "toolTip":"small groups", "status":"small groups", "url":"http://www.growthtrac.com/store/group/"}],
    [{"labelText":"ecards", "toolTip":"ecards", "status":"ecards", "url":"http://www.growthtrac.com/ecard/"}],
    [{"labelText":"connect", "toolTip":"connect", "status":"connect", "url":"http://www.growthtrac.com/connect/"}],
    [
      [{"labelText":"email devotions", "toolTip":"email devotions", "status":"email devotions", "url":"http://www.growthtrac.com/devotional/"}],
      [{"labelText":"monthly e-news", "toolTip":"monthly e-news", "status":"monthly e-news", "url":"http://www.growthtrac.com/subscribe/"}],
      [{"labelText":"rss feeds", "toolTip":"rss feeds", "status":"rss feeds", "url":"http://www.growthtrac.com/connect/rss.php"}],
      [{"labelText":"mobile", "toolTip":"mobile", "status":"mobile", "url":"http://www.growthtrac.com/connect/rss_mobile.php"}],
      [{"labelText":"avantgo", "toolTip":"avantgo", "status":"avantgo", "url":"http://www.growthtrac.com/avantgo/"}]
    ]
  ]
]
];