var ftrUserLocaleCookie = GetCookie('userLocaleCookie');
if (ftrUserLocaleCookie == null || ftrUserLocaleCookie == 'null') {
	ftrUserLocaleCookie = 'wcw';
}

if (ftrUserLocaleCookie == 'wcw')
{
	document.write('<!-- begin footer area -->\n');
	document.write('<table id="g1_footer" width="766" border="0" cellspacing="0" cellpadding="0" align="center">\n');
	document.write('<tr>\n');
	document.write('<td id="footerBoxGray">\n');
	document.write('<div id="footerColumn1">\n');
	document.write('<a class="footerWhiteHead" href="/it/about_gartner.jsp">About Gartner</a>\n');
	document.write('\n');
	document.write('<a class="footerWhiteLink" href="javascript:void(null)" onclick="openFooterLink(\'/it/clients/bac.html\')">Become a Client</a>\n');
	document.write('<a class="footerWhiteLink" href="/it/about/careers/career_at_gartner.jsp">Careers</a>\n');
	document.write('<a class="footerWhiteLink" href="/it/about/contact_gartner.jsp">Contact Gartner</a>\n');
	document.write('<a class="footerWhiteLink" href="/it/about_gartner.jsp#corporate_information">Corporate Information</a>\n');
	document.write('<a class="footerWhiteLink" href="http://investor.gartner.com/phoenix.zhtml?c=99568&p=irol-irhome" target="_blank">Investor Relations</a>\n');
	document.write('<a class="footerWhiteLink" href="/media_relations/asset_61507_1575.jsp">Media Relations</a>\n');
	document.write('<a class="footerWhiteLink" href="/it/about/contact_gartner.jsp">Office Locations</a>\n');
	document.write('<a class="footerWhiteLink" href="/it/about/why_use_gartner.jsp">Why Use Gartner</a>\n');
	document.write('</div>\n');
	document.write('\n');
	document.write('<div id="footerColumn2">\n');
	document.write('<a class="footerWhiteHead" href="/it/products_services.jsp">Products &amp; Services</a>\n');
	document.write('\n');
	document.write('<a class="footerWhiteLink" href="/it/products/consulting/consulting_overview.jsp">Consulting</a>\n');
	document.write('<a class="footerWhiteLink" href="/it/products/research/dataquest.jsp">Gartner Dataquest</a>\n');
	document.write('<a class="footerWhiteLink" href="/it/products/ep/executive_programs.jsp">Executive Programs</a>\n');
	document.write('<a class="footerWhiteLink" href="/it/products/events/events.jsp">Events</a>\n');
	document.write('<a class="footerWhiteLink" href="/5_about/news/gartnerPress.jsp">Gartner Books</a>\n');
	document.write('<a class="footerWhiteLink" href="/invest/asset_48655.jsp">Gartner Invest</a>\n');
	document.write('<a class="footerWhiteLink" href="/it/products/research/research_services.jsp">Research</a>\n');
	document.write('</div>\n');
	document.write('\n');
	document.write('<div id="footerColumn3">\n');
	document.write('<a class="footerWhiteHead" href="/it/about/vendor_relations.jsp">Vendor Relations</a>\n');
	document.write('\n');
	document.write('<a class="footerWhiteLink" href="/ps/media_products/asset_63308_1695.jsp">Media Products</a>\n');
	document.write('<a class="footerWhiteLink" href="/it/about/vendor_relations.jsp#quote">Quote Requests</a>\n');
	document.write('<a class="footerWhiteLink" href="/ps/media_products/asset_63607_1675.jsp">Reprints</a>\n');
	document.write('<a class="footerWhiteLink" href="/it/about/vendor_briefings.jsp">Vendor Briefings</a>\n');
	document.write('</div>\n');
	document.write('\n');
	document.write('<div id="footerColumn4">\n');
	document.write('<a class="footerWhiteHead" href="/it/about/gartner_policies.jsp">Gartner Policies</a>\n');
	document.write('\n');
	document.write('<a class="footerWhiteLink" href="/5_about/company_information/corrections.html">Corrections</a>\n');
	document.write('<a class="footerWhiteLink" href="http://investor.gartner.com/phoenix.zhtml?c=99568&p=irol-govHighlights" target="_blank">Governance</a>\n');
	document.write('<a class="footerWhiteLink" href="/it/about/omb_overview.jsp">Office of the Ombudsman</a>\n');
	document.write('<a class="footerWhiteLink" href="/pages/story.php.id.2630.s.8.jsp">Privacy</a>\n');
	document.write('<a class="footerWhiteLink" href="javascript:void(null)" onclick="openNewAdminFooter(\'/6_help/16.html\')">Terms of Use</a>\n');
	document.write('</div>\n');
	document.write('\n');
	document.write('<div id="footerColumn5">\n');
	document.write('<a class="footerWhiteHead" href="http://'+document.domain+'">gartner.com</a>\n');
	document.write('\n');
	document.write('<a class="footerWhiteLink" href="/5_about/news/notices/i508.jsp">Accessibility</a>\n');
	document.write('<a class="footerWhiteLink" href="javascript:void(null)" onclick="openFooterLink(\'/6_help/glossary/GlossaryMain.jsp\')">Glossary</a>\n');
	document.write('<a class="footerWhiteLink" href="/it/help/g_help.jsp">Help</a>\n');
	document.write('<a class="footerWhiteLink" href="/it/help/online_training.jsp">Online Training</a>\n');
	document.write('<a class="footerWhiteLink" href="/it/about/site_index.jsp">Site Index</a>\n');
	document.write('\n');
	document.write('<a class="footerWhiteLink" href="javascript:void(null)" onclick="openFooterLink(\'/TechSupport?param=No\')">Technical Support</a>\n');
	document.write('</div>\n');
	document.write('</td>\n');
	document.write('</tr>\n');
	document.write('<tr bgcolor="#FFFFFF">\n');
	document.write('<td id="footerBoxWhite">\n');
	document.write('<div id="footerWhiteBg1">\n');
	document.write('<span  class="gray9px">&copy; 2007 Gartner, Inc. and/or its Affiliates. All Rights Reserved.</span>\n');
	document.write('</div>\n');
	document.write('<div id="footerWhiteBg2">\n');
	document.write('<img src="/images/homepage/gartner80.gif" width="80" height="20" alt="" border="0" />\n');
	document.write('</div>\n');
	document.write('</td>\n');
	document.write('</tr>\n');
	document.write('</table>\n');
	document.write('<!-- end footer area -->\n');
	document.write('\n');

}
else {
	// Regional sites footer information
	document.open();

	if (ftrUserLocaleCookie == 'emea') {
		document.write('<!-- begin footer area -->\n');
		document.write('<table id="g1_footer" width="766" border="0" cellspacing="0" cellpadding="0" align="center">\n');
		document.write('<tr>\n');
		document.write('<td id="footerBoxGray">\n');
		document.write('<div id="footerColumn1">\n');
		document.write('<a class="footerWhiteHead" href="/it/about_gartner.jsp">About Gartner</a>\n');
		document.write('\n');
		document.write('<a class="footerWhiteLink" href="javascript:void(null)" onclick="openFooterLink(\'/it/clients/bac.html\')">Become a Client</a>\n');
		document.write('<a class="footerWhiteLink" href="/it/about/careers/career_at_gartner.jsp">Careers</a>\n');
		document.write('<a class="footerWhiteLink" href="/it/about/contact_gartner.jsp">Contact Gartner</a>\n');
		document.write('<a class="footerWhiteLink" href="/it/about_gartner.jsp#corporate_information">Corporate Information</a>\n');
		document.write('<a class="footerWhiteLink" href="http://investor.gartner.com/phoenix.zhtml?c=99568&p=irol-irhome" target="_blank">Investor Relations</a>\n');
		document.write('<a class="footerWhiteLink" href="/media_relations/asset_61507_1575.jsp">Media Relations</a>\n');
		document.write('<a class="footerWhiteLink" href="/it/about/contact_gartner.jsp">Office Locations</a>\n');
		document.write('<a class="footerWhiteLink" href="/it/about/why_use_gartner.jsp">Why Use Gartner</a>\n');
		document.write('</div>\n');
		document.write('\n');
		document.write('<div id="footerColumn2">\n');
		document.write('<a class="footerWhiteHead" href="/it/products_services.jsp">Products &amp; Services</a>\n');
		document.write('\n');
		document.write('<a class="footerWhiteLink" href="/it/products/consulting/consulting_overview.jsp">Consulting</a>\n');
		document.write('<a class="footerWhiteLink" href="/it/products/research/dataquest.jsp">Gartner Dataquest</a>\n');
		document.write('<a class="footerWhiteLink" href="/it/products/ep/executive_programs.jsp">Executive Programs</a>\n');
		document.write('<a class="footerWhiteLink" href="/it/products/events/events.jsp">Events</a>\n');
		document.write('<a class="footerWhiteLink" href="/5_about/news/gartnerPress.jsp">Gartner Books</a>\n');
		document.write('<a class="footerWhiteLink" href="/invest/asset_48655.jsp">Gartner Invest</a>\n');
		document.write('<a class="footerWhiteLink" href="/it/products/research/research_services.jsp">Research</a>\n');
		document.write('</div>\n');
		document.write('\n');
		document.write('<div id="footerColumn3">\n');
		document.write('<a class="footerWhiteHead" href="/it/about/vendor_relations.jsp">Vendor Relations</a>\n');
		document.write('\n');
		document.write('<a class="footerWhiteLink" href="/ps/media_products/asset_63308_1695.jsp">Media Products</a>\n');
		document.write('<a class="footerWhiteLink" href="/it/about/omb_overview.jsp">Office of the Ombudsman</a>\n');
		document.write('<a class="footerWhiteLink" href="/it/about/vendor_relations.jsp#quote">Quote Requests</a>\n');
		document.write('<a class="footerWhiteLink" href="/ps/media_products/asset_63607_1675.jsp">Reprints</a>\n');
		document.write('<a class="footerWhiteLink" href="/it/about/vendor_briefings.jsp">Vendor Briefings</a>\n');
		document.write('</div>\n');
		document.write('\n');
		document.write('<div id="footerColumn4">\n');
		document.write('<a class="footerWhiteHead" href="/it/about/gartner_policies.jsp">Gartner Policies</a>\n');
		document.write('\n');
		document.write('<a class="footerWhiteLink" href="/5_about/company_information/corrections.html">Corrections</a>\n');
		document.write('<a class="footerWhiteLink" href="http://investor.gartner.com/phoenix.zhtml?c=99568&p=irol-govHighlights" target="_blank">Governance</a>\n');
		document.write('<a class="footerWhiteLink" href="/it/about/omb_overview.jsp">Office of the Ombudsman</a>\n');
		document.write('<a class="footerWhiteLink" href="/pages/story.php.id.2630.s.8.jsp">Privacy</a>\n');
		document.write('<a class="footerWhiteLink" href="javascript:void(null)" onclick="openNewAdminFooter(\'/6_help/16.html\')">Terms of Use</a>\n');
		document.write('</div>\n');
		document.write('\n');
		document.write('<div id="footerColumn5">\n');
		document.write('<a class="footerWhiteHead" href="http://'+document.domain+'">gartner.com</a>\n');
		document.write('\n');
		document.write('<a class="footerWhiteLink" href="/5_about/news/notices/i508.jsp">Accessibility</a>\n');
		document.write('<a class="footerWhiteLink" href="javascript:void(null)" onclick="openFooterLink(\'/6_help/glossary/GlossaryMain.jsp\')">Glossary</a>\n');
		document.write('<a class="footerWhiteLink" href="/it/help/g_help.jsp">Help</a>\n');
		document.write('<a class="footerWhiteLink" href="/it/help/online_training.jsp">Online Training</a>\n');
		document.write('<a class="footerWhiteLink" href="/it/about/site_index.jsp">Site Index</a>\n');
		document.write('\n');
		document.write('<a class="footerWhiteLink" href="javascript:void(null)" onclick="openFooterLink(\'/TechSupport?param=No\')">Technical Support</a>\n');
		document.write('</div>\n');
		document.write('</td>\n');
		document.write('</tr>\n');
		document.write('<tr bgcolor="#FFFFFF">\n');
		document.write('<td id="footerBoxWhite">\n');
		document.write('<div id="footerWhiteBg1">\n');
		document.write('<span  class="gray9px">&copy; 2007 Gartner, Inc. and/or its Affiliates. All Rights Reserved.</span>\n');
		document.write('</div>\n');
		document.write('<div id="footerWhiteBg2">\n');
		document.write('<img src="/images/homepage/gartner80.gif" width="80" height="20" alt="" border="0" />\n');
		document.write('</div>\n');
		document.write('</td>\n');
		document.write('</tr>\n');
		document.write('</table>\n');
		document.write('<!-- end footer area -->\n');
		document.write('\n');

	}
	else if (ftrUserLocaleCookie == 'de') {
		document.write('<!-- begin footer area -->\n');
		document.write('<table id="g1_footer" width="766" border="0" cellspacing="0" cellpadding="0" align="center">\n');
		document.write('<tr>\n');
		document.write('<td id="footerBoxGray">\n');
		document.write('<div id="footerColumn1">\n');
		document.write('<a class="footerWhiteHead" href="/it/about_gartner.jsp">&Uuml;ber Gartner</a>\n');
		document.write('\n');
		document.write('<a class="footerWhiteLink" href="javascript:void(null)" onclick="openFooterLink(\'/it/clients/bac.html\')">Werden Sie Kunde</a>\n');
		document.write('<a class="footerWhiteLink" href="/it/about/careers/career_at_gartner.jsp">Stellenangebote</a>\n');
		document.write('<a class="footerWhiteLink" href="javascript:void(null)" onclick="openFooterLink(\'/it/about/contact_gartner.jsp\')">Kontaktieren Sie uns</a>\n');
		document.write('<a class="footerWhiteLink" href="/it/about_gartner.jsp#corporate_information">Unternehmensprofil</a>\n');
		document.write('<a class="footerWhiteLink" href="http://investor.gartner.com/phoenix.zhtml?c=99568&p=irol-irhome" target="_blank">Investor Relations</a>\n');
		document.write('<a class="footerWhiteLink" href="/media_relations/asset_61507_1575.jsp">Media Relations</a>\n');
		document.write('<a class="footerWhiteLink" href="/it/about/contact_gartner.jsp">Niederlassungen</a>\n');
		document.write('<a class="footerWhiteLink" href="/it/about/why_use_gartner.jsp">Wieso Gartner?</a>\n');
		document.write('</div>\n');
		document.write('\n');
		document.write('<div id="footerColumn2">\n');
		document.write('<a class="footerWhiteHead" href="/it/products_services.jsp">Produkte &amp; Services</a>\n');
		document.write('\n');
		document.write('<a class="footerWhiteLink" href="/it/products/consulting/consulting_overview.jsp">Consulting</a>\n');
		document.write('<a class="footerWhiteLink" href="/it/products/research/dataquest.jsp">Gartner Dataquest</a>\n');
		document.write('<a class="footerWhiteLink" href="/it/products/ep/executive_programs.jsp">Executive Programs</a>\n');
		document.write('<a class="footerWhiteLink" href="/it/products/events/events.jsp">Events</a>\n');
		document.write('<a class="footerWhiteLink" href="/5_about/news/gartnerPress.jsp">Gartner Books</a>\n');
		document.write('<a class="footerWhiteLink" href="/invest/asset_48655.jsp">Gartner Invest</a>\n');
		document.write('<a class="footerWhiteLink" href="/it/products/research/research_services.jsp">Research</a>\n');
		document.write('</div>\n');
		document.write('\n');
		document.write('<div id="footerColumn3">\n');
		document.write('<a class="footerWhiteHead" href="/it/about/vendor_relations.jsp">Vendor Relations</a>\n');
		document.write('\n');
		document.write('<a class="footerWhiteLink" href="/ps/media_products/asset_63308_1695.jsp">Medien-Produkte</a>\n');
		document.write('<a class="footerWhiteLink" href="/it/about/omb_overview.jsp">Office of Ombudsman</a>\n');
		document.write('<a class="footerWhiteLink" href="/it/about/vendor_relations.jsp#quote">Zitat-Anfragen</a>\n');
		document.write('<a class="footerWhiteLink" href="/ps/media_products/asset_63607_1675.jsp">Nachdrucke</a>\n');
		document.write('<a class="footerWhiteLink" href="/it/about/vendor_relations.jsp#brief">Vendor Briefings</a>\n');
		document.write('</div>\n');
		document.write('\n');
		document.write('<div id="footerColumn4">\n');
		document.write('<a class="footerWhiteHead" href="/it/about/gartner_policies.jsp">Gartner Policies</a>\n');
		document.write('\n');
		document.write('<a class="footerWhiteLink" href="/5_about/company_information/corrections.html">Korrekturen</a>\n');
		document.write('<a class="footerWhiteLink" href="http://investor.gartner.com/phoenix.zhtml?c=99568&p=irol-govHighlights" target="_blank">Regelungen</a>\n');
		document.write('<a class="footerWhiteLink" href="/it/about/omb_overview.jsp">Office of Ombudsman</a>\n');
		document.write('<a class="footerWhiteLink" href="/pages/story.php.id.2630.s.8.jsp">Datenschutz</a>\n');
		document.write('<a class="footerWhiteLink" href="javascript:void(null)" onclick="openNewAdminFooter(\'/6_help/16.html\')">Nutzungsbedingungen</a>\n');
		document.write('</div>\n');
		document.write('\n');
		document.write('<div id="footerColumn5">\n');
		document.write('<a class="footerWhiteHead" href="http://'+document.domain+'">gartner.com</a>\n');
		document.write('\n');
		document.write('<a class="footerWhiteLink" href="/5_about/news/notices/i508.jsp">Accessibility</a>\n');
		document.write('<a class="footerWhiteLink" href="javascript:void(null)" onclick="openFooterLink(\'/6_help/glossary/GlossaryMain.jsp\')">Glossar</a>\n');
		document.write('<a class="footerWhiteLink" href="/it/help/g_help.jsp">Hilfe</a>\n');
		document.write('<a class="footerWhiteLink" href="/it/help/online_training.jsp">Online-Training</a>\n');
		document.write('<a class="footerWhiteLink" href="/it/about/site_index.jsp">Site-Index</a>\n');
		document.write('\n');
		document.write('<a class="footerWhiteLink" href="javascript:void(null)" onclick="openFooterLink(\'/TechSupport?param=No\')">Technischer Support</a>\n');
		document.write('</div>\n');
		document.write('</td>\n');
		document.write('</tr>\n');
		document.write('<tr bgcolor="#FFFFFF">\n');
		document.write('<td id="footerBoxWhite">\n');
		document.write('<div id="footerWhiteBg1">\n');
		document.write('<span  class="gray9px">&copy; 2007 Gartner, Inc. und/oder seine Tochtergesellschaften. Alle Rechte vorbehalten. | <a class="blueLink9px" href="/regionalization/content/emea/de/06_impressum.html">Impressum</a></span>\n');
		document.write('</div>\n');
		document.write('<div id="footerWhiteBg2">\n');
		document.write('<img src="/images/homepage/gartner80.gif" width="80" height="20" alt="" border="0" />\n');
		document.write('</div>\n');
		document.write('</td>\n');
		document.write('</tr>\n');
		document.write('</table>\n');
		document.write('<!-- end footer area -->\n');
		document.write('\n');

	}

	else if (ftrUserLocaleCookie == 'it') {
		document.write('<!-- begin footer area -->\n');
		document.write('<table id="g1_footer" width="766" border="0" cellspacing="0" cellpadding="0" align="center">\n');
		document.write('<tr>\n');
		document.write('<td id="footerBoxGray">\n');
		document.write('<div id="footerColumn1">\n');
		document.write('<a class="footerWhiteHead" href="/it/about_gartner.jsp">Chi siamo</a>\n');
		document.write('\n');
		document.write('<a class="footerWhiteLink" href="javascript:void(null)" onclick="openFooterLink(\'/it/clients/bac.html\')">Diventa cliente</a>\n');
		document.write('<a class="footerWhiteLink" href="/it/about/careers/career_at_gartner.jsp">Opportunit&agrave; di lavoro</a>\n');
		document.write('<a class="footerWhiteLink" href="javascript:void(null)" onclick="openFooterLink(\'/it/about/contact_gartner.jsp\')">Contattaci</a>\n');
		document.write('<a class="footerWhiteLink" href="/it/about_gartner.jsp#corporate_information">Informazioni aziendali</a>\n');
		document.write('<a class="footerWhiteLink" href="http://investor.gartner.com/phoenix.zhtml?c=99568&p=irol-irhome" target="_blank">Relazioni con gli investitori</a>\n');
		document.write('<a class="footerWhiteLink" href="/media_relations/asset_61507_1575.jsp">Rapporti con i media</a>\n');
		document.write('<a class="footerWhiteLink" href="/it/about/contact_gartner.jsp">I nostri uffici</a>\n');
		document.write('<a class="footerWhiteLink" href="/it/about/why_use_gartner.jsp">Perch&eacute; Gartner</a>\n');
		document.write('</div>\n');
		document.write('\n');
		document.write('<div id="footerColumn2">\n');
		document.write('<a class="footerWhiteHead" href="/it/products_services.jsp">Prodotti e servizi</a>\n');
		document.write('\n');
		document.write('<a class="footerWhiteLink" href="/it/products/consulting/consulting_overview.jsp">Consulting</a>\n');
		document.write('<a class="footerWhiteLink" href="/it/products/research/dataquest.jsp">Gartner Dataquest</a>\n');
		document.write('<a class="footerWhiteLink" href="/it/products/ep/executive_programs.jsp">Executive Programs</a>\n');
		document.write('<a class="footerWhiteLink" href="/it/products/events/events.jsp">Events</a>\n');
		document.write('<a class="footerWhiteLink" href="/5_about/news/gartnerPress.jsp">Gartner Books</a>\n');
		document.write('<a class="footerWhiteLink" href="/invest/asset_48655.jsp">Facilita le decisioni d&acute;investimento</a>\n');
		document.write('<a class="footerWhiteLink" href="/it/products/research/research_services.jsp">Research</a>\n');
		document.write('</div>\n');
		document.write('\n');
		document.write('<div id="footerColumn3">\n');
		document.write('<a class="footerWhiteHead" href="/it/about/vendor_relations.jsp">Relazioni con i fornitori</a>\n');
		document.write('\n');
		document.write('<a class="footerWhiteLink" href="/ps/media_products/asset_63308_1695.jsp">Media</a>\n');
		document.write('<a class="footerWhiteLink" href="/it/about/omb_overview.jsp">Ufficio ombudsman</a>\n');
		document.write('<a class="footerWhiteLink" href="/it/about/vendor_relations.jsp#quote">Richiesta di contenuti</a>\n');
		document.write('<a class="footerWhiteLink" href="/ps/media_products/asset_63607_1675.jsp">Ristampe</a>\n');
		document.write('<a class="footerWhiteLink" href="/it/about/vendor_relations.jsp#brief">Briefing</a>\n');
		document.write('</div>\n');
		document.write('\n');
		document.write('<div id="footerColumn4">\n');
		document.write('<a class="footerWhiteHead" href="/it/about/gartner_policies.jsp">Policy Gartner</a>\n');
		document.write('\n');
		document.write('<a class="footerWhiteLink" href="/5_about/company_information/corrections.html">Correzioni</a>\n');
		document.write('<a class="footerWhiteLink" href="http://investor.gartner.com/phoenix.zhtml?c=99568&p=irol-govHighlights" target="_blank">Governance</a>\n');
		document.write('<a class="footerWhiteLink" href="/it/about/omb_overview.jsp">Ufficio ombudsman</a>\n');
		document.write('<a class="footerWhiteLink" href="/pages/story.php.id.2630.s.8.jsp">Informativa sulla privacy</a>\n');
		document.write('<a class="footerWhiteLink" href="javascript:void(null)" onclick="openNewAdminFooter(\'/6_help/16.html\')">Condizioni per l\'utilizzo</a>\n');
		document.write('</div>\n');
		document.write('\n');
		document.write('<div id="footerColumn5">\n');
		document.write('<a class="footerWhiteHead" href="http://'+document.domain+'">gartner.com</a>\n');
		document.write('\n');
		document.write('<a class="footerWhiteLink" href="/5_about/news/notices/i508.jsp">Accessibilit&agrave;</a>\n');
		document.write('<a class="footerWhiteLink" href="javascript:void(null)" onclick="openFooterLink(\'/6_help/glossary/GlossaryMain.jsp\')">Glossario</a>\n');
		document.write('<a class="footerWhiteLink" href="/it/help/g_help.jsp">Aiuto</a>\n');
		document.write('<a class="footerWhiteLink" href="/it/help/online_training.jsp">Training online</a>\n');
		document.write('<a class="footerWhiteLink" href="/it/about/site_index.jsp">Mappa del sito</a>\n');
		document.write('\n');
		document.write('<a class="footerWhiteLink" href="javascript:void(null)" onclick="openFooterLink(\'/TechSupport?param=No\')">Supporto tecnico</a>\n');
		document.write('</div>\n');
		document.write('</td>\n');
		document.write('</tr>\n');
		document.write('<tr bgcolor="#FFFFFF">\n');
		document.write('<td id="footerBoxWhite">\n');
		document.write('<div id="footerWhiteBg1">\n');
		document.write('<span  class="gray9px">&copy; 2007 Gartner, Inc. o le relative filiali. Tutti i diritti riservati.</span>\n');
		document.write('</div>\n');
		document.write('<div id="footerWhiteBg2">\n');
		document.write('<img src="/images/homepage/gartner80.gif" width="80" height="20" alt="" border="0" />\n');
		document.write('</div>\n');
		document.write('</td>\n');
		document.write('</tr>\n');
		document.write('</table>\n');
		document.write('<!-- end footer area -->\n');
		document.write('\n');

	}
	else if (ftrUserLocaleCookie == 'uk') {
		document.write('<!-- begin footer area -->\n');
		document.write('<table id="g1_footer" width="766" border="0" cellspacing="0" cellpadding="0" align="center">\n');
		document.write('<tr>\n');
		document.write('<td id="footerBoxGray">\n');
		document.write('<div id="footerColumn1">\n');
		document.write('<a class="footerWhiteHead" href="/it/about_gartner.jsp">About Gartner</a>\n');
		document.write('\n');
		document.write('<a class="footerWhiteLink" href="javascript:void(null)" onclick="openFooterLink(\'/it/clients/bac.html\')">Become a Client</a>\n');
		document.write('<a class="footerWhiteLink" href="/it/about/careers/career_at_gartner.jsp">Careers</a>\n');
		document.write('<a class="footerWhiteLink" href="/it/about/contact_gartner.jsp">Contact Gartner</a>\n');
		document.write('<a class="footerWhiteLink" href="/it/about_gartner.jsp#corporate_information">Corporate Information</a>\n');
		document.write('<a class="footerWhiteLink" href="http://investor.gartner.com/phoenix.zhtml?c=99568&p=irol-irhome" target="_blank">Investor Relations</a>\n');
		document.write('<a class="footerWhiteLink" href="/media_relations/asset_61507_1575.jsp">Media Relations</a>\n');
		document.write('<a class="footerWhiteLink" href="/it/about/contact_gartner.jsp">Office Locations</a>\n');
		document.write('<a class="footerWhiteLink" href="/it/about/why_use_gartner.jsp">Why Use Gartner</a>\n');
		document.write('</div>\n');
		document.write('\n');
		document.write('<div id="footerColumn2">\n');
		document.write('<a class="footerWhiteHead" href="/it/products_services.jsp">Products &amp; Services</a>\n');
		document.write('\n');
		document.write('<a class="footerWhiteLink" href="/it/products/consulting/consulting_overview.jsp">Consulting</a>\n');
		document.write('<a class="footerWhiteLink" href="/it/products/research/dataquest.jsp">Gartner Dataquest</a>\n');
		document.write('<a class="footerWhiteLink" href="/it/products/ep/executive_programs.jsp">Executive Programs</a>\n');
		document.write('<a class="footerWhiteLink" href="/it/products/events/events.jsp">Events</a>\n');
		document.write('<a class="footerWhiteLink" href="/5_about/news/gartnerPress.jsp">Gartner Books</a>\n');
		document.write('<a class="footerWhiteLink" href="/invest/asset_48655.jsp">Gartner Invest</a>\n');
		document.write('<a class="footerWhiteLink" href="/it/products/research/research_services.jsp">Research</a>\n');
		document.write('</div>\n');
		document.write('\n');
		document.write('<div id="footerColumn3">\n');
		document.write('<a class="footerWhiteHead" href="/it/about/vendor_relations.jsp">Vendor Relations</a>\n');
		document.write('\n');
		document.write('<a class="footerWhiteLink" href="/ps/media_products/asset_63308_1695.jsp">Media Products</a>\n');
		document.write('<a class="footerWhiteLink" href="/it/about/omb_overview.jsp">Office of the Ombudsman</a>\n');
		document.write('<a class="footerWhiteLink" href="/it/about/vendor_relations.jsp#quote">Quote Requests</a>\n');
		document.write('<a class="footerWhiteLink" href="/ps/media_products/asset_63607_1675.jsp">Reprints</a>\n');
		document.write('<a class="footerWhiteLink" href="/it/about/vendor_briefings.jsp">Vendor Briefings</a>\n');
		document.write('</div>\n');
		document.write('\n');
		document.write('<div id="footerColumn4">\n');
		document.write('<a class="footerWhiteHead" href="/it/about/gartner_policies.jsp">Gartner Policies</a>\n');
		document.write('\n');
		document.write('<a class="footerWhiteLink" href="/5_about/company_information/corrections.html">Corrections</a>\n');
		document.write('<a class="footerWhiteLink" href="http://investor.gartner.com/phoenix.zhtml?c=99568&p=irol-govHighlights" target="_blank">Governance</a>\n');
		document.write('<a class="footerWhiteLink" href="/it/about/omb_overview.jsp">Office of the Ombudsman</a>\n');
		document.write('<a class="footerWhiteLink" href="/pages/story.php.id.2630.s.8.jsp">Privacy</a>\n');
		document.write('<a class="footerWhiteLink" href="javascript:void(null)" onclick="openNewAdminFooter(\'/6_help/16.html\')">Terms of Use</a>\n');
		document.write('</div>\n');
		document.write('\n');
		document.write('<div id="footerColumn5">\n');
		document.write('<a class="footerWhiteHead" href="http://'+document.domain+'">gartner.com</a>\n');
		document.write('\n');
		document.write('<a class="footerWhiteLink" href="/5_about/news/notices/i508.jsp">Accessibility</a>\n');
		document.write('<a class="footerWhiteLink" href="javascript:void(null)" onclick="openFooterLink(\'/6_help/glossary/GlossaryMain.jsp\')">Glossary</a>\n');
		document.write('<a class="footerWhiteLink" href="/it/help/g_help.jsp">Help</a>\n');
		document.write('<a class="footerWhiteLink" href="/it/help/online_training.jsp">Online Training</a>\n');
		document.write('<a class="footerWhiteLink" href="/it/about/site_index.jsp">Site Index</a>\n');
		document.write('\n');
		document.write('<a class="footerWhiteLink" href="javascript:void(null)" onclick="openFooterLink(\'/TechSupport?param=No\')">Technical Support</a>\n');
		document.write('</div>\n');
		document.write('</td>\n');
		document.write('</tr>\n');
		document.write('<tr bgcolor="#FFFFFF">\n');
		document.write('<td id="footerBoxWhite">\n');
		document.write('<div id="footerWhiteBg1">\n');
		document.write('<span  class="gray9px">&copy; 2007 Gartner, Inc. and/or its Affiliates. All Rights Reserved.</span>\n');
		document.write('</div>\n');
		document.write('<div id="footerWhiteBg2">\n');
		document.write('<img src="/images/homepage/gartner80.gif" width="80" height="20" alt="" border="0" />\n');
		document.write('</div>\n');
		document.write('</td>\n');
		document.write('</tr>\n');
		document.write('</table>\n');
		document.write('<!-- end footer area -->\n');
		document.write('\n');

	}
	else if (ftrUserLocaleCookie == 'at') {
		document.write('<!-- begin footer area -->\n');
		document.write('<table id="g1_footer" width="766" border="0" cellspacing="0" cellpadding="0" align="center">\n');
		document.write('<tr>\n');
		document.write('<td id="footerBoxGray">\n');
		document.write('<div id="footerColumn1">\n');
		document.write('<a class="footerWhiteHead" href="/it/about_gartner.jsp">&Uuml;ber Gartner</a>\n');
		document.write('\n');
		document.write('<a class="footerWhiteLink" href="javascript:void(null)" onclick="openFooterLink(\'/it/clients/bac.html\')">Werden Sie Kunde</a>\n');
		document.write('<a class="footerWhiteLink" href="/it/about/careers/career_at_gartner.jsp">Stellenangebote</a>\n');
		document.write('<a class="footerWhiteLink" href="javascript:void(null)" onclick="openFooterLink(\'/it/about/contact_gartner.jsp\')">Kontaktieren Sie uns</a>\n');
		document.write('<a class="footerWhiteLink" href="/it/about_gartner.jsp#corporate_information">Unternehmensprofil</a>\n');
		document.write('<a class="footerWhiteLink" href="http://investor.gartner.com/phoenix.zhtml?c=99568&p=irol-irhome" target="_blank">Investor Relations</a>\n');
		document.write('<a class="footerWhiteLink" href="/media_relations/asset_61507_1575.jsp">Media Relations</a>\n');
		document.write('<a class="footerWhiteLink" href="/it/about/contact_gartner.jsp">Niederlassungen</a>\n');
		document.write('<a class="footerWhiteLink" href="/it/about/why_use_gartner.jsp">Wieso Gartner?</a>\n');
		document.write('</div>\n');
		document.write('\n');
		document.write('<div id="footerColumn2">\n');
		document.write('<a class="footerWhiteHead" href="/it/products_services.jsp">Produkte &amp; Services</a>\n');
		document.write('\n');
		document.write('<a class="footerWhiteLink" href="/it/products/consulting/consulting_overview.jsp">Consulting</a>\n');
		document.write('<a class="footerWhiteLink" href="/it/products/research/dataquest.jsp">Gartner Dataquest</a>\n');
		document.write('<a class="footerWhiteLink" href="/it/products/ep/executive_programs.jsp">Executive Programs</a>\n');
		document.write('<a class="footerWhiteLink" href="/it/products/events/events.jsp">Events</a>\n');
		document.write('<a class="footerWhiteLink" href="/5_about/news/gartnerPress.jsp">Gartner Books</a>\n');
		document.write('<a class="footerWhiteLink" href="/invest/asset_48655.jsp">Gartner Invest</a>\n');
		document.write('<a class="footerWhiteLink" href="/it/products/research/research_services.jsp">Research</a>\n');
		document.write('</div>\n');
		document.write('\n');
		document.write('<div id="footerColumn3">\n');
		document.write('<a class="footerWhiteHead" href="/it/about/vendor_relations.jsp">Vendor Relations</a>\n');
		document.write('\n');
		document.write('<a class="footerWhiteLink" href="/ps/media_products/asset_63308_1695.jsp">Medien-Produkte</a>\n');
		document.write('<a class="footerWhiteLink" href="/it/about/omb_overview.jsp">Office of Ombudsman</a>\n');
		document.write('<a class="footerWhiteLink" href="/it/about/vendor_relations.jsp#quote">Zitat-Anfragen</a>\n');
		document.write('<a class="footerWhiteLink" href="/ps/media_products/asset_63607_1675.jsp">Nachdrucke</a>\n');
		document.write('<a class="footerWhiteLink" href="/it/about/vendor_relations.jsp#brief">Vendor Briefings</a>\n');
		document.write('</div>\n');
		document.write('\n');
		document.write('<div id="footerColumn4">\n');
		document.write('<a class="footerWhiteHead" href="/it/about/gartner_policies.jsp">Gartner Policies</a>\n');
		document.write('\n');
		document.write('<a class="footerWhiteLink" href="/5_about/company_information/corrections.html">Korrekturen</a>\n');
		document.write('<a class="footerWhiteLink" href="http://investor.gartner.com/phoenix.zhtml?c=99568&p=irol-govHighlights" target="_blank">Regelungen</a>\n');
		document.write('<a class="footerWhiteLink" href="/it/about/omb_overview.jsp">Office of Ombudsman</a>\n');
		document.write('<a class="footerWhiteLink" href="/pages/story.php.id.2630.s.8.jsp">Datenschutz</a>\n');
		document.write('<a class="footerWhiteLink" href="javascript:void(null)" onclick="openNewAdminFooter(\'/6_help/16.html\')">Nutzungsbedingungen</a>\n');
		document.write('</div>\n');
		document.write('\n');
		document.write('<div id="footerColumn5">\n');
		document.write('<a class="footerWhiteHead" href="http://'+document.domain+'">gartner.com</a>\n');
		document.write('\n');
		document.write('<a class="footerWhiteLink" href="/5_about/news/notices/i508.jsp">Accessibility</a>\n');
		document.write('<a class="footerWhiteLink" href="javascript:void(null)" onclick="openFooterLink(\'/6_help/glossary/GlossaryMain.jsp\')">Glossar</a>\n');
		document.write('<a class="footerWhiteLink" href="/it/help/g_help.jsp">Hilfe</a>\n');
		document.write('<a class="footerWhiteLink" href="/it/help/online_training.jsp">Online-Training</a>\n');
		document.write('<a class="footerWhiteLink" href="/it/about/site_index.jsp">Site-Index</a>\n');
		document.write('\n');
		document.write('<a class="footerWhiteLink" href="javascript:void(null)" onclick="openFooterLink(\'/TechSupport?param=No\')">Technischer Support</a>\n');
		document.write('</div>\n');
		document.write('</td>\n');
		document.write('</tr>\n');
		document.write('<tr bgcolor="#FFFFFF">\n');
		document.write('<td id="footerBoxWhite">\n');
		document.write('<div id="footerWhiteBg1">\n');
		document.write('<span  class="gray9px">&copy; 2007 Gartner, Inc. und/oder seine Tochtergesellschaften. Alle Rechte vorbehalten. | <a class="blueLink9px" href="/regionalization/content/emea/de/at/06_impressum.html">Impressum</a></span>\n');
		document.write('</div>\n');
		document.write('<div id="footerWhiteBg2">\n');
		document.write('<img src="/images/homepage/gartner80.gif" width="80" height="20" alt="" border="0" />\n');
		document.write('</div>\n');
		document.write('</td>\n');
		document.write('</tr>\n');
		document.write('</table>\n');
		document.write('<!-- end footer area -->\n');
		document.write('\n');

	}
	document.close();
}
