
var mainmenu_MENU_POS = [
{
'height':25,
'width':160,
'block_top':0,
'block_left':0,
'top':25,
'left':0,
'hide_delay':600,
'expd_delay':-1,
'css':{
'outer':['mainmenu_l0oout','mainmenu_l0oover'],
'inner':['mainmenu_l0iout','mainmenu_l0iover']
}
},
{
'height':20,
'width':116,
'block_top':0,
'block_left':160,
'top':20,
'left':0,
'css':{
'outer':['mainmenu_l1oout','mainmenu_l1oover'],
'inner':['mainmenu_l1iout','mainmenu_l1iover']
}
},
{
'block_top':0,
'block_left':116
}
]
