function showHeader()
{	
document.write('<!--- HEAD-1 --------------------------------------->')
document.write('<table bgcolor=#f6f2e7 width=100% height=46 border=0 cellspacing=0 cellpadding=0>')
document.write('<tr>')
document.write('<td valign=top width=228 height=46 align=left>')
document.write('    <a href=index.html><img src=img/head-11.jpg border=0 alt="COLING 2002 Home Page"></a></td>')
document.write('<td bgcolor=#f6f2e7 align=left height=46>&nbsp;</td>')
document.write('<td width=478 height=46 align=right>')
document.write('    <img src=img/head-12.jpg border=0 alt="COLING 2002 Home Page"></td>')
document.write('</tr>')
document.write('</table>')
document.write(' ')
document.write('<!--- HEAD-2 --------------------------------------->')
document.write('<table background=img/head-22-bg.jpg width=100% height=58 border=0 cellspacing=0 cellpadding=0>')
document.write('<tr>')
document.write('<td valign=top width=233 height=58 align=left>')
document.write('    <a href=index.html><img src=img/head-21.jpg border=0></a></td>')
document.write('<td height=46><img src=img/head-22-bg.jpg border=0></td>')
document.write('<td width=530 height=58 align=right>')
document.write('    <map name=head>')
document.write('    <area coords="0,43,47,57" href="index.html">')
document.write('    <area coords="53,43,91,57" href="mailto:COLING02@sinica.edu.tw">')
document.write('    </map>')
document.write('    <img src=img/head-22.jpg border=0 usemap=#head></td>')
document.write('</tr>')
document.write('</table>')
}

