	var NoOffFirstLineMenus=8;			// Number of first level items
	var LowBgColor='ffffff';			// Background color when mouse is not over
	var LowSubBgColor='ffffff';			// Background color when mouse is not over on subs
	var HighBgColor='444444';			// Background color when mouse is over
	var HighSubBgColor='444444';			// Background color when mouse is over on subs
	var FontLowColor='444444';			// Font color when mouse is not over
	var FontSubLowColor='444444';			// Font color subs when mouse is not over
	var FontHighColor='ffffff';			// Font color when mouse is over
	var FontSubHighColor='ffffff';			// Font color subs when mouse is over
	var BorderColor='444444';			// Border color
	var BorderSubColor='444444';			// Border color for subs
	var BorderWidth=1;				// Border width
	var BorderBtwnElmnts=1;				// Border between elements 1 or 0
	var FontFamily="arial,comic sans ms,technical"	// Font family menu items
	var FontSize=8;					// Font size menu items
	var FontBold=1;					// Bold menu items 1 or 0
	var FontItalic=0;				// Italic menu items 1 or 0
	var MenuTextCentered='center';			// Item text position 'left', 'center' or 'right'
	var MenuCentered='center';			// Menu horizontal position 'left', 'center' or 'right'
	var MenuVerticalCentered='top';			// Menu vertical position 'top', 'middle','bottom' or static
	var ChildOverlap=.2;				// horizontal overlap child/ parent
	var ChildVerticalOverlap=.2;			// vertical overlap child/ parent
	var StartTop=0;					// Menu offset x coordinate
	var StartLeft=0;				// Menu offset y coordinate
	var VerCorrect=0;				// Multiple frames y correction
	var HorCorrect=0;				// Multiple frames x correction
	var LeftPaddng=2;				// Left padding
	var TopPaddng=2;				// Top padding
	var FirstLineHorizontal=1;			// SET TO 1 FOR HORIZONTAL MENU, 0 FOR VERTICAL
	var MenuFramesVertical=0;			// Frames in cols or rows 1 or 0
	var DissapearDelay=1000;			// delay before menu folds in
	var TakeOverBgColor=0;				// Menu frame takes over background color subitem frame
	var FirstLineFrame='MyFrameOne';		// Frame where first level appears
	var SecLineFrame='MyFrameTwo';			// Frame where sub levels appear
	var DocTargetFrame='MyFrameTwo';		// Frame where target documents appear
	var TargetLoc='';				// span id for relative positioning
	var HideTop=0;					// Hide first level when loading new document 1 or 0
	var MenuWrap=1;					// enables/ disables menu wrap 1 or 0
	var RightToLeft=0;				// enables/ disables right to left unfold 1 or 0
	var UnfoldsOnClick=0;				// Level 1 unfolds onclick/ onmouseover
	var WebMasterCheck=0;				// menu tree checking on or off 1 or 0
	var ShowArrow=1;				// Uses arrow gifs when 1
	var KeepHilite=1;				// Keep selected path highligthed
	var Arrws=['http://www.mtcps.org/images/navbar/tri.gif',5,10,'http://www.mtcps.org/images/navbar/tridown.gif',10,5,'http://www.mtcps.org/images/navbar/trileft.gif',5,10];	// Arrow source, width and height

function BeforeStart(){return}
function AfterBuild(){return}
function BeforeFirstOpen(){return}
function AfterCloseAll(){return}


// 	Menu tree
//	MenuX=new Array(Text to show, Link, background image (optional), number of sub elements, height, width);
//	For rollover images set "Text to show" to:  "rollover:Image1.jpg:Image2.jpg"

Menu1=new Array("Home","http://www.mtcps.org/home_main.shtml","",0,20,45);

Menu2=new Array("Board Of Ed","","",6,20,90);
	Menu2_1=new Array("Board Of Education","http://www.mtcps.org/central_administration/200607-board_of_education.shtml","",4,20,150);
		Menu2_1_1=new Array("Members","http://www.mtcps.org/central_administration/200607-board_of_education.shtml#members","",0,20,160);
		Menu2_1_2=new Array("Meeting Schedule","http://www.mtcps.org/central_administration/200607-board_of_education.shtml#schedule","",0);
		Menu2_1_3=new Array("School Board Recognition","http://www.mtcps.org/central_administration/200607-school_board_recognition.shtml","",0);
		Menu2_1_4=new Array("Policy Manual","http://www.neola.com/mtclemens-mi/","",0);
	Menu2_2=new Array("Administration Building","http://www.mtcps.org/central_administration/admin_building.shtml","",1);
		Menu2_2_1=new Array("Central Office Move","http://www.mtcps.org/central_administration/press_release/CentralOfficeMove0806.pdf","",0,20,125);
	Menu2_3=new Array("Business Services","","",7);
		Menu2_3_1=new Array("Food Service","","",1,20,144);
			Menu2_3_1_1=new Array("No postings available at this time.","","",0,20,200);
		Menu2_3_2=new Array("Forms","","",1);
			Menu2_3_2_1=new Array("Fund Raising Packet","http://www.mtcps.org/pdfs/2006_FundraisingProcedures.pdf","",0,20,125);
		Menu2_3_3=new Array("Technology Helpdesk","http://www.mtcps.org/helpdesk","",1);
			Menu2_3_3_1=new Array("Technology Service Request Form","http://www.mtcps.org/helpdesk/tsrf.shtml","",0,20,200);
		Menu2_3_4=new Array("Bids","","",1);
			Menu2_3_4_1=new Array("Building Prints","","",7,20,125);
				Menu2_3_4_1_1=new Array("Administration Building","http://www.mtcps.org/central_administration/buildingprints/AdministrationBuilding.pdf","",0,20,150);
				Menu2_3_4_1_2=new Array("High School","http://www.mtcps.org/central_administration/buildingprints/HighSchool.pdf","",0);
				Menu2_3_4_1_3=new Array("King","http://www.mtcps.org/central_administration/buildingprints/King.pdf","",0);
				Menu2_3_4_1_4=new Array("Lincoln","http://www.mtcps.org/central_administration/buildingprints/Lincoln.pdf","",0);
				Menu2_3_4_1_5=new Array("Macomb","http://www.mtcps.org/central_administration/buildingprints/Macomb.pdf","",0);
				Menu2_3_4_1_6=new Array("Middle School","http://www.mtcps.org/central_administration/buildingprints/MiddleSchool.pdf","",0);
				Menu2_3_4_1_7=new Array("Washington","http://www.mtcps.org/central_administration/buildingprints/Washington.pdf","",0);
		Menu2_3_5=new Array("Audits","","",2);
			Menu2_3_5_1=new Array("2005 Audit Report","","",2,20,150);
				Menu2_3_5_1_1=new Array("Single Audit for June 30, 2005","http://www.mtcps.org/central_administration/audits/2005/50160SA.pdf","",0,20,180);
				Menu2_3_5_1_2=new Array("Audit for June 30, 2005","http://www.mtcps.org/central_administration/audits/2005/50160FS.pdf","",0);
			Menu2_3_5_2=new Array("2004 Audit Report","","",2);
				Menu2_3_5_2_1=new Array("Single Audit for June 30, 2004","http://www.mtcps.org/central_administration/audits/2004/50160SA.pdf","",0,20,180);
				Menu2_3_5_2_2=new Array("Audit for June 30, 2004","http://www.mtcps.org/central_administration/audits/2004/50160FS.pdf","",0);
		Menu2_3_6=new Array("E.R.I.","","",2);
			Menu2_3_6_1=new Array("IRS Opinion Letter","http://www.mtcps.org/central_administration/eri/IRSOpinionLetter6-18-02.pdf","",0,20,150);
			Menu2_3_6_2=new Array("MCEA Eligibility","http://www.mtcps.org/central_administration/eri/MEA050205Eligible.pdf","",0);
		Menu2_3_7=new Array("Budget","","",2);
			Menu2_3_7_1=new Array("General Fund Budget Projections","http://www.mtcps.org/central_administration/budget/OriginalBudget.pdf","",0,20,200);
			Menu2_3_7_2=new Array("General Appropriation Resolution","http://www.mtcps.org/central_administration/budget/2006-07GeneralAppropriationResolutionOriginal.pdf","",0);
	Menu2_4=new Array("Human Resources","","",3);
		Menu2_4_1=new Array("Monthly Newsletters","","",3,20,140);
			Menu2_4_1_1=new Array("January 2006","http://www.mtcps.org/central_administration/hr/January2007.pdf","",0,20,100);
			Menu2_4_1_2=new Array("2006","","",9);
				Menu2_4_1_2_1=new Array("December 2006","http://www.mtcps.org/central_administration/hr/December2006.pdf","",0,20,100);
				Menu2_4_1_2_2=new Array("November 2006","http://www.mtcps.org/central_administration/hr/November2006.pdf","",0);
				Menu2_4_1_2_3=new Array("October 2006","http://www.mtcps.org/central_administration/hr/October2006.pdf","",0);
				Menu2_4_1_2_4=new Array("September 2006","http://www.mtcps.org/central_administration/hr/September2006.pdf","",0);
				Menu2_4_1_2_5=new Array("May 2006","http://www.mtcps.org/central_administration/hr/May2006.pdf","",0);
				Menu2_4_1_2_6=new Array("April 2006","http://www.mtcps.org/central_administration/hr/April2006.pdf","",0);
				Menu2_4_1_2_7=new Array("March 2006","http://www.mtcps.org/central_administration/hr/March2006.pdf","",0);
				Menu2_4_1_2_8=new Array("February 2006","http://www.mtcps.org/central_administration/hr/February2006.pdf","",0);
				Menu2_4_1_2_9=new Array("January 2006","http://www.mtcps.org/central_administration/hr/January2006.pdf","",0);
			Menu2_4_1_3=new Array("2005","","",10);
				Menu2_4_1_3_1=new Array("December 2005","http://www.mtcps.org/central_administration/hr/December2005.pdf","",0,20,100);
				Menu2_4_1_3_2=new Array("November 2005","http://www.mtcps.org/central_administration/hr/November2005.pdf","",0);
				Menu2_4_1_3_3=new Array("October 2005","http://www.mtcps.org/central_administration/hr/October2005.pdf","",0);
				Menu2_4_1_3_4=new Array("September 2005","http://www.mtcps.org/central_administration/hr/September2005.pdf","",0);
				Menu2_4_1_3_5=new Array("August 2005","http://www.mtcps.org/central_administration/hr/August2005.pdf","",0);
				Menu2_4_1_3_6=new Array("June 2005","http://www.mtcps.org/central_administration/hr/June2005.pdf","",0);
				Menu2_4_1_3_7=new Array("May 2005","http://www.mtcps.org/central_administration/hr/May2005.pdf","",0);
				Menu2_4_1_3_8=new Array("April 2005","http://www.mtcps.org/central_administration/hr/April2005.pdf","",0);
				Menu2_4_1_3_9=new Array("March 2005","http://www.mtcps.org/central_administration/hr/March2005.pdf","",0);
				Menu2_4_1_3_10=new Array("February 2005","http://www.mtcps.org/central_administration/hr/February2005.pdf","",0);
		Menu2_4_2=new Array("Job Postings","","",1);
//			Menu2_4_2_1=new Array("No postings available at this time.","","",0,20,200)
			Menu2_4_2_1=new Array("Click Here For All Job Postings","http://www.mtcps.org/employment/employment.shtml","",0,20,210);
		Menu2_4_3=new Array("2005-2006 MCCS-Stars","http://www.mtcps.org/district_info/200506_mccs-stars.shtml","",0);
	Menu2_5=new Array("Press Releases","http://www.mtcps.org/central_administration/press_release.shtml","",0);
	Menu2_6=new Array("School Information","http://www.mtcps.org/school_info/school_info.shtml","",6);
		Menu2_6_1=new Array("2006-2007 School Calendars (Revised 01/18/07)","http://www.mtcps.org/district_info/pdfs/2006-2007SchoolCalendar.pdf","",0,20,275);
		Menu2_6_2=new Array("2006-2007 School Start Times","http://www.mtcps.org/district_info/pdfs/200607sst.pdf","",0);
		Menu2_6_3=new Array("Fact Sheet for 2006-2007 School Year","http://www.mtcps.org/district_info/pdfs/FactSheet2006.pdf","",0);
		Menu2_6_4=new Array("2nd Annual Parade of Success","http://www.mtcps.org/district_info/2006_Parade-of-Success.shtml","",0);
		Menu2_6_5=new Array("Mayor's Proclamation","http://www.mtcps.org/district_info/pdfs/ParadeProclamation2006.pdf","",0);
		Menu2_6_6=new Array("Improving Our Telephone System For You","http://www.mtcps.org/district_info/voip.shtml","",0);

Menu3=new Array("Secondary","","",2,20,85);
	Menu3_1=new Array("High School (9-12)","http://www.mtcps.org/secondary/highschool/Welcome.shtml","",6,20,134);
		Menu3_1_1=new Array("Home Page","http://www.mtcps.org/secondary/highschool/Welcome.shtml","",0,20,168);
		Menu3_1_2=new Array("Staff Directories","","",4);
			Menu3_1_2_1=new Array("Administrative","http://www.mtcps.org/secondary/highschool/administrative/Welcome.shtml","",0,20,130);
			Menu3_1_2_2=new Array("Athletic","http://www.mtcps.org/secondary/highschool/athletic/staff.shtml","",0);
			Menu3_1_2_3=new Array("Counseling","http://www.mtcps.org/secondary/highschool/counseling/Welcome.shtml","",0);
			Menu3_1_2_4=new Array("Instructional","http://www.mtcps.org/secondary/highschool/instructional/Welcome.shtml","",0);
		Menu3_1_3=new Array("Althletic Department","","",2);
			Menu3_1_3_1=new Array("Schedules","http://www.mtcps.org/secondary/highschool/athletic/schedules/Welcome.shtml","",0,20,138);
			Menu3_1_3_2=new Array("Message Board","http://www.mtcps.org/secondary/highschool/athletic/message_board.shtml","",0);
		Menu3_1_4=new Array("Extra Curricular","","",5);
			Menu3_1_4_1=new Array("BPA","http://www.mtcps.org/secondary/highschool/extracurricular/bpa/Welcome.html","",0,20,100);
			Menu3_1_4_2=new Array("NHS","http://www.mtcps.org/secondary/highschool/extracurricular/nhs/Welcome.html","",0);
			Menu3_1_4_3=new Array("KEY CLUB","http://www.mtcps.org/secondary/highschool/extracurricular/key_club/Welcome.html","",0);
			Menu3_1_4_4=new Array("QUIZ BOWL","http://www.mtcps.org/secondary/highschool/extracurricular/Quiz%20Bowl/Quiz%20Bowl.htm","",0);
			Menu3_1_4_5=new Array("SA","http://www.mtcps.org/secondary/highschool/extracurricular/sa/Welcome.html","",0);
		Menu3_1_5=new Array("School Pages","","",4);
			Menu3_1_5_1=new Array("Art Department","http://www.mtcps.org/secondary/highschool/ArtDepartment/Art%20Department.htm","",0,20,200);
			Menu3_1_5_2=new Array("Journalism","http://www.mtcps.org/secondary/highschool/Journalism/Journalism.htm","",0);
			Menu3_1_5_3=new Array("Yearbook","http://www.mtcps.org/secondary/highschool/Yearbook/Yearbook.htm","",0);
			Menu3_1_5_4=new Array("MCHS Planetarium","http://www.mtcps.org/secondary/highschool/MCHS%20Planetarium/Welcome.html","",0);
		Menu3_1_6=new Array("Media Center","http://www.mtcps.org/secondary/highschool/MCHS%20Library/library.html","",0);
	Menu3_2=new Array("Middle School (7-8)","http://www.mtcps.org/secondary/middleschool/Welcome.shtml","",5,20,138);
		Menu3_2_1=new Array("Home Page","http://www.mtcps.org/secondary/middleschool/Welcome.shtml","",0,20,168);
		Menu3_2_2=new Array("Staff Directories","","",4);
			Menu3_2_2_1=new Array("Administrative","http://www.mtcps.org/secondary/middleschool/administrative/Welcome.shtml","",0,20,120);
			Menu3_2_2_2=new Array("Athletic","http://www.mtcps.org/secondary/highschool/athletic/staff.shtml","",0);
			Menu3_2_2_3=new Array("Counseling","http://www.mtcps.org/secondary/middleschool/counseling/Welcome.shtml","",0);
			Menu3_2_2_4=new Array("Instructional","http://www.mtcps.org/secondary/middleschool/instructional/Welcome.shtml","",0);
		Menu3_2_3=new Array("Athletic Department","","",2);
			Menu3_2_3_1=new Array("Schedules","http://www.mtcps.org/secondary/middleschool/athletic/schedules/Welcome.shtml","",0,20,138);
			Menu3_2_3_2=new Array("Message Board","http://www.mtcps.org/secondary/middleschool/athletic/message_board.shtml","",0);
		Menu3_2_4=new Array("Newsletters","","",1);
			Menu3_2_4_1=new Array("March 2005","http://www.mtcps.org/secondary/middleschool/newsletters/march05.pdf","",0,20,90);
		Menu3_2_5=new Array("Media Center","http://www.mtcps.org/mediacenter","",0);

Menu4=new Array("Elementary","","",5,20,85);
	Menu4_1=new Array("Alexander Macomb (K-6)","http://www.mtcps.org/elementary/macomb/Macomb%20website/index.shtml","",5,20,178);
		Menu4_1_1=new Array("Home Page","http://www.mtcps.org/elementary/macomb/Macomb%20website/index.shtml","",0,20,168);
		Menu4_1_2=new Array("Staff","http://www.mtcps.org/elementary/macomb/Macomb%20website/staffa.shtml","",0);
		Menu4_1_3=new Array("Annual Report 2003-2004","http://www.mtcps.org/elementary/shared_pdfs/Alexander_Macomb_annualreport0304.pdf","",0);
		Menu4_1_4=new Array("Welcome Brochure","http://www.mtcps.org/elementary/shared_pdfs/Alexander_Macomb_Feb_2002.pdf","",0);
		Menu4_1_5=new Array("Media Center","http://www.mtcps.org/mediacenter","",0);
	Menu4_2=new Array("King Academy (K-6)","http://www.mtcps.org/elementary/king/index.shtml","",5);
		Menu4_2_1=new Array("Home Page","http://www.mtcps.org/elementary/king/index.shtml","",0,20,168);
		Menu4_2_2=new Array("Administrative Staff","http://www.mtcps.org/elementary/king/administrativestaff.shtml","",0);
		Menu4_2_3=new Array("Instructional Staff","http://www.mtcps.org/elementary/king/instructionalstaff.shtml","",0);
		Menu4_2_4=new Array("Welcome Brochure","http://www.mtcps.org/elementary/shared_pdfs/King_Academy_Feb_2002.pdf","",0);
		Menu4_2_5=new Array("Media Center","http://www.mtcps.org/mediacenter","",0);
	Menu4_3=new Array("Seminole Academy (K-6)","http://www.mtcps.org/elementary/seminole/index.shtml","",5);
		Menu4_3_1=new Array("Home Page","http://www.mtcps.org/elementary/seminole/index.shtml","",0,20,168);
		Menu4_3_2=new Array("Instructional Staff","http://www.mtcps.org/elementary/seminole/insstaff.shtml","",0);
		Menu4_3_3=new Array("Support Staff","http://www.mtcps.org/elementary/seminole/supstaff.shtml","",0);
		Menu4_3_4=new Array("Welcome Brochure","http://www.mtcps.org/elementary/shared_pdfs/Seminole_Academy_Feb_2002.pdf","",0);
		Menu4_3_5=new Array("Media Center","http://www.mtcps.org/mediacenter","",0);
	Menu4_4=new Array("Washington Academy (K-6)","http://www.mtcps.org/elementary/washington/Welcome.shtml","",5);
		Menu4_4_1=new Array("Home Page","http://www.mtcps.org/elementary/washington/Welcome.shtml","",0,20,168);
		Menu4_4_2=new Array("Administrative Staff","http://www.mtcps.org/elementary/washington/administrative/Welcome.shtml","",0);
		Menu4_4_3=new Array("Instructional Staff","http://www.mtcps.org/elementary/washington/instructional/Welcome.shtml","",0);
		Menu4_4_4=new Array("Welcome Brochure","http://www.mtcps.org/elementary/shared_pdfs/Washington_Academy_Feb_2002.pdf","",0);
		Menu4_4_5=new Array("Media Center","http://www.mtcps.org/mediacenter","",0);
	Menu4_5=new Array("Lincoln Center","http://www.mtcps.org/elementary/lincoln/Welcome.html","",0);

Menu5=new Array("Calendars","http://www.mtcps.org/calendars","",1,20,85);
		Menu5_1=new Array("Click Here For All Calendars","http://www.mtcps.org/calendars","",0,20,175);

Menu6=new Array("Encore","","",3,20,65);
	Menu6_1=new Array("2006-2007 Encore Flyer","http://www.mtcps.org/extended_day_programs/20062007EncoreFlyer.pdf","",0,20,175);
	Menu6_2=new Array("2006-2007 Encore Brochure","http://www.mtcps.org/extended_day_programs/20062007EncoreBrochure.pdf","",0);
	Menu6_3=new Array("2006-2007 Encore Enrollment","http://www.mtcps.org/extended_day_programs/20062007Encore Enrollment.pdf","",0);

Menu7=new Array("Bond Issue 2001","","",1,20,115);
	Menu7_1=new Array("Construction","","",6,20,125);
		Menu7_1_1=new Array("Alexander Macomb","","",1,20,154);
			Menu7_1_1_1=new Array("Construction Photos","http://www.mtcps.org/construction/am/20070129.shtml","",0,20,138);
		Menu7_1_2=new Array("King Academy","","",2);
			Menu7_1_2_1=new Array("Construction Photos","http://www.mtcps.org/construction/ka/20041025.shtml","",0,20,138);
			Menu7_1_2_2=new Array("Construction Movies","http://www.mtcps.org/construction/ka/construction_movies_ka.shtml","",0);
		Menu7_1_3=new Array("Lincoln Center","","",1);
			Menu7_1_3_1=new Array("Construction Photos","http://www.mtcps.org/construction/lin/20051028.shtml","",0,20,138);
		Menu7_1_4=new Array("Secondary Complex","","",2);
			Menu7_1_4_1=new Array("Construction Photos","http://www.mtcps.org/construction/sc/construction_photos.shtml","",0,20,138);
			Menu7_1_4_2=new Array("Construction Movies","http://www.mtcps.org/construction/sc/construction_movies_sc.shtml","",0);
		Menu7_1_5=new Array("Seminole Academy","","",2);
			Menu7_1_5_1=new Array("Construction Photos","http://www.mtcps.org/construction/sa/20041025.shtml","",0,20,138);
			Menu7_1_5_2=new Array("Construction Movies","http://www.mtcps.org/construction/sa/construction_movies_sa.shtml","",0);
		Menu7_1_6=new Array("Washington Academy","","",2);
			Menu7_1_6_1=new Array("Construction Photos","http://www.mtcps.org/construction/wa/20040513.shtml","",0,20,138);
			Menu7_1_6_2=new Array("Construction Movies","http://www.mtcps.org/construction/wa/construction_movies_wa.shtml","",0);		

Menu8=new Array("Resources","","",8,20,93);
	Menu8_1=new Array("Technology","","",5,20,245);
		Menu8_1_1=new Array("Significance of Information Literacy","http://www.mtcps.org/resources/technology/sil.shtml","",0,20,300);
		Menu8_1_2=new Array("Michigan Technology Content Standards","http://www.mtcps.org/resources/technology/mtcs.shtml","",0);
		Menu8_1_3=new Array("Technology Curriculum Standards","http://www.mtcps.org/resources/technology/tcs.shtml","",0);
		Menu8_1_4=new Array("International Society for Technology in Education","http://www.mtcps.org/resources/technology/iste.shtml","",3);
			Menu8_1_4_1=new Array("Students","http://www.mtcps.org/resources/technology/iste/students.shtml","",0,20,95);
			Menu8_1_4_2=new Array("Staff","http://www.mtcps.org/resources/technology/iste/staff.shtml","",0);
			Menu8_1_4_3=new Array("Administrators","http://www.mtcps.org/resources/technology/iste/administrators.shtml","",0);	
                Menu8_1_5=new Array("MI CliMB","http://www.mtcps.org/resources/technology/miclimb.shtml","",0);
	Menu8_2=new Array("Enhancing Curriculum with Technology","","",6);
		Menu8_2_1=new Array("Marco Polo","http://www.mtcps.org/resources/ecwt/mp.shtml","",0,20,200);
		Menu8_2_2=new Array("Intel Teach to the Future","http://www.mtcps.org/resources/ecwt/itttf.shtml","",0);
		Menu8_2_3=new Array("Michigan Teachers Network","http://www.mtcps.org/resources/ecwt/mtn.shtml","",0);
		Menu8_2_4=new Array("Apple Learning Interchange","http://www.mtcps.org/resources/ecwt/ali.shtml","",0);
		Menu8_2_5=new Array("Merit Teach for Tomorrow","http://www.mtcps.org/resources/ecwt/mtft.shtml","",0);
		Menu8_2_6=new Array("Microsoft Educator's Exchange","http://www.mtcps.org/resources/ecwt/mee.shtml","",0);	
	Menu8_3=new Array("Language Arts","","",7);
		Menu8_3_1=new Array("English Grammar Connection","http://www.mtcps.org/resources/la/egc.shtml","",0,20,250);
		Menu8_3_2=new Array("The Prudue Writing Lab","http://www.mtcps.org/resources/la/pwl.shtml","",0);
		Menu8_3_3=new Array("Online Listening Center","http://www.mtcps.org/resources/la/olc.shtml","",0);
		Menu8_3_4=new Array("Interactive Stories","http://www.mtcps.org/resources/la/is.shtml","",0);
		Menu8_3_5=new Array("Guide to Grammar & Writing","http://www.mtcps.org/resources/la/gtgw.shtml","",0);
		Menu8_3_6=new Array("English Language Arts Overviews","http://www.mtcps.org/resources/pdf/ELAOverviews.pdf","",0);
		Menu8_3_7=new Array("English Language Arts Sequence of Study","http://www.mtcps.org/resources/pdf/ELASequence.pdf","",0);
	Menu8_4=new Array("Math","","",10);
		Menu8_4_1=new Array("High School Hub - Mathematics","http://www.mtcps.org/resources/math/hshm.shtml","",0,20,210);
		Menu8_4_2=new Array("The Math Forum","http://www.mtcps.org/resources/math/tmf.shtml","",0);
		Menu8_4_3=new Array("Math Night Resources","http://www.mtcps.org/resources/math/mnr.shtml","",0);
		Menu8_4_4=new Array("Math Worksheets","http://www.mtcps.org/resources/math/mw.shtml","",0);
		Menu8_4_5=new Array("PBS Mathline - Teacher Resources","http://www.mtcps.org/resources/math/pbsmtr.shtml","",0);
		Menu8_4_6=new Array("Everyday Math for Parents","http://www.mtcps.org/resources/math/emfp.shtml","",0);
		Menu8_4_7=new Array("Family Math Games","http://www.mtcps.org/resources/math/fmg.shtml","",0);
		Menu8_4_8=new Array("More Everyday Math","http://www.mtcps.org/resources/math/mem.shtml","",0);
		Menu8_4_9=new Array("Math Overviews","http://www.mtcps.org/resources/pdf/MathOverviews.pdf","",0);
		Menu8_4_10=new Array("Math Sequence of Study","http://www.mtcps.org/resources/pdf/MathSequence.pdf","",0);
	Menu8_5=new Array("Social Studies","","",6);
		Menu8_5_1=new Array("Historical Collections","http://www.mtcps.org/resources/ss/hc.shtml","",0,20,200);
		Menu8_5_2=new Array("Social Studies for Kids","http://www.mtcps.org/resources/ss/ssfk.shtml","",0);
		Menu8_5_3=new Array("National Archives","http://www.mtcps.org/resources/ss/na.shtml","",0);
		Menu8_5_4=new Array("Altapedia","http://www.mtcps.org/resources/ss/a.shtml","",0);
		Menu8_5_5=new Array("Social Studies Overviews","http://www.mtcps.org/resources/pdf/SSOverviews.pdf","",0);
		Menu8_5_6=new Array("Social Studies Sequence of Study","http://www.mtcps.org/resources/pdf/SSSequence.pdf","",0);
	Menu8_6=new Array("Science","","",5);
		Menu8_6_1=new Array("Internet Public Library","http://www.mtcps.org/resources/science/ipl.shtml","",0,20,215);
		Menu8_6_2=new Array("Cornell Theory Center","http://www.mtcps.org/resources/science/ctc.shtml","",0);
		Menu8_6_3=new Array("Eisenhower National Clearing House","http://www.mtcps.org/resources/science/ench.shtml","",0);
		Menu8_6_4=new Array("Science Overviews","http://www.mtcps.org/resources/pdf/ScienceOverviews.pdf","",0);
		Menu8_6_5=new Array("Science Sequence of Study","http://www.mtcps.org/resources/pdf/ScienceSequence.pdf","",0);
	Menu8_7=new Array("General Resources","","",1);
		Menu8_7_1=new Array("Wikipedia Encyclopedia","http://www.mtcps.org/resources/general/we.shtml","",0,20,150);
	Menu8_8=new Array("Elementary Safety Resources","","",2);
		Menu8_8_1=new Array("Internet Safety","http://www.mtcps.org/resources/elementary/is.shtml","",0,20,95);
		Menu8_8_2=new Array("Web Aware","http://www.mtcps.org/resources/elementary/wa.shtml","",0);
