<!--
  var msg = '</center>\n';
  msg = msg + '<p>New schedules were uploaded on December 3. We will be\n';
  msg = msg + 'updating <b>every Sunday</b> with four weeks worth of information.\n';
  msg = msg + '<p><table width=600 Cellpadding=0 Cellspacing=0 Border=0 Bgcolor=#ffffff>\n';
  msg = msg + '<FORM METHOD="GET" ACTION="http://www.tv-now.com/cgi-bin/stars.pl" Target="_top">\n';
  msg = msg + '<tr>\n';
  msg = msg + '<td></TD>\n';
  msg = msg + '<TD align=center><INPUT TYPE="text" NAME="ACTOR" VALUE="" SIZE=25 MAXLENGTH=40>\n';
  msg = msg + '</td>\n';
  msg = msg + '<td> &#8592; Key another name and hit Enter to search TV schedules.</td>\n';
  msg = msg + '</tr>\n';
  msg = msg + '</Form>\n';
  msg = msg + '</table>\n';
  msg = msg + '<p>NOTE: The hardest tube appearances to keep up with are the Talk\n';
  msg = msg + 'Shows. Visit <A Href="http://www.interbridge.com/lineups.html" target="_blank"><b>Interbridge</b></a>\n';
  msg = msg + 'to see if your star is on one of the main talkfests this week.\n';
  msg = msg + 'If we have listed something incorrectly or are missing\n';
  msg = msg + 'other shows that feature the star,\n';
  msg = msg + '<a href="http://www.tv-now.com/fixerr.htm" target="_blank">Click Here</a> to\n';
  msg = msg + 'alert TVNow about the mistake.\n';
  msg = msg + '<BR><br><center>\n';
  msg = msg + '<TABLE width="600" border=0><TR>\n';
  msg = msg + '<TD align=center valign=center width="200">\n';
  msg = msg + '<a href="http://www.tv-now.com/mysdvds/index.html" target="_top"><IMG SRC="http://www.tv-now.com/js/mysbut2.gif" title="Classic Mystery Movies" width="121" height="53" border=1></a>\n';
  msg = msg + '</TD>\n';
  msg = msg + '<TD align=center valign=center width="200">\n';
  msg = msg + '<A Href="http://www.thehungersite.com" target="_blank"><IMG src="http://www.tv-now.com/js/hunger2.gif" title="Click to feed the hungry" width="121" height="53" border=0></A>\n';
  msg = msg + '</TD>\n';
  msg = msg + '<TD align=center valign=center width="200">\n';
  msg = msg + '<a href="http://www.tv-now.com/wesdvds/index.html" target="_top"><IMG SRC="http://www.tv-now.com/js/wesbut2.gif" title="Classic Western Movies" width="121" height="53" border=1></a>\n';
  msg = msg + '</TD>\n';
  msg = msg + '</TR>\n';
  msg = msg + '</TABLE>\n';
  msg = msg + '</center><BR>\n';
  document.write (msg);
// -->
