//----------DHTML Menu Created using AllWebMenus PRO ver 4.2-#630---------------
//C:\Documents and Settings\Jane Hunter\My Documents\Publish\jews on first\jofmenu.awm
var awmMenuName='jofmenu';
var awmLibraryBuild=630;
var awmLibraryPath='/awmdata';
var awmImagesPath='/awmdata';
var awmSupported=(navigator.appName + navigator.appVersion.substring(0,1)=="Netscape5" || document.all || document.layers || navigator.userAgent.indexOf('Opera')>-1 || navigator.userAgent.indexOf('Konqueror')>-1)?1:0;
if (awmAltUrl!='' && !awmSupported) window.location.replace(awmAltUrl);
if (awmSupported){
var nua=navigator.userAgent,scriptNo=(nua.indexOf('Safari')>-1)?7:(nua.indexOf('Gecko')>-1)?2:((document.layers)?3:((nua.indexOf('Opera')>-1)?4:((nua.indexOf('Mac')>-1)?5:1)));
var mpi=document.location,xt="";
var mpa=mpi.protocol+"//"+mpi.host;
var mpi=mpi.protocol+"//"+mpi.host+mpi.pathname;
while (mpi.search(/\\/)>-1) mpi=mpi.replace("\\","/");
mpi=mpi.substring(0,mpi.lastIndexOf("/")+1);
var e=document.getElementsByTagName("SCRIPT");
for (var i=0;i<e.length;i++){if (e[i].src){if (e[i].src.indexOf(awmMenuName+".js")!=-1){xt=e[i].src.split("/");if (xt[xt.length-1]==awmMenuName+".js"){xt=e[i].src.substring(0,e[i].src.length-awmMenuName.length-3);if (e[i].src.indexOf("://")!=-1){mpi=xt;}else{if(xt.substring(0,1)=="/")mpi=mpa+xt; else mpi+=xt;}}}}}
var awmMenuPath=mpi.substring(0,mpi.length-1);
while (awmMenuPath.search("'")>-1) {awmMenuPath=awmMenuPath.replace("'","&#39;");}
while (awmMenuPath.search(/\/\.\//)>-1) {awmMenuPath=awmMenuPath.replace("/./","/");}
document.write("<SCRIPT SRC='"+awmMenuPath+awmLibraryPath+"/awmlib"+scriptNo+".js'><\/SCRIPT>");
var n=null;
awmzindex=88;
}

var awmSubmenusFrame='';
var awmSubmenusFrameOffset;
var awmOptimize=0;
var awmUseTrs=0;
var awmSepr=["0","","","","90","#FFFFFF","","3","90","#FFFFFF","","1"];
function awmBuildMenu(){
if (awmSupported){
awmImagesColl=["jewsonfirstpanel.jpg",165,1152,"bullets_13.gif",10,10];
awmCreateCSS(0,1,0,n,n,0,n,n,'none',0,'#000000',0,0);
awmCreateCSS(1,2,1,'#6C6C8F',n,n,'bold 12px Verdana, Arial, Helvetica, sans-serif',n,'none',0,'#000000','4px 0px 4px 1',1);
awmCreateCSS(0,2,1,'#6C6C8F','#E5DFF0',n,'bold 11px Verdana, Arial, Helvetica, sans-serif',n,'solid',1,'#FFFFFF','4px 4px 4px 4',1);
awmCreateCSS(0,2,1,'#6C6C8F','#FFFFFF',n,'bold 11px Verdana, Arial, Helvetica, sans-serif','underline','none',0,'#000000','4px 4px 4px 4',1);
awmCreateCSS(0,1,0,n,'#6C6C8F',n,n,n,'outset',3,'#E5DFF0',0,0);
awmCreateCSS(1,2,0,'#FFFFFF','#6C6C8F',n,'bold 11px Verdana, Arial, Helvetica, sans-serif',n,'none',0,'#000000','4px 2px 4px 2',1);
awmCreateCSS(0,2,0,'#E5DFF0','#6C6C8F',n,'bold 11px Verdana, Arial, Helvetica, sans-serif',n,'solid',1,'#FFFFFF','4px 4px 4px 4',1);
awmCreateCSS(0,2,0,'#6C6C8F','#E5DFF0',n,'bold 11px Verdana, Arial, Helvetica, sans-serif','underline','none',0,'#000000','4px 4px 4px 4',1);
awmCreateCSS(1,2,0,'#FFFFFF','#6C6C8F',n,'11px Verdana, Arial, Helvetica, sans-serif',n,'none',0,'#000000','4px 2px 4px 2',1);
var s0=awmCreateMenu(0,0,0,0,1,0,0,0,0,0,17,0,0,0,0,1,0,n,n,85,1,0,0,17,160);
it=s0.addItemWithImages(1,2,3,"HOME","  HOME  ","  HOME  ","",n,n,n,3,3,3,n,n,n,"index.html",n,n,n,"index.html",n,0,0,2,n,n,n,n,n,n,0,0,0,1);
it=s0.addItemWithImages(1,2,3,"ATTACKS ON<br> CHURCH-STATE <br>SEPARATION","  ATTACKS ON  <br>   CHURCH-STATE   <br>  SEPARATION  ","  ATTACKS ON  <br>   CHURCH-STATE   <br>  SEPARATION  ","",n,n,n,3,3,3,1,n,n,"separation.php",n,n,n,"separation.php",n,0,0,2,n,n,n,n,n,n,0,0,0,1);
var s1=it.addSubmenu(0,0,-75,0,0,0,0,4,0,1,0,n,n,95,0,2,380);
it=s1.addItem(5,6,7,"  ATTACKS ON CHURCH-STATE SEPARATION  ",n,n,"","separation.php",n,n,n,"separation.php",n,0,0,2,2);
it=s1.addItem(8,6,7,"  Coercion at the US Air Force Academy  ",n,n,"","airacademy.html",n,n,n,"airacademy.html",n,0,0,2,0);
it=s1.addItem(8,6,7,"  Christocrats build power in all military branches  ",n,n,"","military.html",n,n,n,"military.html",n,0,0,2,0);
it=s1.addItem(8,6,7,"  Court-stripping and legislating against the First Amendment  ",n,n,"","courtstrip.php",n,n,n,"courtstrip.php",n,0,0,2,0);
it=s1.addItem(8,6,7,"  \"Faith-based\" diversion of public funds  ",n,n,"","faithbased.php",n,n,n,"faithbased.php",n,0,0,2,0);
it=s1.addItem(8,6,7,"  Religious displays on public property  ",n,n,"","sep_displays.php",n,n,n,"sep_displays.php",n,0,0,2,0);
it=s1.addItem(8,6,7,"  Government-sponsored sectarian prayer  ",n,n,"","sep_prayer.php",n,n,n,"sep_prayer.php",n,0,0,2,0);
it=s1.addItem(8,6,7,"  Indiana legislators press for prayer  ",n,n,"","indiana.html",n,n,n,"indiana.html",n,0,0,2,0);
it=s1.addItem(8,6,7,"  Government-funded right-wing Christian evangelical prison programs  ",n,n,"","sep_prisons.php",n,n,n,"sep_prisons.php",n,0,0,2,0);
it=s1.addItem(8,6,7,"  How Jews see it  ",n,n,"","howjewsseesep.html",n,n,n,"howjewsseesep.html",n,0,0,2,0);
it=s0.addItemWithImages(1,2,3,"ATTACKS ON<BR>GAY & LESBIAN<BR>CIVIL RIGHTS","  ATTACKS ON<BR>GAY & LESBIAN<BR>CIVIL RIGHTS  ","  ATTACKS ON<BR>GAY & LESBIAN<BR>CIVIL RIGHTS  ","",n,n,n,3,3,3,1,n,n,"gayrights.php",n,n,n,"gayrights.php",n,0,0,2,n,n,n,n,n,n,0,0,0,1);
var s1=it.addSubmenu(0,0,-75,0,0,0,0,4,0,1,0,n,n,95,0,1,380);
it=s1.addItem(5,6,7,"  ATTACKS ON GAY & LESBIAN CIVIL RIGHTS  ",n,n,"","gayrights.php",n,n,n,"gayrights.php",n,0,0,2,2);
it=s1.addItem(8,6,7,"  Attacking  partner rights and benefits  ",n,n,"","partner.html",n,n,n,"partner.html",n,0,0,2,0);
it=s1.addItem(8,6,7,"  The marriage amendment juggernaut  ",n,n,"","marriage.php",n,n,n,"marriage.php",n,0,0,2,0);
it=s1.addItem(8,6,7,"  Rollback on adoption  ",n,n,"","adoption.html",n,n,n,"adoption.html",n,0,0,2,0);
it=s1.addItem(8,6,7,"  The US military's backward gay & lesbian policies  ",n,n,"","gr_military.php",n,n,n,"gr_military.php",n,0,0,2,0);
it=s1.addItem(8,6,7,"  Preaching hatred of homosexuals  ",n,n,"","hate.html",n,n,n,"hate.html",n,0,0,2,0);
it=s1.addItem(8,6,7,"  The \"conversion therapy\" offensive  ",n,n,"","exgay.php",n,n,n,"exgay.php",n,0,0,2,0);
it=s1.addItem(8,6,7,"  How Jews see it  ",n,n,"","howjewsseegr.html",n,n,n,"howjewsseegr.html",n,0,0,2,0);
it=s0.addItemWithImages(1,2,3,"ATTACKS ON<BR>PUBLIC<BR>EDUCATION","  ATTACKS ON<BR>PUBLIC<BR>EDUCATION  ","  ATTACKS ON<BR>PUBLIC<BR>EDUCATION  ","",n,n,n,3,3,3,1,n,n,"public.html",n,n,n,"public.html",n,0,0,2,n,n,n,n,n,n,0,0,0,1);
var s1=it.addSubmenu(0,0,-75,0,0,0,0,4,0,1,0,n,n,95,0,3,380);
it=s1.addItem(5,6,7,"  ATTACKS ON PUBLIC EDUCATION  ",n,n,"","public.html",n,n,n,"public.html",n,0,0,2,2);
it=s1.addItem(8,6,7,"  Vouchers and homeschooling  ",n,n,"","schoolvouchers.php",n,n,n,"schoolvouchers.php",n,0,0,2,0);
it=s1.addItem(8,6,7,"  School prayer and subsidies for religious schools  ",n,n,"","schoolprayer.php",n,n,n,"schoolprayer.php",n,0,0,2,0);
it=s1.addItem(8,6,7,"  Religious clubs and outsiders on campus  ",n,n,"","schoolclubs.php",n,n,n,"schoolclubs.php",n,0,0,2,0);
it=s1.addItem(8,6,7,"  Bible study in public schools  ",n,n,"","bibleclass.php",n,n,n,"bibleclass.php",n,0,0,2,0);
it=s1.addItem(8,6,7,"  Religious plays and displays  ",n,n,"","schooldisplays.php",n,n,n,"schooldisplays.php",n,0,0,2,0);
it=s1.addItem(8,6,7,"  Creationism, \"intelligent design\"  ",n,n,"","creationism_genl.html",n,n,n,"creationism_genl.html",n,0,0,2,0);
it=s1.addItem(8,6,7,"  Intolerance in Delaware school systems  ",n,n,"","delaware_schools.php",n,n,n,"delaware_schools.php",n,0,0,2,0);
it=s1.addItem(8,6,7,"  \"ID\" vanquished in Dover, Penn.  ",n,n,"","dover.html",n,n,n,"dover.html",n,0,0,2,0);
it=s1.addItem(8,6,7,"  Kansas votes to teach \"intelligent design\"  ",n,n,"","kansas.html",n,n,n,"kansas.html",n,0,0,2,0);
it=s1.addItem(8,6,7,"  Christian school sues UC on admission standards  ",n,n,"","ucadmissions.html",n,n,n,"ucadmissions.html",n,0,0,2,0);
it=s1.addItem(8,6,7,"  How Jews see it  ",n,n,"","howjewsseepub.html",n,n,n,"howjewsseepub.html",n,0,0,2,0);
it=s0.addItemWithImages(1,2,3,"CURTAILING<br>OPTIONS FOR<br>REPRODUCTIVE<br>& SEXUAL<br>HEALTH","  CURTAILING  <br>  OPTIONS FOR  <br>  REPRODUCTIVE  <br>  & SEXUAL  <br>  HEALTH  ","  CURTAILING  <br>  OPTIONS FOR  <br>  REPRODUCTIVE  <br>  & SEXUAL  <br>  HEALTH  ","",n,n,n,3,3,3,1,n,n,"reprorights.html",n,n,n,"reprorights.html",n,0,0,2,n,n,n,n,n,n,0,0,0,1);
var s1=it.addSubmenu(0,0,-75,0,0,0,0,4,0,1,0,n,n,95,0,4,380);
it=s1.addItem(5,6,7,"  CURTAILING OPTIONS FOR REPRODUCTIVE HEALTH  ",n,n,"","reprorights.html",n,n,n,"reprorights.html",n,0,0,2,2);
it=s1.addItem(8,6,7,"  Religious right's campaign against contraceptives  ",n,n,"","contraceptives.html",n,n,n,"contraceptives.html",n,0,0,2,0);
it=s1.addItem(8,6,7,"  Fighting a woman's right to choose  ",n,n,"","choice.html",n,n,n,"choice.html",n,0,0,2,0);
it=s1.addItem(8,6,7,"  South Dakota's harsh law against abortion  ",n,n,"","southdakota.html",n,n,n,"southdakota.html",n,0,0,2,0);
it=s1.addItem(8,6,7,"  Religious right fights access to Plan B  ",n,n,"","planb.html",n,n,n,"planb.html",n,0,0,2,0);
it=s1.addItem(8,6,7,"  Pharmacist refusal  ",n,n,"","pharmacists.php",n,n,n,"pharmacists.php",n,0,0,2,0);
it=s1.addItem(8,6,7,"  Replacing sex education with religious dogma  ",n,n,"","sex-ed.html",n,n,n,"sex-ed.html",n,0,0,2,0);
it=s1.addItem(8,6,7,"  Battle over sex education in Maryland suburb  ",n,n,"","maryland.html",n,n,n,"maryland.html",n,0,0,2,0);
it=s1.addItem(8,6,7,"  Congressional religious right attacks Shelby Knox documentary  ",n,n,"","shelbyknox.html",n,n,n,"shelbyknox.html",n,0,0,2,0);
it=s1.addItem(8,6,7,"  Limiting foreign aid recipients' access to contraceptives  ",n,n,"","overseasrepro.html",n,n,n,"overseasrepro.html",n,0,0,2,0);
it=s1.addItem(8,6,7,"  How Jews see it  ",n,n,"","howjewsseerepro.html",n,n,n,"howjewsseerepro.html",n,0,0,2,0);
it=s0.addItemWithImages(1,2,3,"INTIMIDATION<br>OF JUDGES","  INTIMIDATION  <br>  OF JUDGES  ","  INTIMIDATION  <br>  OF JUDGES  ","",n,n,n,3,3,3,n,n,n,"judiciary.html",n,n,n,"judiciary.html",n,0,0,2,n,n,n,n,n,n,0,0,0,1);
it=s0.addItemWithImages(1,2,3,"OPPOSING<BR>STEM CELL<BR>RESEARCH","  OPPOSING<BR>STEM CELL<BR>RESEARCH  ","  OPPOSING<BR>STEM CELL<BR>RESEARCH  ","",n,n,n,3,3,3,n,n,n,"stemcell.php",n,n,n,"stemcell.php",n,0,0,2,n,n,n,n,n,n,0,0,0,1);
it=s0.addItemWithImages(1,2,3,"\"INTELLIGENT<br>DESIGN\"<br>(CREATIONISM)","  \"INTELLIGENT  <br>  DESIGN\"  <br>  CREATIONISM  ","  \"INTELLIGENT  <br>  DESIGN\"  <br>  CREATIONISM  ","",n,n,n,3,3,3,1,n,n,"creationism_genl.html",n,n,n,"creationism_genl.html",n,0,0,2,n,n,n,n,n,n,0,0,0,1);
var s1=it.addSubmenu(0,0,-75,0,0,0,0,4,0,1,0,n,n,95,0,5,380);
it=s1.addItem(5,6,7,"  \"INTELLIGENT DESIGN\" (CREATIONISM)  ",n,n,"","creationism_genl.html",n,n,n,"creationism_genl.html",n,0,0,2,2);
it=s1.addItem(8,6,7,"  Kansas votes to teach \"intelligent design\"  ",n,n,"","kansas.html",n,n,n,"kansas.html",n,0,0,2,0);
it=s1.addItem(8,6,7,"  \"ID\" vanquished in Dover, Penn.  ",n,n,"","dover.html",n,n,n,"dover.html",n,0,0,2,0);
it=s1.addItem(8,6,7,"  How Jews see it  ",n,n,"","howjewsseepub.html",n,n,n,"howjewsseepub.html",n,0,0,2,0);
it=s1.addItem(8,6,7,"  Noah's Park  ",n,n,"","noahspark.html",n,n,n,"noahspark.html",n,0,0,2,0);
it=s0.addItemWithImages(1,2,3,"EVANGELIZING<BR>THE JEWS","  EVANGELIZING<BR>THE JEWS  ","  EVANGELIZING<BR>THE JEWS  ","",n,n,n,3,3,3,n,n,n,"evangelizing.php",n,n,n,"evangelizing.php",n,0,0,2,n,n,n,n,n,n,0,0,0,1);
it=s0.addItemWithImages(1,2,3,"WORKING FOR<br>THE RETURN OF<br>PATRIARCHY","  WORKING FOR  <br>  THE RETURN OF  <br>  PATRIARCHY  ","  WORKING FOR  <br>  THE RETURN OF  <br>  PATRIARCHY  ","",n,n,n,3,3,3,n,n,n,"patriarchy.php",n,n,n,"patriarchy.php",n,0,0,2,n,n,n,n,n,n,0,0,0,1);
it=s0.addItemWithImages(1,2,3,"INTRUDING ON<BR>FAMILY PRIVACY","  INTRUDING ON<BR>FAMILY PRIVACY  ","  INTRUDING ON<BR>FAMILY PRIVACY  ","",n,n,n,3,3,3,1,n,n,"family.html",n,n,n,"family.html",n,0,0,2,n,n,n,n,n,n,0,0,0,1);
var s1=it.addSubmenu(0,0,-75,0,0,0,0,4,0,1,0,n,n,95,0,10,380);
it=s1.addItem(5,6,7,"  INTRUDING ON FAMILY PRIVACY  ",n,n,"","family.html",n,n,n,"family.html",n,0,0,2,2);
it=s1.addItem(8,6,7,"  How Jews see it  ",n,n,"","howjewsseefam.html",n,n,n,"howjewsseefam.html",n,0,0,2,0);
it=s0.addItemWithImages(1,2,3,"INTERVENTION<br>ABROAD","  INTERVENTION  <br>  ABROAD  ","  INTERVENTION  <br>  ABROAD  ","",n,n,n,3,3,3,1,n,n,"foreignpol.html",n,n,n,"foreignpol.html",n,0,0,2,n,n,n,n,n,n,0,0,0,1);
var s1=it.addSubmenu(0,0,-75,0,0,0,0,4,0,1,0,n,n,95,0,11,380);
it=s1.addItem(5,6,7,"  CHRISTOCRATS FAVOR INTERVENTION ABROAD  ",n,n,"","foreignpol.html",n,n,n,"foreignpol.html",n,0,0,2,2);
it=s1.addItem(8,6,7,"  Christian Zionists  ",n,n,"","christian_zionists.php",n,n,n,"christian_zionists.php",n,0,0,2,0);
it=s1.addItem(8,6,7,"  Limiting foreign aid recipients' access to contraceptives  ",n,n,"","overseasrepro.html",n,n,n,"overseasrepro.html",n,0,0,2,0);
it=s0.addItemWithImages(1,2,3,"CHRISTIAN<br>ZIONISTS","  CHRISTIAN  <br>  ZIONISTS  ","  CHRISTIAN  <br>  ZIONISTS  ","",n,n,n,3,3,3,n,n,n,"christian_zionists.php",n,n,n,"christian_zionists.php",n,0,0,2,n,n,n,n,n,n,0,0,0,1);
it=s0.addItemWithImages(1,2,3,"CULTURAL<br>INTIMIDATION","  CULTURAL  <br>  INTIMIDATION  ","  CULTURAL  <br>  INTIMIDATION  ","",n,n,n,3,3,3,1,n,n,"cultural.html",n,n,n,"cultural.html",n,0,0,2,n,n,n,n,n,n,0,0,0,1);
var s1=it.addSubmenu(0,0,-75,0,0,0,0,4,0,1,0,n,n,95,0,6,380);
it=s1.addItem(5,6,7,"  CULTURAL INTIMIDATION  ",n,n,"","cultural.html",n,n,n,"cultural.html",n,0,0,2,2);
it=s1.addItem(8,6,7,"  Religious bullying  ",n,n,"","bullying.php",n,n,n,"bullying.php",n,0,0,2,0);
it=s1.addItem(8,6,7,"  Bullying the media  ",n,n,"","cultural_media.php",n,n,n,"cultural_media.php",n,0,0,2,0);
it=s1.addItem(8,6,7,"  At the movies  ",n,n,"","at_the_movies.php",n,n,n,"at_the_movies.php",n,0,0,2,0);
it=s1.addItem(8,6,7,"  The \"war\" over Christmas   ",n,n,"","xmaswar.html",n,n,n,"xmaswar.html",n,0,0,2,0);
it=s1.addItem(8,6,7,"  How Jews see it  ",n,n,"","howjewsseecul.html",n,n,n,"howjewsseecul.html",n,0,0,2,0);
it=s0.addItemWithImages(1,2,3,"DOMINIONISM","  DOMINIONISM  ","  DOMINIONISM  ","",n,n,n,3,3,3,1,n,n,"dominionism.html",n,n,n,"dominionism.html",n,0,0,2,n,n,n,n,n,n,0,0,0,1);
var s1=it.addSubmenu(0,0,-75,0,0,0,0,4,0,1,0,n,n,95,0,7,380);
it=s1.addItem(5,6,7,"  DOMINIONISM  ",n,n,"","dominionism.html",n,n,n,"dominionism.html",n,0,0,2,2);
it=s1.addItem(8,6,7,"  Ohio Patriot Pastors Parsley and Johnson  ",n,n,"","parsley.html",n,n,n,"parsley.html",n,0,0,2,0);
it=s1.addItem(8,6,7,"  Roy Moore  ",n,n,"","roymoore.html",n,n,n,"roymoore.html",n,0,0,2,0);
it=s1.addItem(8,6,7,"  Christian Exodus  ",n,n,"","exodus.html",n,n,n,"exodus.html",n,0,0,2,0);
it=s1.addItem(8,6,7,"  How Jews see it  ",n,n,"","howjewsseedom.html",n,n,n,"howjewsseedom.html",n,0,0,2,0);
it=s0.addItemWithImages(1,2,3,"BACKGROUND<br>& ANALYSIS","  BACKGROUND  <br>  & ANALYSIS  ","  BACKGROUND  <br>  & ANALYSIS  ","",n,n,n,3,3,3,1,n,n,"background.html",n,n,n,"background.html",n,0,0,2,n,n,n,n,n,n,0,0,0,1);
var s1=it.addSubmenu(0,0,-75,0,0,0,0,4,0,1,0,n,n,95,0,8,380);
it=s1.addItem(5,6,7,"  BACKGROUND & ANALYSIS  ",n,n,"","background.html",n,n,n,"background.html",n,0,0,2,0);
it=s1.addItem(8,6,7,"  How Jews see it  ",n,n,"","howjewsseeback.html",n,n,n,"howjewsseeback.html",n,0,0,2,0);
it=s0.addItemWithImages(1,2,3,"REVISING<BR>HISTORY","  REVISING<BR>HISTORY  ","  REVISING<BR>HISTORY  ","",n,n,n,3,3,3,n,n,n,"history.php",n,n,n,"history.php",n,0,0,2,n,n,n,n,n,n,0,0,0,1);
it=s0.addItemWithImages(1,2,3,"BOOKS","  BOOKS  ","  BOOKS  ","",n,n,n,3,3,3,n,n,n,"books.php",n,n,n,"books.php",n,0,0,2,n,n,n,n,n,n,0,0,0,1);
it=s0.addItemWithImages(1,2,3,"CURRENT NEWS","  CURRENT NEWS  ","  CURRENT NEWS  ","",n,n,n,3,3,3,n,n,n,"currentnews.html",n,n,n,"currentnews.html",n,0,0,2,n,n,n,n,n,n,0,0,0,1);
it=s0.addItemWithImages(1,2,3,"ORGANIZING<br>TO OPPOSE<br>THEOCRACY","  ORGANIZING  <br>  TO OPPOSE  <br>  THEOCRACY  ","  ORGANIZING  <br>  TO OPPOSE  <br>  THEOCRACY  ","",n,n,n,3,3,3,1,n,n,"organizing.html",n,n,n,"organizing.html",n,0,0,2,n,n,n,n,n,n,0,0,0,1);
var s1=it.addSubmenu(0,0,-75,0,0,0,0,4,0,1,0,n,n,95,0,9,380);
it=s1.addItem(5,6,7,"  ORGANIZING TO OPPOSE THEOCRACY  ",n,n,"","organizing.html",n,n,n,"organizing.html",n,0,0,2,2);
it=s1.addItem(8,6,7,"  Battle over sex education in Maryland suburb  ",n,n,"","maryland.html",n,n,n,"maryland.html",n,0,0,2,0);
it=s1.addItem(8,6,7,"  Get involved!  ",n,n,"","getinvolved.html",n,n,n,"getinvolved.html",n,0,0,2,0);
it=s0.addItemWithImages(1,2,3,"YOUR STORIES","  YOUR STORIES  ","  YOUR STORIES  ","",n,n,n,3,3,3,n,n,n,"ourstories.html",n,n,n,"ourstories.html",n,0,0,2,n,n,n,n,n,n,0,0,0,1);
it=s0.addItemWithImages(1,2,3,"GET INVOLVED","  GET INVOLVED  ","  GET INVOLVED  ","",n,n,n,3,3,3,n,n,n,"getinvolved.html",n,n,n,"getinvolved.html",n,0,0,2,n,n,n,n,n,n,0,0,0,1);
it=s0.addItemWithImages(1,2,3,"ABOUT US","  ABOUT US  ","  ABOUT US  ","",n,n,n,3,3,3,n,n,n,"about.html",n,n,n,"about.html",n,0,0,2,n,n,n,n,n,n,0,0,0,1);
it=s0.addItemWithImages(1,2,3,"LINKS WE LIKE","  LINKS WE LIKE  ","  LINKS WE LIKE  ","",n,n,n,3,3,3,n,n,n,"links.html",n,n,n,"links.html",n,0,0,2,n,n,n,n,n,n,0,0,0,1);
it=s0.addItemWithImages(1,2,3,"Please DONATE to<br><i>JewsOnFirst.org","  Please DONATE to  <br>  <i>JewsOnFirst.org  ","  Please DONATE to  <br>  <i>JewsOnFirst.org  ","",n,n,n,3,3,3,n,n,n,"https://secure.democracyinaction.org/dia/organizations/shortstop/shop/custom.jsp?donate_page_KEY=1115",n,n,n,"https://secure.democracyinaction.org/dia/organizations/shortstop/shop/custom.jsp?donate_page_KEY=1115",n,0,0,2,n,n,n,n,n,n,0,0,0,1);
it=s0.addItemWithImages(1,2,3,"CONTACT US","  CONTACT US  ","  CONTACT US  ","",n,n,n,3,3,3,n,n,n,"http://www.democracyinaction.org/dia/organizationsORG/shortstop/signUp.jsp?key=1264",n,n,n,"http://www.democracyinaction.org/dia/organizationsORG/shortstop/signUp.jsp?key=1264",n,0,0,2,n,n,n,n,n,n,0,0,0,1);
s0.pm.buildMenu();
}}
