document.write('		<div class="rightBox" style="margin-top: 12px;">');
document.write('			<img src="/images/righthead_bestsellers.gif" alt="Bestsellers" width="231" height="40" border="0"');
document.write('			/><div class="rightBoxInner">');
document.write('				<div style="width: 202px; float: left; margin-left: 4px; padding: 0px 14px 0px 0px; display: inline; vertical-align: top;">');
document.write('					<!--[if IE 5.5000]>');
document.write('						<img src="/images/blank.gif" alt="" width="202" height="1" border="0" />');
document.write('					<![endif]-->');
document.write('					<p style="margin-top: 0px; padding-top: 0px; ">');
document.write('						What are Canadians reading right now? Browse national bestseller lists to find out about books that are selling.');
document.write('					</p>');
document.write('				</div>');
document.write('				<div style="width: 204px; float: left; margin-left: 2px; padding: 10px 14px 6px 0px; display: inline;">');
document.write('					<!--[if IE 5.5000]>');
document.write('						<img src="/images/blank.gif" alt="" width="202" height="1" border="0" />');
document.write('					<![endif]-->');
document.write('					<div style="background-color: #635C56; margin-top: 4px;" class="linkButton">');
document.write('						<div class="tight"><img src="/images/mini_chevron_right.gif" alt="" width="6" height="6" border="0" style="padding: 0px 4px 0px 0px; margin: 4px 0px 0px 0px" /></div>');
document.write('						<!--TODO: link-->');
document.write('						<div class="tight"><a href="/category/best_all/index.pperl" class="linkWhite Small" style="text-decoration: none;">View All Bestsellers</a></div>');
document.write('					</div>');
document.write('				</div>');
document.write('			</div>');
document.write('		</div><!--rightBox-->');
document.write('		<!--bottom box border-->');
document.write('		<div class="rightBox" style="background: none;"><img');
document.write('			src="/images/newsletter_base.gif" alt="" width="231" height="10" border="0" />');
document.write('		</div><!--bottom box border-->');