document.write('		<div class="rightBox" style="margin-top: 12px;">');
document.write('			<img src="/images/righthead_newsletter.gif" alt="Newsletter" width="231" height="30" border="0"');
document.write('			/><div style="width: 202px; padding-left: 10px;">');
document.write('				<div style="width: 219px; float: left; display: inline; margin-left: 1px; padding-top: 0px; vertical-align: top; border-right: 1px solid #b2b2b2;">');
document.write('					<!--[if IE 5.5000]>');
document.write('						<img src="/images/blank.gif" alt="" width="219" height="0" />');
document.write('					<![endif]-->');
document.write('					<p class="Small">');
document.write('						Be the first to learn about new releases, contests and more.');
document.write('					</p>');
document.write('				</div>');
document.write('				<div style="width: 204px; float: left; display: inline; margin-left: 2px; padding: 0px 14px 6px 0px; border-right: 1px solid #b2b2b2; display: inline;">');
document.write('					<!--[if IE 5.5000]>');
document.write('						<img src="/images/blank.gif" alt="" width="204" height="0" />');
document.write('					<![endif]-->');
document.write('					<div style="background-color: #635C56;" class="linkButton">');
document.write('						<div class="tight"><img src="/images/mini_chevron_right.gif" alt="" width="6" height="6" border="0" style="padding: 0px 4px 0px 0px; margin: 4px 0px 0px 0px" /></div>');
document.write('						<!--TODO: link-->');
document.write('						<div class="tight"><a href="/news/signup.html" class="linkWhite" style="text-decoration: none;">More Info</a></div>');
document.write('					</div>');
document.write('				</div>');
document.write('				<!--TODO: complete form method, action, name and id attributes as necessary-->');
document.write('				<form action="http://prefctr.ddc.dartmail.net/randomhouse/randomhouse_miniform.asp" method="post" name="searchForm2" id="searchForm2"><input type="hidden" name="Update" value="0"><input type="hidden" name="path" value="news"><input type="hidden" name="domain" value="http://www.randomhouse.ca/"><input type="hidden" name="action" value="subscribe"><input type="hidden" name="bookbuzz" value="1">');
document.write('				<div style="width: 219px; float: left; display: inline; margin-left: 1px; padding: 8px 0px 6px 0px; border-right: 1px solid #b2b2b2; display: inline;">');
document.write('					<!--[if IE 5.5000]>');
document.write('						<img src="/images/blank.gif" alt="" width="219" height="0" />');
document.write('					<![endif]-->');
document.write('						<div style="float: left; text-align: center; margin-right: 8px;">');
document.write('							<!--TODO: restore previous search term-->');
document.write('							<input type="text" name="email" id="email" style="width: 128px;"/>');
document.write('						</div>');
document.write('						<div style="float: left; padding-left: 0px; margin: 0;">');
document.write('							<label for="searchText2"><input type="image" name="searchBtn2" src="/images/header_submitbutton.gif" style="margin-bottom: -2px;" alt="Search button" onmouseover="this.src=\'/images/header_submitbuttonON.gif\';" onmouseout="this.src=\'/images/header_submitbutton.gif\';" /></label>');
document.write('						</div>');
document.write('				</div>');
document.write('				</form>');
document.write('			</div>');
document.write('		</div><!--rightBox-->');
document.write('		<!--bottom box border-->');
document.write('		<div class="rightBox" style="background: none;"><img');
document.write('			src="/images/newsletter_base.gif" alt="" width="231" height="10" border="0" />');
document.write('		</div><!--bottom box border-->');