document.write('			<div class="leftBox" style="margin-top: 8px;">');
document.write('			<img src="/images/lefthead_contests.gif" alt="Contests and Offers" width="180" height="40" border="0" /><div class="leftBoxInner">');
document.write('				<!--[if IE 5.5000]>');
document.write('					<img src="/images/blank.gif" alt="" width="170" height="0" border="0" style="padding: 0; margin: 0;" vspace="0" />');
document.write('				<![endif]-->');
document.write('				<div style="float: left; width: 65px; padding: 4px 0px 0px 4px; vertical-align: top; margin-top: 0px; margin-left: 2px; display: inline;">');
document.write('					<a href="/features/contests/index.html"><img src="/images/dyn/cover/?source=9780679313885&height=100&alternate=/images/dyn/cover/no_cover_100.gif&maxwidth=85" alt="" width="60" class="bordered" border="0" /></a>');
document.write('				</div>');
document.write('				<div style="float: left; width: 77px; margin-left: 10px; padding: 0px 12px 0px 0px; vertical-align: top; display: inline; margin-top: 0px;">');
document.write('					<span class="Tiny">');
document.write('						<a href="/features/contests/index.html" class="Bold">ENTER</a> this week\'s contest for a chance to win:<br /><br />');
document.write('						<!--TODO: link-->');
document.write('						<a href="/features/contests/index.html"" class="Bold">Enter the Babylon System</a>');
document.write('						<!--TODO: link-->');
document.write('						<br />Rodrigo Bascunan and Christian Pearce');
document.write('						<br />');
document.write('						<br />');
document.write('					</span>');
document.write('				</div>');
document.write('			</div><!--leftBoxInner-->');
document.write('			<div class="leftBoxInner">');
document.write('				<!--[if IE 5.5000]>');
document.write('					<img src="/images/blank.gif" alt="" width="170" height="0" />');
document.write('				<![endif]-->');
document.write('				<div style="background-color: #635C56; margin: 4px 0 0 6px; display: inline;" class="linkButton">');
document.write('					<div class="tight"><img src="/images/mini_chevron_right.gif" alt="" width="6" height="6" border="0" style="padding: 0px 4px 0px 0px; margin: 4px 0px 0px 0px" /></div>');
document.write('					<!--TODO: link-->');
document.write('					<div class="tight"><a href="/features/contests/index.html" class="linkWhite" style="text-decoration: none;">More Contests</a></div>');
document.write('				</div>');
document.write('			</div>');
document.write('		</div><!--leftBox-->');
document.write('		<!--bottom box border-->');
document.write('		<div class="leftBox" style="background: none; margin-top: 0px; padding: 0; display: inline;"><img');
document.write('			src="/images/left_boxbottom_gray.gif" alt="" width="180" height="10" vspace="0" border="0" style="padding: 0; margin-top: 0;" />');
document.write('		</div>');
document.write('		<!--bottom box border-->');