document.write('			<div class="rightBox">');
document.write('			<img src="/images/righthead_booklounge.gif" alt="booklounge.ca" width="231" height="50" border="0" vspace="0" style="padding: 0; margin: 0;"');
document.write('			/><div class="rightBoxInner">');
document.write('				<!--[if IE 5.5000]>');
document.write('					<img src="/images/blank.gif" alt="" width="220" height="0" border="0" style="padding: 0; margin: 0;" vspace="0" />');
document.write('				<![endif]-->');
document.write('				<div style="float: left; width: 110px; padding-top: 0px; vertical-align: top; margin-top: 0px; margin: 0;">');
document.write('					<p class="Sans Big Black Bold" style="padding-top: 0; margin-top: 4px;">');
document.write('						Listen to an interview with bestselling author Douglas Coupland');
document.write('					</p>');
document.write('					<p>');
document.write('						Access exclusive audio and video clips of your favourite authors, sneak a peek at what\'s coming and more.');
document.write('					</p>');
document.write('				</div>');
document.write('				<div style="width: 87px; float: left; margin-left: 16px; margin-top: 0px; padding: 8px 0px 0px 0px;">');
document.write('					<a href="http://www.booklounge.ca/"> <img src="/catalog/authphoto_110/5838_coupland_douglas.gif" alt="Douglas Coupland" width="88" border="1" /></a>');
document.write('					<p class="photoCredit">');
document.write('						photo credit: Mark Gilbert');
document.write('					</p>');
document.write('				</div>');
document.write('			</div><!--rightBoxInner-->');
document.write('			<div style="width: 204px; float: left; margin-left: 12px; padding: 10px 14px 6px 0px; border-right: 1px solid #b2b2b2; display: inline; margin-top: 0px;">');
document.write('				<!--[if IE 5.5000]>');
document.write('					<img src="/images/blank.gif" alt="" width="204" height="0" />');
document.write('				<![endif]-->');
document.write('				<div style="background-color: #096B6C;" class="linkButton"><!--linkButton-->');
document.write('					<div class="tight"><img src="/images/mini_chevron_right.gif" alt="" width="6" height="6" border="0" style="padding: 0px 4px 0px 0px; margin: 4px 0px 0px 0px;" /></div>');
document.write('					<!--TODO: link-->');
document.write('					<div class="tight"><a href="http://www.booklounge.ca/" class="linkWhite Small" style="text-decoration: none;">Visit BookLounge.ca</a></div>');
document.write('				</div>');
document.write('			</div>');
document.write('		</div><!--rightBox-->');
document.write('		<!--bottom box border-->');
document.write('		<div class="rightBox" style="padding: 0; border-right: 0; width: 231px; vertical-align: bottom; background: none;"><img');
document.write('			src="/images/newsletter_base.gif" alt="" width="231" height="10" border="0" style="padding: 0; margin: 0;" />');
document.write('		</div><!--bottom box border-->');