function showMenu()
{

document.write('    <table border=0 cellspacing=0 cellpadding=0>')
document.write('     <tr><td valign=top width=200 align=right>')
document.write('         <font class=t10b>Information</font><br>')
document.write('   	 <a href=i-welcome.html class=item1>Welcome</a><br>')
document.write('	 <a href=i-participants.html class=item1>Call for participants</a><br>')
document.write('	 <a href=i-scholarshipawardee.html class=item1>Scholarship awardee</a><br>')
document.write('	 <a href=i-demo-exhi.html class=item1>Demonstrations and exhibitions</a><br>')
document.write('	 <a href=i-forum.html class=item1>Research/Study opportunities</a><br>')
document.write('	 <img src=img/new.gif>&nbsp;<a href=i-post.html class=item1>Post COLING2002 news</a><br>')
document.write('	 <font class=t10r>Closed items:</font><br>')
document.write('	 <a href=i-papers.html class=item1>Call for papers</a><br>')
document.write('	 <a href=i-workshops.html class=item1>Call for workshops</a><br>')
document.write('	 <a href=i-wspapers.html class=item1>Call for workshop papers</a><br>')
document.write('	 <a href=i-demonstration.html class=item1>Call for demonstrations</a><br>')
document.write('	 <a href=i-exhibition.html class=item1>Call for exhibitions</a><br>')
document.write('	 <a href=i-scholarship.html class=item1>Scholarship</a><br>')
document.write('         <img src=img/line.jpg><br>')
document.write('')
document.write('         <font class=t10b>Paper Submission</font><br>')
document.write('	 <a href=http://www.ikp.uni-bonn.de/coling2002/cfp.html class=item1 target="_blank">Manuscript submission</a><br>')
document.write('	 <a href=p-camera.html class=item1>Camera-ready submission</a><br>')
document.write('	 <a href=p-presenter.html class=item1>Presenter instructions</a><br>')
document.write('         <img src=img/line.jpg><br>')
document.write('')
document.write('         <font class=t10b>Registration</font><br>')
document.write('	 <a href=r-general.html class=item1>General information</a><br>')
document.write('	 <font color=red>(closed)</font><a href=r-online.html class=item1>Online registration</a><br>')
document.write('	 <a href=r-scip.html class=item1>Tutorials:¬ì¾Ç¤Hsubscribers</a><br>')
document.write('	 <a href=r-accommodation.html class=item1>Accommodation</a><br>')
document.write('	 <font color=red>(closed)</font><a href=r-hotelreserve.html class=item1>Hotel reservation</a><br>')
document.write('	 <a href=r-hotelroommates.html class=item1>Find roommates</a><br>')
document.write('         <img src=img/line.jpg><br>')
document.write('')
document.write('         <font class=t10b>Organization</font><br>')
document.write('	 <a href=http://www.dcs.shef.ac.uk/research/ilash/iccl/ target=_blank class=item1>ICCL</a><br>')
document.write('	 <a href=o-aclcp.html class=item1>ACLCLP</a><br>')
document.write('	 <a href=o-organizing.html class=item1>Organizing committee</a><br>')
document.write('	 <a href=o-program.html class=item1>Program committee</a><br>')
document.write('	 <a href=o-sponsors.html class=item1>Sponsors</a><br>')
document.write('         <img src=img/line.jpg><br>')
document.write('')
document.write('         <font class=t10b>Conference</font><br>')
document.write('	 <a href=c-dates.html class=item1>Important dates</a><br>')
document.write('	 <a href=c-conference.html class=item1>Conference program</a><br>')
document.write('	 <a href=c-keynote.html class=item1>Keynote speech</a><br>')
document.write('	 <a href=c-panel.html class=item1>Panel discussion</a><br>')
document.write('	 <a href=c-acceptedpapers.html class=item1>Accepted papers</a><br>')
document.write('         <img src=img/line.jpg><br>')
document.write('')
document.write('         <font class=t10b>Workshops & Tutorials</font><br>')
document.write('	 <a href=w-tutorials.html class=item1>Tutorials</a><br>')
document.write(' 	 <a href=w-post-conference.html class=item1>Post-conference workshops</a><br>')
document.write('	 <a href=w-post-conference.html class=item1>Workshop accepted papers</a><br>')
document.write('         <img src=img/line.jpg><br>')
document.write('')
document.write('         <font class=t10b>Download Area</font><br>')
document.write('	 <a href=pdf/coling2002-programme.pdf class=item1 target=_blank>Conference program in pdf</a><br>')
document.write('	 <a href=pdf/coling2002-handbook.pdf class=item1 target=_blank>Conference handbook in pdf</a><br>')
document.write('         <img src=img/line.jpg><br>')
document.write('')
document.write('         <font class=t10b>Satellite Events</font><br>')
document.write('	 <a href=http://www.cm.nctu.edu.tw/ISCSLP2002/ class=item1 target="_blank">ISCSLP2002</a><br>')
document.write('         <img src=img/line.jpg><br>')
document.write('')
document.write('         <font class=t10b>Transportation</font><br>')
document.write('	 <a href=t-venue.html class=item1>Venue</a><br>')
document.write('	 <a href=t-visa.html class=item1>Visa</a><br>')
document.write('	 <a href=t-maps.html class=item1>Maps</a><br>')
document.write('	 <a href=t-taipei.html class=item1>Access to Taipei</a><br>')
document.write('	 <a href=t-conference.html class=item1>Access to conference site</a><br>')
document.write('	 <a href=t-workshop.html class=item1>Access to workshop site</a><br>')
document.write('	 <a href=t-introductionTP.html class=item1>Introduction to Taipei</a><br>')
document.write('	 <a href=t-phone.html class=item1>Useful phone numbers</a><br>')
document.write('	 <a href=t-parking.html class=item1>Car Parking (local participants)</a><br>')
document.write('         <img src=img/line.jpg><br>')
document.write('')
document.write('         <font class=t10b>Social Events</font><br>')
document.write('	 <a href=s-reception.html class=item1>Welcome reception</a><br>')
document.write('	 <a href=s-banquet.html class=item1>Banquet</a><br>')
document.write('	 <a href=s-excursion.html class=item1>Excursion</a><br>')
document.write('	 <a href=s-show.html class=item1>Lunchtime mini-concert series</a><p>')
document.write('     </td></tr>')
document.write('     </table>')
}
