Menu.CLASS_BGCOLOR = '#EFF3FF';
Menu.TOP_COORD = top_coord + 1;
Menu.SM_TOP_COORD = Menu.TOP_COORD + 22;
Menu.CSM_TOP_COORD = Menu.TOP_COORD + 22;
Menu.CL_BGCOLOR = '#FC0208';
Menu.SM_LEFT_COORD = Menu.LEFT_COORD;
Menu.SM_HEADER_TOP_COORD = (228 + Menu.TOP_COORD - 302 - 15);
Menu.MI_BGCOLOR = ['#001B6A','#000033','#336699','#3399CC'];
Menu.MI_ROVR_BGCOLOR = '#5F87FF';
Menu.SM_BGCOLOR = '#4F4F68';
Menu.SM_HEADER = '#003366';
Menu.SI_EVEN_BGCOLOR = '#F9F8FA';
Menu.SI_ODD_BGCOLOR = '#E5E5E5';
Menu.CSI_EVEN_BGCOLOR = '#FFFAED';
Menu.CSI_ODD_BGCOLOR = '#F9E7DB';
Menu.SI_ROVR_BGCOLOR = '#C1D5FF';
var hNAVBAR = new Menu();
hNAVBAR.m_i[0] = new MenuI('a', 'Home', 'asub','/', 53, 10, 'mi');
hNAVBAR.m_i[0].s_m.s_i = [
new SubI('sub0link0', '<b>Home Page</b>', '/'),
new SubI('sub0link1', 'Site Index', '/siteindex/'),
new SubI('sub0link2', 'About Us', '/aboutus/'),
new SubI('sub0link3', 'Advertise With Us', '/mediakit/'),
new SubI('sub0link4', 'Help/Feedback', '/contactus/'),
new SubI('sub0link5', 'Privacy Policy', '/privacypolicy/'),
new SubI('sub0link6', 'User Agreement', '/useragreement/'),
new SubI('sub0link7', 'Affiliates', '/affiliates/'),
new SubI('sub0link8', 'Newsletters', 'http://update.masslive.com/adv_masslive/newsletters/masslive/subscribe.htm')
]
hNAVBAR.m_i[1] = new MenuI('b', 'News+Biz', 'bsub','/news', 78, 63, 'mi');
hNAVBAR.m_i[1].s_m.s_i = [
new SubI('sub1link0', '<b>News Home</b>', '/news/'),
new SubI('sub1link1', '<b>The Republican</b>', '/republican/'),
new SubI('sub1link2', 'Newsflash', '/newsflash/'),
new SubI('sub1link3', 'Chicopee/Holyoke', '/chicopeeholyoke/republican/'),
new SubI('sub1link4', 'Weather', '/weather/'),
new SubI('sub1link5', 'Hamp/Frank', '/hampfrank/republican/'),
new SubI('sub1link6', '<b>Blogs</b>', '/blogs/'),
new SubI('sub1link7', 'Metro East', '/metroeast/republican/'),
new SubI('sub1link8', 'Breaking News', 'http://blog.masslive.com/breakingnews/'),
new SubI('sub1link9', 'Metro West', '/metrowest/republican/'),
new SubI('sub1link10', 'The Fray', 'http://fray.blogs.masslive.com/'),
new SubI('sub1link11', 'Springfield', '/springfield/republican/'),
new SubI('sub1link12', '<b>Features</b>', '/news/features.ssf'),
new SubI('sub1link13', 'Editorials', '/editorials/republican/'),
new SubI('sub1link14', 'Church in Crisis', '/news/church/'),
new SubI('sub1link15', 'Graphics', '/republican/graphics/'),
new SubI('sub1link16', 'Gay Marriage', '/news/gay_marriage/'),
new SubI('sub1link17', 'Letters to Editor', '/letters/republican/'),
new SubI('sub1link18', 'Corruption Probes', '/springfield/corruption/'),
new SubI('sub1link19', 'Paid Death Notices', 'http://www.legacy.com/masslive/LegacyHome.asp'),
new SubI('sub1link20', 'Haleigh Poutre', '/news/poutre/'),
new SubI('sub1link21', '<b>Photos</b>', '/galleries/'),
new SubI('sub1link22', 'Viewpoint', '/viewpoint/republican/'),
new SubI('sub1link23', 'News Photos', '/news/photos/'),
new SubI('sub1link24', '<b>Columnists</b>', '/republican/columnists/'),
new SubI('sub1link25', 'Republican Photos', '/republican/photos/'),
new SubI('sub1link26', 'Barbara Bernard', '/bernard/republican/'),
new SubI('sub1link27', 'Seen@ Photos', '/living/photos/'),
new SubI('sub1link28', 'Mike Burke', '/burke/republican/'),
new SubI('sub1link29', '<b>Business</b>', '/business/'),
new SubI('sub1link30', 'Cries & Whispers', '/cries/republican/'),
new SubI('sub1link31', 'American Biz Daily', '/business/ambizdaily/'),
new SubI('sub1link32', 'Just Ask', '/justask/republican/'),
new SubI('sub1link33', 'Market Updates', '/newsflash/business/'),
new SubI('sub1link34', 'Larry McDermott', '/mcdermott/republican/'),
new SubI('sub1link35', 'Property Transfers', '/deeds/republican/'),
new SubI('sub1link36', 'Tom Shea', '/shea/republican/'),
new SubI('sub1link37', 'Kenneth Ross', '/ross/republican/'),
new SubI('sub1link38', '<b>Local Buzz</b>', '/localbuzz/')
]
hNAVBAR.m_i[2] = new MenuI('c', 'Local', 'csub','/local', 50, 142, 'mi');
hNAVBAR.m_i[2].s_m.s_i = [
new SubI('sub2link0', '<b>Local Home</b>', '/local/'),
new SubI('sub2link1', '<b>WMass Blogs</b>', '/blogs/'),
new SubI('sub2link2', 'Events', '/events/'),
new SubI('sub2link3', 'Blog Beat', 'http://blogbeat.blogs.masslive.com/'),
new SubI('sub2link4', '<b>Forums</b>', '/forums/'),
new SubI('sub2link5', 'Some Girl', 'http://somegirl.blogs.masslive.com/'),
new SubI('sub2link6', 'Amherst', '/forums/amherst/'),
new SubI('sub2link7', 'Prospect Perspec.', 'http://prospectperspective.blogs.masslive.com/'),
new SubI('sub2link8', 'Belchertown', '/forums/belchertown/'),
new SubI('sub2link9', 'Feedback', 'http://feedback.blogs.masslive.com/'),
new SubI('sub2link10', 'Chicopee', '/forums/chicopee/'),
new SubI('sub2link11', 'Valley Victuals', 'http://victuals.blogs.masslive.com/'),
new SubI('sub2link12', 'Easthampton', '/forums/easthampton/'),
new SubI('sub2link13', 'The Fray', 'http://fray.blogs.masslive.com/'),
new SubI('sub2link14', 'East Longmeadow', '/forums/eastlongmeadow/'),
new SubI('sub2link15', 'Movie Boy', 'http://movieboy.blogs.masslive.com/'),
new SubI('sub2link16', 'Holyoke', '/forums/holyoke/'),
new SubI('sub2link17', 'Sound Check', 'http://soundcheck.blogs.masslive.com/'),
new SubI('sub2link18', 'Longmeadow', '/forums/longmeadow/'),
new SubI('sub2link19', '<b>Find It</b>', '/local/'),
new SubI('sub2link20', 'Ludlow', '/forums/ludlow/'),
new SubI('sub2link21', 'Maps+Directions', '/maps/'),
new SubI('sub2link22', 'Northampton', '/forums/northampton/'),
new SubI('sub2link23', 'Weather', '/weather/'),
new SubI('sub2link24', 'South Hadley', '/forums/southhadley/'),
new SubI('sub2link25', 'White Pages', 'http://masslive.switchboard.com/bin/cgiqa.dll?MEM=227'),
new SubI('sub2link26', 'Springfield', '/forums/springfield/'),
new SubI('sub2link27', 'Yellow Pages', 'http://www.switchboard.com/bin/cgidir.dll?MEM=227'),
new SubI('sub2link28', 'West Springfield', '/forums/westspringfield/'),
new SubI('sub2link29', '<b>Guides</b>', '/local/'),
new SubI('sub2link30', 'Westfield', '/forums/westfield/'),
new SubI('sub2link31', 'Your Stories Northampton', 'http://local.masslive.com/northampton/'),
new SubI('sub2link32', 'Wilbraham', '/forums/wilbraham/'),
new SubI('sub2link33', 'WMass', '/visitorsguide/')
]
hNAVBAR.m_i[3] = new MenuI('d', 'Sports', 'dsub','/sports', 55, 192, 'mi');
hNAVBAR.m_i[3].s_m.s_i = [
new SubI('sub3link0', '<b>Sports Home</b>', '/sports/'),
new SubI('sub3link1', '<b>HS Sports Home</b>', '/varsity/'),
new SubI('sub3link2', 'AP SportsFlash', '/sportsflash/'),
new SubI('sub3link3', 'Football', '/varsity/football/'),
new SubI('sub3link4', '<b>College Sports</b>', '/collegesports/republican/'),
new SubI('sub3link5', 'Basketball', '/varsity/basketball'),
new SubI('sub3link6', 'UMass Basketball', '/umassbasketball/'),
new SubI('sub3link7', 'Boys Soccer', '/varsity/boyssoccer/'),
new SubI('sub3link8', 'MinuteBlog', 'http://minutemen.blogs.masslive.com'),
new SubI('sub3link9', 'Girls Soccer', '/varsity/girlssoccer/'),
new SubI('sub3link10', 'UMass Audio', '/umassbasketball/audio/complete'),
new SubI('sub3link11', 'Baseball', '/varsity/baseball'),
new SubI('sub3link12', 'UMass Sports', '/umass/'),
new SubI('sub3link13', 'Softball', '/varsity/softball'),
new SubI('sub3link14', '<b>MLB</b>', '/mlb/'),
new SubI('sub3link15', 'Videos', '/varsity/mass/video/complete/'),
new SubI('sub3link16', 'Red Sox', '/redsox/'),
new SubI('sub3link17', '<b>Blogs</b>', '/blogs/'),
new SubI('sub3link18', 'Sox Monster', 'http://blog.masslive.com/redsoxmonster/'),
new SubI('sub3link19', 'School Scene', 'http://blog.masslive.com/schoolscene'),
new SubI('sub3link20', '<b>NFL</b>', '/nfl'),
new SubI('sub3link21', 'Varsity Voice', 'http://blog.masslive.com/varsityvoice'),
new SubI('sub3link22', 'Patriots', '/patriots/'),
new SubI('sub3link23', 'Berkshire Sports', 'http://berkshiresports.blogs.masslive.com/'),
new SubI('sub3link24', 'Patriots Blog', 'http://patriots.blogs.masslive.com/'),
new SubI('sub3link25', 'EMass Press Pass', 'http://emasspresspass.blogs.masslive.com'),
new SubI('sub3link26', '<b>NBA</b>', '/nba'),
new SubI('sub3link27', '<b>Photos</b>', '/galleries/'),
new SubI('sub3link28', 'Celtics', '/celtics'),
new SubI('sub3link29', 'HS Sports Photos', '/varsity/photos/'),
new SubI('sub3link30', 'Hoop Hall', '/hooptown'),
new SubI('sub3link31', '<b>More Sports</b>', '/sports/complete/'),
new SubI('sub3link32', '<b>NHL</b>', '/nhl/'),
new SubI('sub3link33', 'Auto Racing', '/autoracing/'),
new SubI('sub3link34', 'Bruins', '/bruins/'),
new SubI('sub3link35', 'Golf', '/golf/'),
new SubI('sub3link36', 'Falcons', '/falcons/'),
new SubI('sub3link37', 'Outdoors', '/outdoors'),
new SubI('sub3link38', '<b>Columnists</b>', '/republican/columnists/'),
new SubI('sub3link39', '<b>Summer Sports</b>', '/summersports')
]
hNAVBAR.m_i[4] = new MenuI('e', 'Forums', 'esub','/forums', 67, 250, 'mi');
hNAVBAR.m_i[4].s_m.s_i = [
new SubI('sub4link0', '<b>Forums Home</b>', '/forums/'),
new SubI('sub4link1', '<b>Local</b>', '/forums/index.ssf?local.ssf'),
new SubI('sub4link2', 'Forums FAQ', '/forums/index.ssf?faq.html'),
new SubI('sub4link3', 'Agawam', '/forums/agawam/'),
new SubI('sub4link4', 'Forums Search', '/forums/search/'),
new SubI('sub4link5', 'Chicopee', '/forums/chicopee/'),
new SubI('sub4link6', 'Help Center', '/forums/index.ssf?help.html'),
new SubI('sub4link7', 'Holyoke', '/forums/holyoke/'),
new SubI('sub4link8', 'Register Now', 'http://register.masslive.com/regdb/servlet/Reg?affiliate=MassLive.com&source=forums&_returnurl=http://www.masslive.com/forums/welcome/'),
new SubI('sub4link9', 'Springfield', '/forums/springfield/'),
new SubI('sub4link10', '<b>Pro Sports</b>', '/forums/index.ssf?sports.ssf'),
new SubI('sub4link11', 'Westfield', '/forums/westfield/'),
new SubI('sub4link12', 'Bruins', '/forums/bruins/'),
new SubI('sub4link13', '<b>News</b>', '/forums/index.ssf?news.ssf'),
new SubI('sub4link14', 'Celtics', '/forums/celtics/'),
new SubI('sub4link15', 'NewsWatch', '/forums/newswatch/'),
new SubI('sub4link16', 'Falcons', '/forums/falcons/'),
new SubI('sub4link17', 'Politics', '/forums/politics/'),
new SubI('sub4link18', 'Patriots', '/forums/patriots/'),
new SubI('sub4link19', 'Schools & Ed.', '/forums/schools/'),
new SubI('sub4link20', 'Red Sox', '/forums/redsox/'),
new SubI('sub4link21', '<b>Entertainment</b>', '/forums/'),
new SubI('sub4link22', '<b>UMass Sports</b>', '/forums/'),
new SubI('sub4link23', 'Movies', '/forums/movies/'),
new SubI('sub4link24', 'Basketball', '/forums/umasshoops/'),
new SubI('sub4link25', 'SoundBoard', '/forums/soundboard/'),
new SubI('sub4link26', 'Football', '/forums/umfootball/'),
new SubI('sub4link27', 'Wine & Dine', '/forums/wineanddine/'),
new SubI('sub4link28', 'Hockey', '/forums/umasshockey/'),
new SubI('sub4link29', '<b>Living</b>', '/forums/index.ssf?living.ssf'),
new SubI('sub4link30', 'Lacrosse', '/forums/umlacrosse/'),
new SubI('sub4link31', 'Parents', '/forums/parents/'),
new SubI('sub4link32', '<b>HS Sports</b>', '/forums/index.ssf?hssports.ssf'),
new SubI('sub4link33', 'Pets', '/forums/pets/'),
new SubI('sub4link34', '<b>More Sports</b>', '/forums/index.ssf?sports.ssf'),
new SubI('sub4link35', 'Relationships', '/forums/relationships/'),
new SubI('sub4link36', 'Fishing', '/forums/fishing/'),
new SubI('sub4link37', 'Tag Sale', '/forums/tagsale/')
]
hNAVBAR.m_i[5] = new MenuI('f', 'Multimedia', 'fsub','/multimedia', 95, 316, 'mi');
hNAVBAR.m_i[5].s_m.s_i = [
new SubI('sub5link0', '<b>Multimedia</b>', '/multimedia/'),
new SubI('sub5link1', '<b>Photos home</b>', '/galleries/'),
new SubI('sub5link2', 'News video', '/news/mass/video/complete/'),
new SubI('sub5link3', '<i>Republican</i> daily', '/republican/photos/'),
new SubI('sub5link4', 'Varsity video', '/varsity/mass/video/complete/'),
new SubI('sub5link5', 'Varsity photos', '/varsity/photos/'),
new SubI('sub5link6', 'Entertainment vids', '/entertainment/mass/video/complete/'),
new SubI('sub5link7', 'News photos', '/news/photos/'),
new SubI('sub5link8', '<b>CampusCam</b>', '/campuscam/'),
new SubI('sub5link9', 'Cam photos', '/campuscam/photos/'),
new SubI('sub5link10', 'Springfield police', '/police/springfield/'),
new SubI('sub5link11', 'Seen@ photos', '/living/photos/'),
new SubI('sub5link12', 'Holyoke police', '/police/holyoke/'),
new SubI('sub5link13', 'Weddings photos', '/weddings/photos/'),
new SubI('sub5link14', 'WMUA (UMass)', '/wmua/'),
new SubI('sub5link15', 'UMass photos', '/umassbasketball/photos/'),
new SubI('sub5link16', 'Falcons broadcasts', '/falconslive/'),
new SubI('sub5link17', 'More photos', '/galleries/'),
new SubI('sub5link18', 'Local music radio', '/music/bands/'),
new SubI('sub5link19', 'MP3 downloads', '/music/bands/archive/complete/')
]
hNAVBAR.m_i[6] = new MenuI('g', 'Living', 'gsub','/living', 55, 244, 'mi');
hNAVBAR.m_i[6].s_m.s_i = [
new SubI('sub6link0', '<b>Living Home</b>', '/living/'),
new SubI('sub6link1', '<b>Blogs</b>', '/blogs'),
new SubI('sub6link2', 'Recipe column', '/kenney/republican/'),
new SubI('sub6link3', 'Parenting Project', 'http://blog.masslive.com/parentingproject/'),
new SubI('sub6link4', 'Girls Have Fun', '/living/girls/'),
new SubI('sub6link5', 'Religion', '/religion/republican/'),
new SubI('sub6link6', 'UNlisted', '/unlisted/'),
new SubI('sub6link7', '<b>Health & Fitness</b>', '/health/'),
new SubI('sub6link8', '<b>Weddings</b>', '/weddings/'),
new SubI('sub6link9', 'Shaping Up', '/shapingup/'),
new SubI('sub6link10', 'Wedding Photos', '/weddings/photos/'),
new SubI('sub6link11', '<b>Home & Garden</b>', '/hg/'),
new SubI('sub6link12', 'Engagement Pix', '/engagements/photos/'),
new SubI('sub6link13', 'Lee Reich', '/reich/republican/'),
new SubI('sub6link14', 'Local Weddings', '/weddings/republican/'),
new SubI('sub6link15', 'Home Advice', '/forums/home/'),
new SubI('sub6link16', 'Anniversaries', '/weddings/republican/annivindex.ssf'),
new SubI('sub6link17', '<b>Pets</b>', '/living/pets/'),
new SubI('sub6link18', 'Engagements', '/weddings/republican/engageindex.ssf'),
new SubI('sub6link19', '<b>Life After 50</b>', '/lifeafter50/')
]
hNAVBAR.m_i[7] = new MenuI('h', 'Entertainment', 'hsub','/entertainment', 107, 352, 'mi');
hNAVBAR.m_i[7].s_m.s_i = [
new SubI('sub7link0', '<b>Entertainment</b>', '/entertainment/'),
new SubI('sub7link1', '<b>Music</b>', '/music/'),
new SubI('sub7link2', 'Photos', '/entertainment/photos/'),
new SubI('sub7link3', 'Club Scout', '/clubscout/republican/'),
new SubI('sub7link4', 'Television', '/entertainment/tv/'),
new SubI('sub7link5', 'Live Wire', '/moorhouse/republican/'),
new SubI('sub7link6', 'Weekend Guide', '/weekend/republican/'),
new SubI('sub7link7', 'MP3 Downloads', '/music/bands/'),
new SubI('sub7link8', '<b>Movies</b>', '/movies/'),
new SubI('sub7link9', 'Playback', '/ohare/republican/'),
new SubI('sub7link10', 'Movies Forum', '/forums/movies/'),
new SubI('sub7link11', 'SoundBoard', '/forums/soundboard/'),
new SubI('sub7link12', '<b>Dining Guide</b>', '/dining/'),
new SubI('sub7link13', '<b>Arts+Events</b>', '/events/'),
new SubI('sub7link14', 'Beer Nut', '/beernut/republican/'),
new SubI('sub7link15', 'Fine Art', '/fineart/republican/'),
new SubI('sub7link16', 'Dining Out', '/diningout/republican/'),
new SubI('sub7link17', '<b>Blogs</b>', '/blogs/'),
new SubI('sub7link18', 'Off the Menu', '/offthemenu/republican/'),
new SubI('sub7link19', 'Feedback', 'http://feedback.blogs.masslive.com/'),
new SubI('sub7link20', 'Wine & Dine', '/forums/wineanddine/'),
new SubI('sub7link21', 'Movie Boy', 'http://movieboy.blogs.masslive.com/'),
new SubI('sub7link22', '<b>Local Buzz</b>', '/localbuzz/'),
new SubI('sub7link23', 'Sound Check', 'http://soundcheck.blogs.masslive.com/'),
new SubI('sub7link24', 'Local Buzz Forum', '/forums/localbuzz/'),
new SubI('sub7link25', 'Tuning Out', 'http://blog.masslive.com/tuningout/'),
new SubI('sub7link26', 'Local Buzz Photos', '/localbuzz/photos/'),
new SubI('sub7link27', 'Valley Victuals', 'http://victuals.blogs.masslive.com/')
]
hNAVBAR.m_i[8] = new MenuI('i', '<img src="/dhtml/hnavbar_class/images/classtitle.gif" border=0>', 'isub','/classifieds', 193, 244, 'miclass');
hNAVBAR.m_i[8].s_m.s_i = [
new SubI('sub8link0', 'Search our listings for your next job!', 'http://www.masslive.com/jobs/', 'Best Local Jobs:', 'Local employers want you', '/dhtml/hnavbar_class/images/icons/spacer.gif'),
new SubI('sub8link1', 'We\'ve got the local MLS listings', 'http://www.masslive.com/realestate/', '', 'Stop paying rent -- start building equity!', '/dhtml/hnavbar_class/images/icons/spacer.gif'),
new SubI('sub8link2', 'Browse thousands of new and used cars', 'http://www.masslive.com/autos/', 'Best Local Autos:', 'Now is the best time to buy', '/dhtml/hnavbar_class/images/icons/spacer.gif'),
new SubI('sub8link3', 'Landscaping, plumbing, contractors and more', 'http://www.masslive.com/classifieds/services/', '', 'Check our service listings for help around the house', '/dhtml/hnavbar_class/images/icons/spacer.gif'),
new SubI('sub8link4', 'Click here to place your ad online', 'http://www.masslive.com/placead/', 'Need money?', 'Unload your stuff in classifieds', '/dhtml/hnavbar_class/images/icons/spacer.gif')
]
